### ISSUE TITLE
Re-implement UUID filtering on Android

### ISSUE THREAD

**Issue by don** [don/cordova-plugin-ble-central#10]
UUID filtering in [bluetoothAdapter.leScan](http://developer.android.com/reference/android/bluetooth/BluetoothAdapter.html#startLeScan(java.util.UUID[],%20android.bluetooth.BluetoothAdapter.LeScanCallback)) appears to be broken. Switch to leScan without filters, manually parse advertising data in the scan callback and filter results in the plugin before returning to Cordova.

**Comment by don** [comment]
Won't fix. Newer version of android are getting better.

**Comment by abcd-ca** [comment]
Filtering works on Android 5.1.1, Google Nexus 4, FYI.

**Comment by don** [comment]
@abcd-ca Thanks for the update. Filtering problems appear to be more of a 4.3 and 4.4 issue. 5.x and 6.x are working well.

**Comment by abcd-ca** [comment]
Cool, thanks for the extra detail @don! I'm happy to now also know the specific versions it's problematic for as I may decide to detect those and not filter.
