### ISSUE TITLE
startNotification sometimes throws Peripheral not connected or code 133  

### ISSUE THREAD

**Issue by fudom** [don/cordova-plugin-ble-central#1003]
We use [startNotification](https://github.com/don/cordova-plugin-ble-central?tab=readme-ov-file#startnotification) after BLE connect (incl. scan before) on app start. It works. But sometimes it fails with error:

> Peripheral {id} is not connected.

or 

> Write descriptor failed: 133

Tested on Android 8.1 and other versions. 

Error 133 (0x85) is [GATT_ERROR](https://android.googlesource.com/platform/external/bluetooth/bluedroid/+/android-5.1.1_r13/stack/include/gatt_api.h). But the reason or source is not clear. Any experience with that?

**Comment by peitschie** [comment]
> It would be great if we got a success callback upon successful subscription to the notification.

This is possible, by using `await ble.withPromises.startNotification(device_id, success, failure)` instead. I can't change the existing callback for fear of breaking backward compatibility, but the promise-returning version instead does exactly what you're requesting.
