### ISSUE TITLE
Module not found. Can't resolve 'cordova-plugin-ble-central'. (TS)

### ISSUE THREAD

**Issue by fudom** [don/cordova-plugin-ble-central#1007]
I get an error during build when 

```ts
import 'cordova-plugin-ble-central';
```

No error in VSCode. But the Angular build throws:

```
Error: Module not found: Error: Can't resolve 'cordova-plugin-ble-central'
```

Has anyone tested this? I'm not sure what's wrong in my tsconfig.json. Great that types are present. But I would add this to the docs or fix that. It seems that the [types.d.ts](https://github.com/don/cordova-plugin-ble-central/blob/1727fd1d305f3265a72debe51af81d515ec40a19/types.d.ts#L401) extends `window` with `ble`. It's not a module. Fine, but why this error? The [package.json](https://github.com/don/cordova-plugin-ble-central/blob/1727fd1d305f3265a72debe51af81d515ec40a19/package.json#L42) looks ok. I'm currently exhausted and appreciate any hint.

**Comment by peitschie** [comment]
Hi @fudom 

I generally reference these via triple-slash directives:
```
/// <reference types="cordova-plugin-ble-central" />
```

You can also add these to the `types` collection in your `tsconfig.json` instead if you prefer: https://www.typescriptlang.org/tsconfig#types

**Comment by peitschie** [comment]
Some related discussion at https://github.com/apache/cordova-plugin-file/issues/400#issuecomment-648731239
