### ISSUE TITLE
Scan BLE not returning any result

### ISSUE THREAD

**Issue by jorisnicolas** [don/cordova-plugin-ble-central#1011]
Hi,

When scanning for ble, using scan/startScan/scanWithOptions, I never have a returned result. 
It was working 1 or 2 months ago on the same device.
I have no error, in logcat I have nothing pointing me to a direction.
I have all the android permissions required.
Bluetooth is on.
I juste know that the java function "findLowEnergyDevices" is returning "No result".
I know it's not a problem with the android device or the ble device because other apps can pair with that device.

Is someone have an idea ?

Here's me specs:

<uses-permission android:name="android.permission.BLUETOOTH" />
<uses-permission android:name="android.permission.BLUETOOTH_ADMIN" />
<uses-permission android:name="android.permission.ACCESS_BACKGROUND_LOCATION" />
<uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION" />
<uses-permission android:name="android.permission.BLUETOOTH_SCAN" />
<uses-permission android:name="android.permission.BLUETOOTH_ADVERTISE" />

cordova-plugin-ble-central 1.7.2-slim "BLE"
Ionic:
   Ionic CLI          : 5.4.16 (C:\Users\jni\AppData\Local\Volta\tools\image\packages\ionic\node_modules\ionic)
   Ionic Framework    : ionic-angular 3.9.8
   @ionic/app-scripts : 3.2.4
Cordova:

   Cordova CLI       : 11.0.0 (cordova-lib@11.1.0)
   Cordova Platforms : android 10.1.2

**Comment by peitschie** [comment]
@jorisnicolas any hints as to what went wrong here? 🙂
