### ISSUE TITLE
Does this plug-in support Bluetooth 4.0 HM10 module?

### ISSUE THREAD

**Issue by bluemoon-i** [don/cordova-plugin-ble-central#1013]
Does this plug-in support Bluetooth 4.0 HM10 module?
After connecting to Bluetooth, failure when using ble.startNotification

**Comment by peitschie** [comment]
Hi @bluemoon-i 

Presuming this is a Bluetooth LE module, there should be no problems with support.

Are you using this on iOS or Android (or both)?

If Android, I'd highly recommend trying to connect and interact using [nRF Connect](https://play.google.com/store/apps/details?id=no.nordicsemi.android.mcp) as a nice way to double-check that the notification information is properly available for the BLE peripheral.

**Comment by bluemoon-i** [comment]
![Screenshot_2024-05-31-13-10-06-742_no nordicsemi android mcp](https://github.com/don/cordova-plugin-ble-central/assets/65477955/7dbf3c0c-b517-402d-8872-fec3ccbfa122)

**Comment by bluemoon-i** [comment]
I'm using Android, and it seems like I can receive notifications normally, but when I write '1', I get an error

**Comment by peitschie** [comment]
That looks like the peripheral itself has some issues. 

Given the response there is coming from the Android layer itself, it's not going to be caused by anything in this plugin.

I can't really help much with this I'm afraid. You'd need to contact whoever made the BLE device for support here.

**Comment by bluemoon-i** [comment]
OK, thanks for your answer
