### ISSUE TITLE
some users experiencing "cordova is not defined"

### ISSUE THREAD

**Issue by sithwarrior** [don/cordova-plugin-ble-central#1029]
We are experiencing some users that hit the following error (small percentage)

cordova is not defined

I suspect that it might be caused by this plugin calling cordova directly, the same issue seems to have happened in another plugin outlined here: https://github.com/EddyVerbruggen/SocialSharing-PhoneGap-Plugin/issues/243

in short its caused by the plugin calling `cordova.exec` directly instead of first `const exec = require('cordova/exec');`

As also mentioned in the issue, the official plugins use this pattern

**Comment by peitschie** [comment]
@sithwarrior I'd be happy to accept a PR for this if you have time?

**Comment by sithwarrior** [comment]
@peitschie  Made a PR and tested the change in my own app without issue

**Comment by peitschie** [comment]
This is released in 1.7.6

Sorry for the delay!
