### ISSUE TITLE
isConnected always returns false

### ISSUE THREAD

**Issue by markamccorkle** [don/cordova-plugin-ble-central#1033]
On the latest 1.7.7, calling `isConnected` on iOS is always returning false. Reverting to 1.7.4 fixes the issue.

**Comment by youssefadel94** [comment]
reverting to 1.7.4 causes the issue of malformed service uuid

**Comment by peitschie** [comment]
@markamccorkle is this just using `ble.isConnected`? Or are you using `ble.withPromises.isConnected`?

@youssefadel94 are you able to share the exact error you're seeing there? 1.7.4 did not have the UUID validation code in it, so I wonder what the issue you're seeing there.

**Comment by markamccorkle** [comment]
I can dig in further to see what the ionic native wrapper uses, but this is the latest ionic capacitor.

**Comment by peitschie** [comment]
Found the issue! MR up shortly

**Comment by peitschie** [comment]
Fix is released in version 1.7.8
