### ISSUE TITLE
Plugin stopped working after clearing platforms/ios and rebuilding

### ISSUE THREAD

**Issue by AndreasHeiberg** [don/cordova-plugin-ble-central#107]
I'm lost as to how it used to work but now doesn't?

https://www.dropbox.com/s/4dvkwmlt9qisghe/Screenshot%202015-10-13%2015.32.29.png?dl=1

**Comment by AndreasHeiberg** [comment]
Diff from when it worked 

https://www.dropbox.com/s/hpj0xekv107gsgk/Screenshot%202015-10-13%2015.42.15.png?dl=0

**Comment by AndreasHeiberg** [comment]
Yeah I just reverted that file in git and now it works. I have no clue what the problem is, but seems like something that should be considered.

**Comment by don** [comment]
The links to the screenshots don't work so I can't see what's happening. You can drag images into the text area when commenting on an issue.

**Comment by AndreasHeiberg** [comment]
<img width="1680" alt="screenshot 2015-10-13 15 32 29" src="https://cloud.githubusercontent.com/assets/820962/10526255/aa2d8e18-7381-11e5-8318-5e5e158f8e96.png">
![screenshot 2015-10-13 15 32 29 2](https://cloud.githubusercontent.com/assets/820962/10526254/aa2ad7fe-7381-11e5-992d-e720c65a1fe6.png)
<img width="1680" alt="screenshot 2015-10-13 15 42 15" src="https://cloud.githubusercontent.com/assets/820962/10526256/aa2e2ef4-7381-11e5-81ba-d4372dfceb9d.png">

**Comment by don** [comment]
Based on the diff it looks like you have both cordova-plugin-ble-central and cordova-plugin-bluetooth-serial installed. I don't think they'll work together on iOS.
