### ISSUE TITLE
"ble is not defined", cordova-plugin-ble-central 1.0.2 "BLE" with Ionic 

### ISSUE THREAD

**Issue by andreribeiropinto104** [don/cordova-plugin-ble-central#116]
Hi, 
I am conducting some tests with its ionic -ble example and when I try to run for this error appears .

"ble is not defined".

Have you any idea what that might be ?

My thank you for help with their examples.

![bleisnotdefined](https://cloud.githubusercontent.com/assets/11064437/10910480/900522c0-8237-11e5-87b4-87dbdc3504a8.PNG)
![cordovaplugins](https://cloud.githubusercontent.com/assets/11064437/10910481/90070b9e-8237-11e5-8172-8082b001b0dc.PNG)

**Comment by don** [comment]
"ble is not defined" typically means that the plugin is not installed correctly

Ensure you've installed the plugin with 

    cordova plugin add cordova-plugin-ble-central

If you're using PhoneGap Build, you need to install the plugin in config.xml

    <gap:plugin name="cordova-plugin-ble-central" source="npm" />

See https://github.com/don/ionic-ble for a sample ionic project that uses this plugin

**Comment by johnyso** [comment]
I had the same problem. I was working on another "older" git branch (without the plugin) after i switched back the plugin was there but maybe some references were missing. 
After running 
```
ionic platform rm android
ionic platform add android
```
it worked again.
the following command should solve this too:
```
ionic state restore
```

**Comment by redphoenix2k** [comment]
Hi guys, i have a similar issue but without ionic

if i call ble functions directly in javascript with the phonegap debugger it works, but if i call ble functions inside an angular controller or service i get the undefined error as well

**Comment by don** [comment]
@redphoenix2k if you can call the `ble` object from JavaScript, this sounds like a problem with the Angular code. Make sure you're not calling any Cordova APIs until after the deviceready event fires.

**Comment by redphoenix2k** [comment]
I quickly made a small test app to showcase my error

This is all the code & i still get the error in angular when testing with phonegap developper app on android

vanilla javascript calls it just fine

Any idea what the problem might be ?

![ble error](https://cloud.githubusercontent.com/assets/4505474/11506362/cdf4bdd0-9857-11e5-8cec-ec128bacfcdf.png)

**Comment by redphoenix2k** [comment]
ok i updated the test app a bit

i added a button to scan directly with javascript and fixed a typo in the previous code (it was wrong, i now put the ble device id string in proper brackets [])

you can see better from this second screenshot how one call gives the error and another doesnt

![ble error2](https://cloud.githubusercontent.com/assets/4505474/11507195/98a9eaac-985b-11e5-97d8-90decea1edd8.png)

**Comment by redphoenix2k** [comment]
@don issue solved

the problem was that when using angular i must explicitly add before it  <script type="text/javascript" src="cordova.js"></script>

doing so made the ble plugin work the same as in pure javascript

![ble error3](https://cloud.githubusercontent.com/assets/4505474/11525126/2fb7dcce-98d9-11e5-9784-570289b75334.png)

**Comment by vinimendes3** [comment]
@andreribeiropinto104 Did you solve your problem? I'm with the same problem here...

**Comment by sharathr3** [comment]
I m facing same issue here.. "ble not defined"  Guys, have you fixed ?
