### ISSUE TITLE
onDisconnect Method

### ISSUE THREAD

**Issue by JohnMcLear** [don/cordova-plugin-ble-central#117]
An event that fires if a connected device goes out of range..  Possible?

**Comment by halindrome** [comment]
You essentially have this now.  The fail callback on "connect" gets called when the device disconnects.  At least, that's how it works for me.

**Comment by don** [comment]
@JohnMcLear @halindrome is correct. The failure callback for [ble.connect](https://github.com/don/cordova-plugin-ble-central#connect) will be called when the peripheral disconnects.

**Comment by JohnMcLear** [comment]
Ah, interesting..
