### ISSUE TITLE
Add timeouts

### ISSUE THREAD

**Issue by RangerMauve** [don/cordova-plugin-ble-central#125]
[Reading up on issues with Android's bluetooth stack](https://github.com/iDevicesInc/SweetBlue/wiki/Android-BLE-Issues#general-issues), I noticed that callbacks sometimes won't get fired and that developers should be tracking timeouts themselves.

I actually noticed this happening in my code the other day when my call to `connect` never succeeded nor failed and borked some of my application logic.

Now I'm sure that people can figure out adding timers on their own over top of this library, but I think that since it already does queuing of blueooth events, this might be a logical addition.

**Comment by don** [comment]
I'd rather have apps deal with this for now, but I'll consider pull requests if it can be implemented cleanly.
