### ISSUE TITLE
How to monitor the way disconnect bluetooth

### ISSUE THREAD

**Issue by YouSirY** [don/cordova-plugin-ble-central#128]
First I use ble connect bluetooth and start notify , everything is well
but when I turn off the mobile bluetooth 
App could not get any notify about disconnect event
Midway disconnected

**Comment by YouSirY** [comment]
Can you help me?

**Comment by don** [comment]
The failure callback on the [ble.connect](https://github.com/don/cordova-plugin-ble-central#connect) function will get called when the peripheral disconnects.
