### ISSUE TITLE
Incorrect notification data

### ISSUE THREAD

**Issue by lijunxyz** [don/cordova-plugin-ble-central#130]
I am building a phone app using Ionic framework in which cordova-plugin-ble-central plugin is used. The BLE peripheral has a characteristic which pushes notifications to central upon writes. I first enable the notification and register the callback by calling startNotification() function, and then write to that characteristic. Both operations seem to be successful because both notification handler and write success callback are called. The code snippets are below. The syntax of the function is slightly different and should be self-explanatory because it is wrapped around by another AngularJS layer which splits off the callbacks:

```
provider.startNotification(
  sensor_id,   // MAC 
  target_metadata_service,  // service UUID string
  target_metadata_char  // characteristic UUID string
  ).then(
  function (data) {
	console.log("get notification with data: " + JSON.stringify(data));
  },
  function (error) {
	console.log("notification failed with error " + error);
  }
);

var buf = new ArrayBuffer(1);
buf[0] = 0x01;
provider.write(
  sensor_id,   // MAC 
  target_metadata_service,  // service UUID string
  target_metadata_char,  // characteristic UUID string
  buf).then(
  function (success) {
	  console.log("write data " + JSON.stringify(buf));
  },
 function (error) {
	 console.log("write failed: " + JSON.stringify(error));
 }
);
```

The problem is that the notification data is always an ArrayBuffer type with empty content, while I expect more than that. The same operation has been tested with another desktop BLE application and correct notification data can be obtained. So I think the BLE peripheral functions well. I am just wondering if I do things correctly on the BLE central side, or this behavior is caused by a potential bug.

**Comment by don** [comment]
@lijunxyz Are you sure you're getting an empty buffer? ArrayBuffers look empty "{}" when you stringify them. Check the size with `data.byteLength`. Print the contents with `JSON.stringify(new Uint8Array(data))` to see if you have some data.

If that doesn't work, it's likely something in your Angular wrapper. I recommend writing very simple test app that handles notifications.
