### ISSUE TITLE
ios isEnabled method not work well

### ISSUE THREAD

**Issue by wzhsh90** [don/cordova-plugin-ble-central#134]
the bluetooth i opened,but the first time i run the application,the isEnabled method get the state is not power on but unknown.
after serval test the problem caused by ios bluetooth sleep.

**Comment by don** [comment]
It sounds like `isEnabled` is working as documented if it is returning a status in a failure callback. This plugin can't make the Bluetooth stack or iOS wake up any faster. See if #136 works better for you.
