### ISSUE TITLE
i cant find out device

### ISSUE THREAD

**Issue by ted66** [don/cordova-plugin-ble-central#141]
I follow this example
https://github.com/don/cordova-plugin-ble-central/tree/master/examples/bluefruitle

i want to connect Arduino BLE 4.0, but i can find out the device.
i have set UUID and run this command
ble.scan([bluefruit.serviceUUID], 5, app.onDiscoverDevice, app.onError);

it also not find any.
How could i check and connect it?

**Comment by don** [comment]
Try scanning without any UUID `ble.scan([], 5, app.onDiscoverDevice, app.onError);`. Some Android devices have trouble filtering scan results by UUID.

**Comment by ted66** [comment]
@don 
ok i have try it, but is alway
thx your reply

**Comment by don** [comment]
@ted66 did the scan find your device without the UUID?

Make sure nothing is connected to you Bluetooth peripheral when scanning. Most device won't advertise when a central is connected.
