### ISSUE TITLE
Write with a return value

### ISSUE THREAD

**Issue by laics1984** [don/cordova-plugin-ble-central#147]
Thanks for the awesome plugin. I am trying to imitate the official bluno basic demo app http://www.dfrobot.com/wiki/index.php/Bluno_SKU:DFR0267 where it will return value when a value is sent. May I know which method to use?

**Comment by don** [comment]
I think the Bluno board has a UART-like BLE service. You'll need to find the UUIDs for this service. There should be a Transmit characteristic and Receive characteristic. When you have these UUIDs you should be able to adjust the [Adafruit example](https://github.com/don/cordova-plugin-ble-central/tree/master/examples/bluefruitle) or [RedBear example](https://github.com/don/cordova-plugin-ble-central/tree/master/examples/redbearlab) to work with your hardware.
