### ISSUE TITLE
Android ble.connect() function quesstions

### ISSUE THREAD

**Issue by DoFast** [don/cordova-plugin-ble-central#155]
![image](https://cloud.githubusercontent.com/assets/16661171/12259361/1eaeddaa-b950-11e5-976c-bd43e90fb6d7.png)

SOS , when I try to connect device always failed

**Comment by don** [comment]
There's not enough information here for me to help you.

**Comment by DoFast** [comment]
![image](https://cloud.githubusercontent.com/assets/16661171/12283602/c09babe2-b9e2-11e5-86d7-363df8e9fa7b.png)

In Android 22 alway connect error , the same as BluetoothLE - Rand Dusing's BLE plugin for Cordova
But in Ios is ok

**Comment by don** [comment]
What device are you connecting to?

Can you duplicate this on with different phones? Or does this only happen on one phone?

Can you connect with [nRF Master Contol Panel](https://play.google.com/store/apps/details?id=no.nordicsemi.android.mcp&hl=en)?

**Comment by DoFast** [comment]
![qq 20160113132957](https://cloud.githubusercontent.com/assets/16661171/12285896/12d12fb0-b9fa-11e5-89d3-55636a7335a5.jpg)
![qq 20160113132949](https://cloud.githubusercontent.com/assets/16661171/12285899/1c817600-b9fa-11e5-86dc-d63b0d688765.jpg)
I use the car OBD device.
And I have three differernt phones all have question

**Comment by DoFast** [comment]
nRF Master Contol Panel Always stay connecting....

**Comment by DoFast** [comment]
I change function  gatt = device.connectGatt(activity, false, this); to true 
In one of my phone android 5.0.1  is connected ,but the other still failed   
![qq 20160113195531](https://cloud.githubusercontent.com/assets/16661171/12293615/be552e4c-ba2f-11e5-81d1-5c7dd02f3f50.png)

**Comment by DoFast** [comment]
Now  when i connect decvice 
always  Log   "onClientConnectionState() - status=133 clientIf=5 device=xxxxxxx"
