### ISSUE TITLE
 if the peripheral is accidentally disconnected, will automatically reconnect?

### ISSUE THREAD

**Issue by BIGN0** [don/cordova-plugin-ble-central#156]

**Comment by don** [comment]
Your application needs to handle the reconnect. The [failure callback for connect](https://github.com/don/cordova-plugin-ble-central#connect) will be called when the peripheral unexpectedly disconnects. Even if the success callback has been called, the failure callback can be called at some point in the future.

    var onConnect = function(peripheral) {
      // the connection was successful
      // save the peripheral.id
      // discover services etc
    }

    var onDisconnect = function(peripheral) {
      // the peripheral unexpectedly disconnected 
      // add your reconnect logic here
    }

    ble.connect(deviceId, onConnect, onDisconnect);

**Comment by BIGN0** [comment]
var interval;

ble.connect(deviceId, onConnect, onDisconnect);

var onConnect = function(peripheral) {
    clearInterval(interval )
    //...
}

var onDisconnect = function(peripheral) {
    interval = setInterval(function(){
        ble.connect(deviceId, onConnect, onDisconnect);
    },5000)
}

Do you think it would be okay? 5 seconds to make a re connection,if the peripheral is accidentally disconnected

**Comment by don** [comment]
Some devices will need longer after they disconnect. You might add a decaying timer so each reconnection attempt takes a bit longer 5 seconds, 10 seconds, 20 seconds etc. Rather than trying to reconnect forever, you probably want to have it error out at some point.
