### ISSUE TITLE
Problem using ui-router to display services

### ISSUE THREAD

**Issue by RobinDesir** [don/cordova-plugin-ble-central#164]
Hello Don, 

I have take some of your code to experience with a BLE device the communication and to print out the services provided by the device. However, even if I can manage to connect to the device I have a problem concerning your code here: 

    .state('tab.ble', {
          url: '/ble',
          views: {
            'tab-ble': {
              templateUrl: 'templates/tab-ble.html',
              controller: 'BLECtrl'
            }
          }
        })
        .state('tab.ble-detail', {
          url: '/ble/:deviceId',
          views: {
            'tab-ble': {
              templateUrl: 'templates/ble-detail.html',
              controller: 'BLEDetailCtrl'
            }
          }
      })

when I try the same (and even if i compile and run your application) I can't manage to go to the state after having click on the device (in order to print the services linked to it).

I tried some other basic example to try to navigate and pass parameters using stateParams and I can't managed to get them work. 

Hereafter is a piece of code illustrating what i said : 

home.html 

<ion-nav-view></ion-nav-view>
<ion-view title="Home">	
	<ion-content class="padding">
		<h2 class='text-center'>Users</h2>
	
	<div class="card item item-text-wrap padding" ng-repeat="profil in profils"  ui-sref="app.test({name: profil.name })" >

	
		<p class="padding">
			{{ profil.name }}
		</p>
	</div>
	</ion-content>
</ion-view>

test.html

<ion-view view-title="{{name}}">
<ion-content class="padding">

	<h1> Hello {{ name }}</h1>

	<p class="padding">
		Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quia maxime quibusdam ullam dolore, non aliquam tempore cupiditate rerum culpa unde molestiae obcaecati ipsam. Explicabo aut, eligendi fugiat est rem similique!
	</p>

	</ion-content>
</ion-view>

app.js 

    .state('app',{
      url:'/app',
      abstract: true,
      templateUrl:'templates/menu.html',
    })

    .state('app.home', {
      url: '/home',
      views: {
        'menuContent':{
          templateUrl: 'templates/home.html',    
          controller: 'HomeCtrl'
        }
      }
    })

    .state('app.test',{
      url:"/home/:name",
      templateUrl:"templates/test.html",
      controller: function($scope, $stateParams) {
          // get the name
          $scope.name = $stateParams.name;
          alert($scope.name);
      } 
    })

The information printed in the home page come from HomeCtrl and it's only a list of name basically.

**Comment by don** [comment]
It sounds like you're having an Angular issue rather than a problem with the plugin.

I have an older [Ionic example app](https://github.com/don/ionic-ble) which might help you. It discovers peripherals and lists the services. If that doesn't work, StackOverflow is probably the best place to get Angular/Ionic help.

![ble50](https://cloud.githubusercontent.com/assets/3133/12595208/06126c82-c448-11e5-851d-99dab610a41e.png)
