### ISSUE TITLE
the plugin does not find the BT smartphone!

### ISSUE THREAD

**Issue by KinG-InFeT** [don/cordova-plugin-ble-central#166]
Hello,

I had already opened a ticket issue https://github.com/don/cordova-plugin-ble-central/issues/92 ,
Now, however, I learned that the plugin works by scanning the BT device, but my big problem, and that has no other smartphone! how can I do?

I tested the scanning with the same script with nexus 5, note 2, 2014 g bike.

can you help me?

thank you.

**Comment by don** [comment]
@KinG-InFeT you can use [bleno](https://github.com/sandeepmistry/bleno) on your computer to create a Bluetooth Low Energy devices for the phone to discover.
