### ISSUE TITLE
Getting subscribed notifications on iOS not working in background

### ISSUE THREAD

**Issue by tomasbedrich** [don/cordova-plugin-ble-central#169]
When the app is in background mode, the subscribed notifications will stop working after a while. It may be related to [UIBackgroundModes](https://developer.apple.com/library/ios/documentation/General/Reference/InfoPlistKeyReference/Articles/iPhoneOSKeys.html#//apple_ref/doc/plist/info/UIBackgroundModes) option in `Info.plist`, [which is required by Apple](https://developer.apple.com/library/ios/documentation/NetworkingInternetWeb/Conceptual/CoreBluetooth_concepts/CoreBluetoothBackgroundProcessingForIOSApps/PerformingTasksWhileYourAppIsInTheBackground.html).

The alternative `cordova-plugin-blootoothle` handles this [somewhere in the code](https://github.com/randdusing/cordova-plugin-bluetoothle/blob/4400f6e99aa67b3a2bd78d8e5c18101a7e3405a9/plugin.xml#L34) (not verified, if it's working).

**Comment by tomasbedrich** [comment]
I have tested the version with `UIBackgroundModes` option set to `bluetooth-central` and it seemed to work well.

**Comment by don** [comment]
I'm a bit concerned about having all apps set UIBackgroundModes. I'm not sure if this can be configurable or it would be better to do with the Cordova Custom Config plugin, https://www.npmjs.com/package/cordova-custom-config

**Comment by tomasbedrich** [comment]
Can you please describe why are you concerned about that?
