### ISSUE TITLE
android can not find other ble devices

### ISSUE THREAD

**Issue by dayukiller** [don/cordova-plugin-ble-central#173]
hi，i'm using the plugin to write a ble app;but when i use this plugin, i can not find the other devices(another android cellphone) through bluetooth;here is my code:

`onDeviceReady: function() {
        console.log('hello world');

        ble.scan([], 20, function(device) {
            console.log('success');
        }, function() {
            console.log('fail');
        });
    }`
it looks very simple; but i can not find the other devices(my android cellphone open the bluetooth already)
seek for help, 3q!

**Comment by don** [comment]
Are you sure the other devices near you are advertising Bluetooth LE serivces? Use another tool like [nRF Master Control Panel](https://play.google.com/store/apps/details?id=no.nordicsemi.android.mcp&hl=en) or [Light Blue](https://itunes.apple.com/us/app/lightblue-explorer-bluetooth/id557428110?mt=8) and ensure your phone can find devices. You should see similar results when scanning from Cordova.

**Comment by dayukiller** [comment]
I can not use this plugin to find my cellphone, but i can find my devices using bluetooth like my bluetooth scales. If i use the plugin uncorrectly to find my cellphones?Or it can only find the devices not cellphones?

**Comment by don** [comment]
@dayukiller the plugin will find phones *if* they are advertising Bluetooth LE services. You can use LightBlue Explorer to create virtual peripherals on iOS devices and nRF Master Control Panel to create virtual peripherals on newer Android devices.
