### ISSUE TITLE
Connect() with pincode

### ISSUE THREAD

**Issue by madstt** [don/cordova-plugin-ble-central#180]
I have a peripheral that requires a pincode to connect. Is this even possible? Is it on the roadmap?

**Comment by RangerMauve** [comment]
Currently, it seems that devices that require pairing should be paired through the native bluetooth UI, and then they can magically connect somehow. Try fiddling with that until @don responds.

**Comment by don** [comment]
Ideally the OS will prompt for a pin when connecting or when accessing a characteristic with permissions requiring additional encryption. (This might work better on iOS, but I'm pretty sure it works on Android too.)

**Comment by madstt** [comment]
Ok, thanks. I'll have to verify that options...

**Comment by hervethouzard** [comment]
Hello,

Has someone verified that it is automatically managed by the OS?
