### ISSUE TITLE
Connect without pin

### ISSUE THREAD

**Issue by JanMesaric** [don/cordova-plugin-ble-central#181]
Hi,

so I'm having trouble connecting with this one (always there's this one :D ) device that keeps asking me to pair devices via PIN (android handshake or whatever the proper term is). The thing is, that the peripheral device is not mobile phone or anything that I could enter a pin.

Is there any way to disable asking for this pin? Why is this even happening?

**Comment by don** [comment]
I think the best solution for a device like this is to use the phone's Bluetooth settings and bond with the device. Then disconnect. The next time you connect in the app you shouldn't be prompted for a PIN since you're already bonded.
