### ISSUE TITLE
Anybody having Connect issues on a Nexus 5 running 6.0.1?

### ISSUE THREAD

**Issue by mikecunneen** [don/cordova-plugin-ble-central#183]
I have no problems with my Samsung Galaxy S5 on 5.0 and iPhone but can't connect with a Nexus 5 on 6.0.1?

Thanks in advance,

Mike

**Comment by don** [comment]
@mikecunneen the plugin doesn't support android-23 yet, so the Bluetooth API calls are failing on your Nexus 5.

Edit your config.xml and set the target SDK to android-22 and it will start working again.

    <preference name="android-targetSdkVersion" value="22"/> 

The next release of the plugin should support Android 6.

**Comment by don** [comment]
Duplicate #182
