### ISSUE TITLE
ble.scan with service id not working with Nexus 5 Android 4.4.4

### ISSUE THREAD

**Issue by X-Y** [don/cordova-plugin-ble-central#184]
When using ble.scan without service id, it is capable of discovering my device. However when the id is provided, the function does not return the device. 

I tried the same code on LG G3 and Nexus 5, the former does not have this problem. I'm using a customized service code: 19B10000-E8F2-537E-4F6C-D104768A1214

**Comment by don** [comment]
Filtering by UUID doesn't work very well or consistently on Android 4.3 and 4.4. This is an Android issue, so there's not much the plugin can do.

For older versions of Android, scan for all devices and then manually filter the results in JavaScript.

**Comment by X-Y** [comment]
Thanks! This is very good to know
