### ISSUE TITLE
iOS write command stopped working with Cordova 6.0.0

### ISSUE THREAD

**Issue by Janckk** [don/cordova-plugin-ble-central#188]
Hi,

so everything was working fine until the newest update of cordova and xCode on iOS. Now I'm experiencing no errors but "write" fails silently as well I get no "notifications" from startNotification. Connects, scan and everything else works fine.

Did anyone experience this as well?

edit: I've also found this error message in the console:
[NSNull isEqualToString:]: unrecognized selector sent to instance 0x395ef588
tion:request:frame:decisionListener: delegate: <NSInvalidArgumentException> -[NSNull isEqualToString:]: unrecognized selector sent to instance 0x395ef588

might this be related to:
https://github.com/don/cordova-plugin-rfduino/issues/5 ?

**Comment by don** [comment]
It sounds like Cordova 6 iOS broke something. Maybe you can drop back to an older version for a bit?

I'll be working on a new BLE project next week, so a lot of these issues should get fixed soon.

**Comment by zabojad** [comment]
If we can't have Cordova 5 and Cordova 6 supported together, maybe we could have one branch of this repo for each?

**Comment by don** [comment]
@zabojad the plan is to support both. I just need to block off some time to duplicate and fix issues. Are you seeming this problem too?

**Comment by zabojad** [comment]
@don Not yet but I shall face it soon as I plan to upgrade few apps to Cordova 6.0...

**Comment by don** [comment]
@Janckk I can't duplicate this. I've been working on an app today with many writes and they're all working.

I'm running 
- cordova 6.0.0 
- cordova platform ios 4.0.1
- cordova-plugin-ble-central 1.0.4
- OS X 10.10.5
- Xcode Version 7.2.1 (7C1002) 

Can you ensure that the BLE plugin and cordova ios platform are up to date?
Can you provide a simple example that duplicates the problem?

**Comment by don** [comment]
Can't duplicate.

@Janckk if you're still seeing this, try updating your native project. If you have more info, post here and I'll reopen the issue.

**Comment by snowbreeze** [comment]
I am getting Writing is not permitted.
