### ISSUE TITLE
ble.stopNotification() on success  return issue 

### ISSUE THREAD

**Issue by cajay01** [don/cordova-plugin-ble-central#196]
In ble I used megster plugin in that ble.stopNotification() on success return it returns me an array buffer
but currently I updated the plugin to ble-central-plugin and for same call now it returns me "OK"
so is this plugin change?because in that array buffer I get some values that I am not getting now since it returns only OK .
What should I do to fix this issue?

**Comment by don** [comment]
It sounds like this is working as intended. [ble.stopNotification](https://github.com/don/cordova-plugin-ble-central#stopnotification) should return nothing (or perhaps OK) in the success callback to indicate that the notification has been removed. 

What data were you expecting in stopNotification?

**Comment by don** [comment]
[ble.stopNotification](https://github.com/don/cordova-plugin-ble-central#stopnotification) works as intended

Ignore any data passed to the success callback. Android will pass "OK", iOS will pass null. (This is the default Cordova behavior.)

https://github.com/don/ble-issue196
