### ISSUE TITLE
One write, multiple notifications

### ISSUE THREAD

**Issue by papasmurf17** [don/cordova-plugin-ble-central#197]
Hi, 
i'm using yours plugin, when I write a command my notification callback was called 2 times.
Will be always called 2 times my callback or the number is variable?
If the numbers of call is variable, how can I determinate when the response data, for a particular request (ble.write), is ended?

My last question is:
Is there some workaround to determinate if i've already subscribe a certain service?

Thanks :)

**Comment by don** [comment]
For `ble.write` only one callback should be called. Either the success or failure callback will be called.

For `ble.startNotification` the success callback can be called zero to an infinite number of times. The success callback is called whenever a ble notification arrives.

If you're seeing callbacks for `ble.write` called multiple times, please post some sample code to help track down the issue.
