### ISSUE TITLE
Android support for scan() and read()

### ISSUE THREAD

**Issue by cleancoderocker** [don/cordova-plugin-ble-central#199]
I'm developing a small application that scans for devices, connects to them and reads different characteristics. For this I use (among others) the `scan()` and the `read()` methods. The problem: they work when testing the application on an Android (5.1) phone using the PhoneGap Developer App (http://app.phonegap.com/). However when I deploy the application on the same Android phone calling one of the two methods results in an error "Invalid action". How can that be?

**Comment by don** [comment]
PhoneGap developer app includes this plugin.  

When your running your own app, you need to install the plugin into the project with `cordova plugin add cordova-plugin-ble-central`
