### ISSUE TITLE
Depreciated methods, posing issues in iOS8 +

### ISSUE THREAD

**Issue by georgeedwards** [don/cordova-plugin-ble-central#202]
I am getting the following warnings when building an app which references this plug-in in XCode.

> ~/platforms/ios/V2 Test/Plugins/cordova-plugin-ble-central/BLECentralPlugin/BLECentralPlugin.m:562:17: 'getBytes:' is deprecated: first deprecated in iOS 8.0 - This method is unsafe because it could potentially cause buffer overruns. Use -getBytes:length: instead.

and 

> ~/platforms/ios/V2 Test/Plugins/cordova-plugin-ble-central/BLECentralPlugin/CBPeripheral+Extensions.m:50:15: 'RSSI' is deprecated: first deprecated in iOS 8.0

**Comment by don** [comment]
Those deprecations will be fixed in future releases. For now you can just ignore the warnings.
