### ISSUE TITLE
Plugin not working Galaxy S6 Android 6.0.1 with edit in config.xml. 

### ISSUE THREAD

**Issue by Nico924** [don/cordova-plugin-ble-central#210]
I saw the previous issues related to this subject however, the addition of 

<preference name="android-targetSdkVersion" value="22"/>  

in my config.xml did not change anything. I have no error but when I use the scan or startScan function, I am not able to discover any device (however if I go in the bluetooth section of my phone, I can see the device I am trying to connect to)

Do y

**Comment by Kailash43** [comment]
@Nico924 have you found the solution for this issue?
