### ISSUE TITLE
ble not work after locked the screen on ios

### ISSUE THREAD

**Issue by wzhsh90** [don/cordova-plugin-ble-central#215]
I locked the screen when I scan the peripheral ,  the ble will stop to do anything . when I open the screen the ble will go on working  on stop point . How can we make it works on  background mode.

**Comment by wzhsh90** [comment]
I find the solution.
edit project xxx-info.plist, add row  Required background modes 
and add subitems App shares data using CoreBluetooth  && App communicates using CoreBluetooth 
under Required background modes.

it works for me.

**Comment by don** [comment]
@wzhsh90 I'll be looking at background scanning soon.

**Comment by don** [comment]
Duplicate of #169 

See https://github.com/don/cordova-plugin-ble-central/blob/master/README.md#background-notifications-on-ios

**Comment by wzhsh90** [comment]
ok , i will use it soon.thank you.
