### ISSUE TITLE
ipad ios 7 scan error 

### ISSUE THREAD

**Issue by dennis-b** [don/cordova-plugin-ble-central#216]
Hi Don,
Our project connecting to custom device and communicating over BLE. 
It works fine on ios 8 and grater, on ios 7 we get this error:

startScan
[CBUUID UUIDString]: unrecognized selector sent to instance 0x17822f3e0
Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[CBUUID UUIDString]: unrecognized selector sent to instance 0x17822f3e0'
*** First throw call stack:
(0x185c4f09c 0x191f85d78 0x185c53d14 0x185c51a7c 0x185b714ac 0x1000fcedc 0x1000fc9e4 0x1000f8e20 0x18590e818 0x18590ee20 0x185917e38 0x192554420 0x1925543e0 0x19255756c 0x185c0ed64 0x185c0d0a4 0x185b4db38 0x18b51f830 0x188b8c0e8 0x1000f5cd8 0x19256faa0)
libc++abi.dylib: terminating with uncaught exception of type NSException

in xcode it stops at:

` // Create a new list of Service UUIDs as Strings instead of CBUUIDs
NSMutableArray *serviceUUIDs = [dict objectForKey:CBAdvertisementDataServiceUUIDsKey];
NSMutableArray *serviceUUIDStrings;
if (serviceUUIDs) {
    serviceUUIDStrings = [[NSMutableArray alloc] initWithCapacity:serviceUUIDs.count];

    for (CBUUID *uuid in serviceUUIDs) {
       **[serviceUUIDStrings addObject:[uuid UUIDString]];**
    }

    // replace the UUID list with list of strings
    [dict removeObjectForKey:CBAdvertisementDataServiceUUIDsKey];
    [dict setObject:serviceUUIDStrings forKey:CBAdvertisementDataServiceUUIDsKey];

}`

System information:
-----------------------------
Cordova CLI: 6.1.1
Ionic CLI Version: 1.7.14
Ionic App Lib Version: 0.7.0
ios-deploy version: 1.8.5 
ios-sim version: 5.0.8 
OS: Mac OS X El Capitan
Node Version: v5.5.0
Xcode version: Xcode 7.2.1 Build version 7C1002 

Thanks and regards,
Dennis.

**Comment by don** [comment]
@dennis-b I think you'll need to use an older version of the plugin for iOS7. If you really need iOS7 support in the latest version, reach out via email and we can discuss.
