### ISSUE TITLE
Can anyone help with the ble is not defined error? Thanks in advance.

### ISSUE THREAD

**Issue by Montanajim** [don/cordova-plugin-ble-central#220]

**Comment by don** [comment]
"ble not defined" usually means the plugin isn't installed correctly. Did you install with the cordova command?

    cordova plugin add cordova-plugin-ble-central

What versions of cordova are you running? Are you seeing this on iOS or Android?

**Comment by Montanajim** [comment]
Made  a novice mistake, forgot that the failure callback was optional.  All newbies,  if you are testing, delete the failure parameter or write the function in the scan.  Thanks!
