### ISSUE TITLE
Question: Is the delay between BLE transactions configurable?

### ISSUE THREAD

**Issue by FriendFX** [don/cordova-plugin-ble-central#222]
We are using our app on both Android and iOS and noticed that iOS seems to show a significantly shorter turnaround time for BLE transactions than Android. Unless Android is slower or iOS is faster than the BLE spec, I don't see any reason for this difference.

The devices we're using for our tests are running Android 4.4.4 and iOS 9.3.1.

Is there a parameter anywhere in the cordova-plugin-ble-central plugin that I could tweak to have shorter transaction-to-transaction delay, or is this timing dictated entirely by the BLE stack of the device's operating system?

**Comment by don** [comment]
This behavior is based on the operating system BLE stack. iOS is usually much faster than Android, especially iOS 9. 

Android 4..3 and 4.4 are usually crappy, I get much better results with newer hardware running Android 6. Not as fast as iOS, but much better.
