### ISSUE TITLE
ble.startScanWithOptions() description and functionality issues

### ISSUE THREAD

**Issue by valterforesto** [don/cordova-plugin-ble-central#228]
I think that "ble.startScanWithOptions()" at #startscanwithoptions must replace "ble.startScan()".
I also tested it's function on Samsung S4 with Android 5.0.1 using PhoneGap and seem not working properly. Someone has experienced the same problems?

**Comment by don** [comment]
@valterforesto `startScanWithOptions` does not replace `startScan`

You'll only see startScanWithOptions if you're running from master, that version hasn't been released to npm yet.

**Comment by don** [comment]
Version 1.1.0 has been released to NPM and contains the new startScanWithOptions functions.
