### ISSUE TITLE
PhoneGap Build

### ISSUE THREAD

**Issue by JohnHigbie** [don/cordova-plugin-ble-central#23]
Hi Don, looks like you've been busy!
Will you be submitting this to PhoneGap Build?
-John

**Comment by don** [comment]
This plugin is on PGB https://build.phonegap.com/plugins/1305 but you can also use it directly from plugins.cordova.io now http://phonegap.com/blog/2014/12/09/phonegap-build-new-features/

**Comment by JohnHigbie** [comment]
Great. I'll be checking it out!

Best,
John
