### ISSUE TITLE
Scanning for multiple services

### ISSUE THREAD

**Issue by dested** [don/cordova-plugin-ble-central#230]
When I call ble.startScan with multiple services I never get an onFoundDevice callback. If I call with either individually, it works flawlessly. Is this a limitation of the framework/ble adapter?

ble.startScan(['FFF0', 'FFF1'], onFoundDevice, onLostDevice)

I am testing this on an Android Nexus 5 with 6.0.1

**Comment by dested** [comment]
Ah! Thank you for the reply.

Does start scan support running two concurrent scans?

**Comment by don** [comment]
I think you need to run them serially.

**Comment by dested** [comment]
Thank for the information!
