### ISSUE TITLE
startNotification "BluetoothGatt is null" error on Android 6.0

### ISSUE THREAD

**Issue by artman186** [don/cordova-plugin-ble-central#233]
I have a device (Motorola XT1585, Droid Turbo 2) that was recently updated to Android 6.0 from Android 5.0.  On this device I'm able to make a connection to a BLE device (a scale, in this case) but when I call "startNotification" the device immediately disconnects and then invokes the startNotification failure callback with the message "BluetoothGatt is null".  The exact same code is working fine on a Asus K01A running Android 5.0.  I was previously running version 0.1.3 of the plugin, I upgraded to 1.0.6 and am experiencing the same issue.

**Comment by don** [comment]
Can you run `adb logcat` and see if there is a stack trace?

**Comment by artman186** [comment]
The Android logs don't indicate any errors, but I do have the adb output from the device while this was happening.  I've sent what I have via e-mail, let me know what else I can provide.

**Comment by don** [comment]
@artman186 you probably need to upgrade to the latest version of the plugin with new Android-6 permission support. You need at least version 1.0.5, but I recommend using the latest.

    cordova plugin rm cordova-plugin-ble-central
    cordova plugin add cordova-plugin-ble-central

**Comment by artman186** [comment]
We are using this plugin through the verified Telerik plugins marketplace, and although their versioning scheme is a little goofy, according to them we are using version "1.1.0.2", although the only versions they show are 0.1.3 and 1.1.0.2 depending on which part of the tool you are in.

Regardless, I just re-tested this issue on Android 6.0 using Telerik's "1.1.0.2" version of the plugin and everything worked correctly, so I will mark this closed.

**Comment by don** [comment]
@artman186 Is the Telerik v1.1.0.2 different from my 1.1.0? Any way you can test with my version?
