### ISSUE TITLE
Fails to build for Android in Phonegap Build

### ISSUE THREAD

**Issue by ibcomputing** [don/cordova-plugin-ble-central#236]
When referencing the plugin in config.xml as such:
`<gap:plugin name="cordova-plugin-ble-central" source="npm" />`

I get the following build error for the Android platform: 
Error - Some official plugins have to be updated if using PhoneGap >= 4.0.0. Please upgrade the version of any plugins that may include the following file: Peripheral.java

I tried changing the phonegap version to 3.7.0 and 3.4.0 but oddly still got exactly the same error message.

Seems to be an issue with line 71 of peripheral.java:
`gatt = device.connectGatt(activity, false, this, BluetoothDevice.TRANSPORT_LE);`

**Comment by don** [comment]
Add this to config.xml (thanks to @valterforesto)

    <preference name="phonegap-version" value="cli-6.1.0" />
