### ISSUE TITLE
startStateNotifications why not support state 'unsupported' on android

### ISSUE THREAD

**Issue by wzhsh90** [don/cordova-plugin-ble-central#238]
Hi:

  on ios CBCentralManager support CBCentralManagerStateUnsupported state,so we can easy get this state,but on android if we need to check the mobile whether support 'ble' we need to make another method to check, i suggest startStateNotifications also support  'unsupported' state on android.

**Comment by don** [comment]
That's a good idea. Can you create a pull request?
