### ISSUE TITLE
iOS > Duplicate peripherals on both scan and startScan

### ISSUE THREAD

**Issue by lauleehong** [don/cordova-plugin-ble-central#239]
I'm getting a list of duplicate peripherals with both scan and startScan, specifically on iOS only. I'm get the same results from using the stock codes. Is there a faster way than storing each UUID in an array and comparing the current one with the array before displaying?

**Comment by don** [comment]
I usually have a dictionary of device ids in javascript and filter for duplicates before displaying. It's possible some filtering could be done in the native code. iOS isn't supposed to return duplicates, but I sometimes see multiple results when the RSSI is changing.
