### ISSUE TITLE
heart-rate for ionic

### ISSUE THREAD

**Issue by Rishi99es** [don/cordova-plugin-ble-central#240]
You have written an application in ionic for ble scan.
I have tried merging your HRM-phonegap code with the ionic framework, however, did not succeed.
Can you help me with some pointers, that can help me get the HRM going in ionic?

For starters,
I would like to know how to use the index.js file in the various app.js, controllers.js and services.js files of ionic.

Thank you

**Comment by don** [comment]
@Rishi99es Take a look at this Ionic example https://github.com/don/ionic-ble
