### ISSUE TITLE
How to broadcast an information?

### ISSUE THREAD

**Issue by lettierimarco** [don/cordova-plugin-ble-central#241]
It is possible to advertise an information with this plugin?
I need to broadcast an information on ble, like nearby android/ios does

**Comment by don** [comment]
No, this plugin only supports the Bluetooth Central role. I recently started working on another plugin, [cordova-plugin-ble-peripheral](https://github.com/don/cordova-plugin-ble-peripheral), for creating Bluetooth LE services using Cordova.

**Comment by lettierimarco** [comment]
it works only for ios... :(

**Comment by don** [comment]
The android version isn't complete yet. Will be at some point.
