### ISSUE TITLE
Plugin only works with the GPS location on

### ISSUE THREAD

**Issue by victorazevedo** [don/cordova-plugin-ble-central#242]
I have to turn the Bluetooth and GPS on to this plugin work. If I turn only the bluetooth the scan results in a empty array :[]

How can I remove this dependency to the GPS?

**Comment by smuser90** [comment]
If the platform you are testing this on is Android then that is expected. The OS requires location services to be on to use BLE. Bluetooth classic does not have this requirenent.

**Comment by don** [comment]
Unfortunately like @smuser90 said, Android requires the location permission (android.permission.ACCESS_COARSE_LOCATION) when doing a Bluetooth Low Energy scan.
