### ISSUE TITLE
android 6.0 cannot find any devices

### ISSUE THREAD

**Issue by qppq54s** [don/cordova-plugin-ble-central#248]
hi
My devices update to android 6.0 this days,and when i startScan there are no devices callback.
It worked fine before
Can you help me about this,thanks

**Comment by don** [comment]
Ensure you're using the lastest version of the plugin that has support for Android 6 permissions.

**Comment by qppq54s** [comment]
thanks for the reply!
I checked the version and It's 1.1.0.
But when i open the 'Open Bluetooth debug log' and 'Open Bluetooth packet log' options in developer options, it works fine. 
Then i close these options, it works fine and never show the problem i met before;
Could you figure out the reason

**Comment by qppq54s** [comment]
thanks for the reply!
I checked the version and It's 1.1.0.
My phone is nexus 5X, android 6.0.1 and i can find my bluetooth devices in my system bluetooth setting,but it never gives me a callback when using the plugin;
I have another device MI4 ,android 6.0.1, the plugin works fine
Could you figure out the reason

**Comment by djlitvak** [comment]
I was having this problem with my Nexus 6p. We were using 1.0.4. I just updated to 1.1.0 and have now been unable to reproduce - I will continue testing.

The strange thing was that on 1.0.4, I was able to find devices if I toggled my Bluetooth off/on through the phone settings.
