### ISSUE TITLE
BLE Connect on Samsung Galaxy S5

### ISSUE THREAD

**Issue by tl8roy** [don/cordova-plugin-ble-central#25]
I am trying to connect to a BLE module (OLP 421) using my Samsung Galaxy S5.
While it can discover it, it is not able connect to it. It doesn't fail but doesn't call the success callback.

A bit of research has suggested this could be the issue: http://stackoverflow.com/questions/20839018/while-connecting-to-ble113-from-android-4-3-is-logging-client-registered-waiti

I am not skilled enough to work out if this is the issue so some help or suggestions are appreciated.

Here is the log file:
```
    12-02 12:07:09.683: D/BLEPlugin(20745): action = isEnabled
    12-02 12:07:09.683: D/BLEPlugin(20745): action = scan
    12-02 12:07:09.683: D/BluetoothAdapter(20745): startLeScan(): [Ljava.util.UUID;@42b02068
    12-02 12:07:09.973: D/BluetoothAdapter(20745): onClientRegistered() - status=0 clientIf=7
    12-02 12:07:09.983: W/PluginManager(20745): THREAD WARNING: exec() call to BLE.scan blocked the main thread for 295ms. Plugin should use CordovaInterface.getThreadPool().
    12-02 12:07:10.303: D/BluetoothAdapter(20745): onScanResult() - Device=00:12:F3:23:96:F7 RSSI=-53
    12-02 12:07:10.333: D/CordovaLog(20745): file:///android_asset/www/js/bluetooth.js: Line 20 : {"advertising":{},"id":"00:12:F3:23:96:F7","rssi":-53,"name":"Bluetooth Device"}
    12-02 12:07:10.333: I/chromium(20745): [INFO:CONSOLE(20)] "{"advertising":{},"id":"00:12:F3:23:96:F7","rssi":-53,"name":"Bluetooth Device"}", source: file:///android_asset/www/js/bluetooth.js (20)
    12-02 12:07:10.353: D/BLEPlugin(20745): action = connect
    12-02 12:07:10.363: D/BluetoothGatt(20745): connect() - device: 00:12:F3:23:96:F7, auto: false
    12-02 12:07:10.363: D/BluetoothGatt(20745): registerApp()
    12-02 12:07:10.363: D/BluetoothGatt(20745): registerApp() - UUID=28406036-b3d2-4efd-9f50-062e298c6a63
    12-02 12:07:10.363: I/BluetoothGatt(20745): Client registered, waiting for callback
    12-02 12:07:10.373: D/BluetoothGatt(20745): onClientRegistered() - status=0 clientIf=8
    12-02 12:07:11.313: D/BluetoothAdapter(20745): onScanResult() - Device=00:12:F3:23:96:F7 RSSI=-53
    12-02 12:07:13.333: D/BluetoothAdapter(20745): onScanResult() - Device=00:12:F3:23:96:F7 RSSI=-56
    12-02 12:07:14.333: D/BluetoothAdapter(20745): onScanResult() - Device=00:12:F3:23:96:F7 RSSI=-55
    12-02 12:07:15.333: D/BluetoothAdapter(20745): onScanResult() - Device=00:12:F3:23:96:F7 RSSI=-53
    12-02 12:07:16.333: D/BluetoothAdapter(20745): onScanResult() - Device=00:12:F3:23:96:F7 RSSI=-54
    12-02 12:07:17.333: D/BluetoothAdapter(20745): onScanResult() - Device=00:12:F3:23:96:F7 RSSI=-53
    12-02 12:07:17.383: E/ViewRootImpl(20745): sendUserActionEvent() mView == null
    12-02 12:07:18.343: D/BluetoothAdapter(20745): onScanResult() - Device=00:12:F3:23:96:F7 RSSI=-53
    12-02 12:07:20.353: D/BluetoothAdapter(20745): onScanResult() - Device=00:12:F3:23:96:F7 RSSI=-54
    12-02 12:07:21.343: D/BluetoothAdapter(20745): onScanResult() - Device=00:12:F3:23:96:F7 RSSI=-54
    12-02 12:07:22.353: D/BluetoothAdapter(20745): onScanResult() - Device=00:12:F3:23:96:F7 RSSI=-53
    12-02 12:07:25.373: D/BluetoothAdapter(20745): onScanResult() - Device=00:12:F3:23:96:F7 RSSI=-54
    12-02 12:07:26.363: D/BluetoothAdapter(20745): onScanResult() - Device=00:12:F3:23:96:F7 RSSI=-51
    12-02 12:07:27.383: D/BluetoothAdapter(20745): onScanResult() - Device=00:12:F3:23:96:F7 RSSI=-53
    12-02 12:07:29.393: D/BluetoothAdapter(20745): onScanResult() - Device=00:12:F3:23:96:F7 RSSI=-55
    12-02 12:07:30.403: D/BluetoothAdapter(20745): onScanResult() - Device=00:12:F3:23:96:F7 RSSI=-54
    12-02 12:07:31.393: D/BluetoothAdapter(20745): onScanResult() - Device=00:12:F3:23:96:F7 RSSI=-53
    12-02 12:07:32.403: D/BluetoothAdapter(20745): onScanResult() - Device=00:12:F3:23:96:F7 RSSI=-53
    12-02 12:07:33.423: D/BluetoothAdapter(20745): onScanResult() - Device=00:12:F3:23:96:F7 RSSI=-53
    12-02 12:07:34.413: D/BluetoothAdapter(20745): onScanResult() - Device=00:12:F3:23:96:F7 RSSI=-54
    12-02 12:07:35.423: D/BluetoothAdapter(20745): onScanResult() - Device=00:12:F3:23:96:F7 RSSI=-52
    12-02 12:07:39.433: D/BluetoothAdapter(20745): onScanResult() - Device=00:12:F3:23:96:F7 RSSI=-51
    12-02 12:07:40.003: D/BLEPlugin(20745): Stopping Scan
    12-02 12:07:40.003: D/BluetoothAdapter(20745): stopLeScan()
```

**Comment by diesel1** [comment]
Hi I cant help with your problem but can you help Me .I have also got a Samsung s5 and a Bluno but I cant connect to that .I have the same problem as you.The connect led lights but I cant pair the two .
Can you help at all . 
Thanks

**Comment by don** [comment]
OBS421 needs to be configured for BLE.
From a default OBS421 the following need to be set:
AT*AGLE=2,1 (BLE enable)
AT*ADDSP=14,1 (LE Serial Port Service enable)

**Comment by DheerubhaiBansal** [comment]
I am getting this logs continously in SAMSUNG deice kitkat and lolipop also.

D/BluetoothAdapter: onScanResult() - Device=6A:40:8C:39:DF:DD RSSI=-92
D/BluetoothAdapter: onScanResult() - Device=6A:40:8C:39:DF:DD RSSI=-86
D/BluetoothAdapter: onScanResult() - Device=00:07:80:C7:BD:16 RSSI=-61
D/BluetoothAdapter: onScanResult() - Device=6A:40:8C:39:DF:DD RSSI=-88
D/BluetoothAdapter: onScanResult() - Device=C2:0C:78:26:03:B2 RSSI=-90
D/BluetoothAdapter: onScanResult() - Device=00:07:80:C7:BD:16 RSSI=-61
D/BluetoothAdapter: onScanResult() - Device=6A:40:8C:39:DF:DD RSSI=-88 
D/BluetoothAdapter: onScanResult() - Device=6A:40:8C:39:DF:DD RSSI=-92
D/BluetoothAdapter: onScanResult() - Device=6A:40:8C:39:DF:DD RSSI=-86
D/BluetoothAdapter: onScanResult() - Device=6A:40:8C:39:DF:DD RSSI=-92
D/BluetoothAdapter: onScanResult() - Device=6A:40:8C:39:DF:DD RSSI=-86
D/BluetoothAdapter: onScanResult() - Device=00:07:80:C7:BD:16 RSSI=-61
D/BluetoothAdapter: onScanResult() - Device=6A:40:8C:39:DF:DD RSSI=-88
D/BluetoothAdapter: onScanResult() - Device=C2:0C:78:26:03:B2 RSSI=-90
D/BluetoothAdapter: onScanResult() - Device=00:07:80:C7:BD:16 RSSI=-61
D/BluetoothAdapter: onScanResult() - Device=6A:40:8C:39:DF:DD RSSI=-88 
D/BluetoothAdapter: onScanResult() - Device=00:07:80:C7:BD:16 RSSI=-61
D/BluetoothAdapter: onScanResult() - Device=6A:40:8C:39:DF:DD RSSI=-88
D/BluetoothAdapter: onScanResult() - Device=C2:0C:78:26:03:B2 RSSI=-90
D/BluetoothAdapter: onScanResult() - Device=00:07:80:C7:BD:16 RSSI=-61
D/BluetoothAdapter: onScanResult() - Device=6A:40:8C:39:DF:DD RSSI=-88 

Around 1 minute within this period I am unable to connect.
