### ISSUE TITLE
Add example project connecting to multiple devices

### ISSUE THREAD

**Issue by don** [don/cordova-plugin-ble-central#26]
Add example project connecting to multiple devices

**Comment by lucalenardi** [comment]
Hello Don and thanks for the hard work!

That would be really useful, is there an example available where you would start from? Do you have any particular recommendation for implementing multi-device connection? We can eventually work on this task with your support.

Looking forward to your comment!

**Comment by don** [comment]
@lucalenardi Unfortunately I don't have an example to post, but you can easily connect to multiple devices at the same time. Your application is responsible for managing the connected device ids which need to be passed in with each call.

When you're connected to multiple devices, sometimes its difficult to tell which device disconnected. For now I solve this by wrapping the disconnect function in another function.

    var createDisconnectFunction = function(id) {
      // return a new function that knows the device id
      return function(reason) {
        console.log("Disconnected from " + id + ".");
      }
    }

Then when connecting

    ble.connect(id, onConnect, createDisconnectFunction(id));
