### ISSUE TITLE
0x1800 service (Device Name) not accesible in iOS but accesible in Android

### ISSUE THREAD

**Issue by hiniesta** [don/cordova-plugin-ble-central#260]
When trying to access the generic Device Name service to change it (0x1800) in iOS get the error "Could not find service with UUID 1800 on peripheral" while the service works perfect in Android. The service is not listed when periperhal is discovered 

Updated: Soved, in iOS is not possible

**Comment by don** [comment]
Write is optional for Device Name characteristic 0x2a00 on the GAP service 0x1800.

https://developer.bluetooth.org/gatt/services/Pages/ServiceViewer.aspx?u=org.bluetooth.service.generic_access.xml

Unfortunately as you found iOS doesn't allow access to the GAP service.
