### ISSUE TITLE
Devices only detected once

### ISSUE THREAD

**Issue by BioPhoton** [don/cordova-plugin-ble-central#267]
I recieve all near devices. 
Also all values.

But for some reason the plugin shows just the data from the first detection. 
So every device gets console.loged only once in my code. No subsequent updates...

Is this a propper behaviour?

**Comment by don** [comment]
That's the expected behavior.

If you want duplicates try https://github.com/don/cordova-plugin-ble-central#startscanwithoptions

**Comment by BioPhoton** [comment]
Thx!! Found it myselfe now and wanted to close thsi issue.. :-)
