### ISSUE TITLE
Getting Blood Pressure Measurement (Service: 1810)

### ISSUE THREAD

**Issue by saenzramiro** [don/cordova-plugin-ble-central#27]
Hi everybody,

I'm trying to get the BPM values from "A&D" device (model [UA-651BLE] (http://www.wellnessconnected.com/wp-content/uploads/2014/08/UA_651BLE_datasheet.pdf)).

The service to get that data is [1810] (https://developer.bluetooth.org/gatt/services/Pages/ServiceViewer.aspx?u=org.bluetooth.service.blood_pressure.xml) and the characteristic is [2A35] (https://developer.bluetooth.org/gatt/characteristics/Pages/CharacteristicViewer.aspx?u=org.bluetooth.characteristic.blood_pressure_measurement.xml). I used the battery example as a base to get this values, but I don't know why is always failed (print "Read failed"). I tried to get this data in pair mode (holding the power button until shows "Pr" in the display) or immediately after getting my BPM. 

My code (after scanning and connecting):
```javascript
var onReadSuccess = function(data) {
	var a = new Uint8Array(data);
	console.log('onReadSuccess', data, a);
}
				
var onReadFail = function(error) {
	console.log('onReadFail', error);
}
						
ble.read('7C:66:9D:88:B2:B8', '1810', '2a35', onReadSuccess, onReadFail);
```

I saw other apps that they could get this data from my device, but I think they do it natively.

Can anyone helps me?

Thanks.

**Comment by don** [comment]
According to the [specs](https://developer.bluetooth.org/gatt/services/Pages/ServiceViewer.aspx?u=org.bluetooth.service.blood_pressure.xml), blood pressure only uses **indicate** you can't **read** it..

Indicate has not implemented in the plugin yet. If you add support for indicate this please submit a pull request.

As for the short vs long uuids, the plugin will translate 16-bit UUIDs into their 2a35 128-bit form internally for Android. You should use the short UUIDs.

**Comment by don** [comment]
@saenzramiro On iOS is looks like notifications and indications are handled the same from an API perspective so you should be able to use startNotification to receive a callback when 2a35 changes on 1810. Depending on the Android behavior, I'll probably add a startIndication() method to both iOS and Android in a future version of the plugin.

https://developer.apple.com/library/ios/documentation/CoreBluetooth/Reference/CBPeripheral_Class/#//apple_ref/occ/instm/CBPeripheral/setNotifyValue:forCharacteristic:

**Comment by don** [comment]
[startNotification](https://github.com/don/cordova-plugin-ble-central#startnotification) now supports notification and indication on both iOS and Android

    var onData = function(buffer) {
        var data = new Uint16Array(buffer);
        console.log(data[0]);
    }

    ble.startNotification(deviceId, '1810', '2a35', onData, failure)

**Comment by daniperezluna** [comment]
@saenzramiro Could you send me your code?? I am triying to do something like this. Thanks.

**Comment by GeneLiulumira** [comment]
I get the MAC address of the peripheral (A&D_UA-651BLE_xxFxxxx).
I get the SN (514xxxxxxx)
I get the service_uuid (233BF000-5A34-1B6D-975C-xxxxxxxxxxxx).
I get the the characteristic_uuid(233BF001-5A34-1B6D-975C-xxxxxxxxxxxx)
But I cannot get the blood pressure data because the characteristic.value is empty.
Here is the print out for this characteristic
<CBCharacteristic: 0x16da3da0, UUID = 233BF001-5A34-1B6D-975C-xxxxxxxxxxxx, properties = 0xA, value = <>, notifying = NO>
Could anyone help me here?
Thanks a lot

**Comment by ftaibi** [comment]
@don Hi there I have the same problem, I am using the startNotification method and I get this:

ERROR: Attempt to invoke virtual method 'java.util.List android.bluetooth.BluetoothGattService.getCharacteristics()' on a null object reference

I am using the service 1810 and the characteristic 2a35
