### ISSUE TITLE
BLE plugin is not installed

### ISSUE THREAD

**Issue by twinsit** [don/cordova-plugin-ble-central#272]
Till yesterday my bluetooth app worked great on Android and iOs. Now when I do a startScan I get this error:

3     231914   warn     Native: tried calling BLE.startScan, but the BLE plugin is not installed.
4     231917   warn     Install the BLE plugin: 'ionic plugin add cordova-plugin-ble-central'
6     231933   error    [object Object]
5     231928   warn     Unable to clear the previous observable watch for, BLE, startScan

Is there a good solution to fix this? Thanks

**Comment by don** [comment]
It's possible the generated native project or plugins directory got deleted.

Did you try `ionic plugin add cordova-plugin-ble-central`?

Note that plugin's JavaScript object is named `ble` rather then `BLE`.

**Comment by twinsit** [comment]
Sorry for late reply. I was able to fix it by creating a new project and copying everything inside.
