### ISSUE TITLE
Unable to access battery service data from battery  service created for advertisement simulation in nrf master control panel. 

### ISSUE THREAD

**Issue by rajxi** [don/cordova-plugin-ble-central#275]
Battery service 0x180f service is created with service data in hex from nrf master control panel.
But when using the example battery app to check the simulated ble battery device getting
ERROR:attempt to invoke virtual method 'java.util.List android.bluetooth.BluetoothGattService.getCharacteristics() on a null object reference

**Comment by don** [comment]
Please export your service definition from nRF Master Control Panel and include here with any instructions on how to recreate. 

Include the full stack trace from `adb logcat` So I know what line the error happened on.
