### ISSUE TITLE
ble.write() not working on Android

### ISSUE THREAD

**Issue by GianlucaCesari** [don/cordova-plugin-ble-central#282]
Hi there @don ,
I've been trying to use your plugin in my app, and is working fine on iOs, the only thing is when I try to write on a characteristic on the method ble.write(), the first parameter (device.id) doesn't work in android (even if the mac address is the right one). Tell me if you need more information or if is just something I've been doing wrong.

**Comment by don** [comment]
Do you have an error message? Are you using the MAC address you got from the ble.scan()?

**Comment by GianlucaCesari** [comment]
Yes, I'm using the MAC address coming from ble.connect(),  the error message is the general error which I console.logged in the error function. The error says "Write failed."

**Comment by don** [comment]
The exact same code works on iOS with the same peripheral?

What hardware and what version of Android? What version of this plugin?

Use chrome://inspect to see if there are JavaScript errors (requires Android 5+) 

Run 'adb logcat' and see if there's an error message in the log. 

It's possible you have some JavaScript that works on iOS and fails on Android.

**Comment by GianlucaCesari** [comment]
Yes, it works on iOS with the same peripheral(an arduino 101), I'm using a samsung for android (I believe it's a galaxy s5 with the latest update(I will check tomorrow morning)). I've already checked for js errors but there are no errors. I will try 'adb logcat' first thing tomorrow morning and I will report here the results.

**Comment by GianlucaCesari** [comment]
<img width="521" alt="schermata 2016-07-21 alle 10 11 42" src="https://cloud.githubusercontent.com/assets/13241843/17016116/cd0af60e-4f2d-11e6-9c42-d70ee6ed3770.png">
<img width="1257" alt="schermata 2016-07-21 alle 10 19 36" src="https://cloud.githubusercontent.com/assets/13241843/17016115/cd0a5604-4f2d-11e6-848e-29d05e115c0d.png">
<img width="599" alt="schermata 2016-07-21 alle 10 20 59" src="https://cloud.githubusercontent.com/assets/13241843/17016117/cd1267cc-4f2d-11e6-9aaa-af014604cdc2.png">
So this is the code, hope it can help, the android device is a S5 with Android 5.0 onboard

**Comment by don** [comment]
'chars[0].service' is the problem. On Android, you're writing to the wrong characteristic. Android returns the Generic Access Service 0x1800 and the Generic Attribute Service 0x1801 in addition to your custom service. (iOS hides the 0x1800 and 0x1801 services)

I recommend explicitly stating the service and characteristic UUID in your Cordova code.

**Comment by GianlucaCesari** [comment]
Oh, that was the problem, thank you very much for your help!

**Comment by jsanchez1993** [comment]
I Dom, I have the same problem but your answer is not correct for my. 
this sis my error: Characteristic 00001801-0000-1000-8000-00805f9b34fb not found.
`
var data = new Uint8Array(1);
		data[0] = 97;
		ble.write(app.device_id, '1800', '1801', data.buffer, function (success) {
			console.log('success: ');
			console.log(success);
		}, function (failure) {
			console.log('error: ');
			console.log(failure);
		});`
