### ISSUE TITLE
Try to get battery level, but unable to connect ble device 

### ISSUE THREAD

**Issue by testaccnt0435** [don/cordova-plugin-ble-central#286]
When i run my app in device, its returns "Peripheral deviceid not found" only.

    onConnect = function() {
        alert('onconnect start');
        // TODO check if we have the battery service
        // TODO check if the battery service can notify us
        //ble.startNotification(deviceId, battery.service,battery.level, app.onBatteryLevelChange, app.onError);
        batteryStateButton.dataset.deviceId = deviceId;
        disconnectButton.dataset.deviceId = deviceId;
        app.showDetailPage();
        alert('onconnect end');
    };    
    ble.connect(deviceId, onConnect, app.onError);

When i use above code, didn't get 'onconnect start' alert. I have check plugin code

    connect: function (device_id, success, failure) {
        alert(device_id);
        var successWrapper = function(peripheral) {
            alert('successWrapper');
            convertToNativeJS(peripheral);
            success(peripheral);
        };
        cordova.exec(successWrapper, failure, 'BLE', 'connect', [device_id]);
    },

From this plugin get device id alert only, not 'successWrapper' alert. Also i tried to pair from my mobile to device, get some error "Unable to communicate with deviceid".

**Comment by don** [comment]
Based on the error, you're not connecting to the device, so the connect success callback is never called.

Make sure you scanning for BLE peripherals before attempting to connect. Use the peripheral.id from the scan results.
