### ISSUE TITLE
Unable to communicate with device

### ISSUE THREAD

**Issue by rrpatil761** [don/cordova-plugin-ble-central#298]
When i tried to connect to BLE device which requires pairing and on setting correct pair code, the device gets connected for few seconds only and then get disconnected automatically and shows a toast message "Unable to communicate with device_name".

**Comment by don** [comment]
Pairing devices has been problematic for some people. Once you've bonded with the device, you shouldn't need to do this again. If bonding fails from the app, try pairing from the Android Bluetooth screen. Then run the app again and it should work.

Unfortunately these tend to be device specific problems which I can't track down without the hardware.
