### ISSUE TITLE
BLE device authentication always fails.

### ISSUE THREAD

**Issue by rrpatil761** [don/cordova-plugin-ble-central#300]
I am facing problem with device authentication. following is the code.

```
$scope.authenticate = function (peripheral) {
        var characteristics = peripheral.characteristics;
        var SERVICEUUID = characteristics[5].service;
        var DATAUUID = characteristics[5].characteristic;
        var data = new Uint8Array(1);
        data[0] = "6Bh"; 
        ble.write(peripheral.id, SERVICEUUID, DATAUUID,  data.buffer, authsuccess, authfail);
    }
```

"6Bh" This command is used to access the extended features of the reader. I didn't understand what is going wrong here? Can you please help!

**Comment by don** [comment]
6Bh probably means the number 0x6b rather than the string 6Bh. Try putting a number into the array.

    data[0] = 0x6b;

For device usage issues like this, it would be better to post on StackOverflow.
