### ISSUE TITLE
[Question] IOS / MBP scan issue

### ISSUE THREAD

**Issue by tchauviere** [don/cordova-plugin-ble-central#301]
Hi,

I'm currently trying to scan for my MBP Bluetooth from my PhoneGap app with your plugin, but it seems that I have nothing that shows up during scan. My bluetooth is supposed to be LMP V4.0 so I guess it should work ?

Any idea about that ?

Here's the code snippet used:

```js
        ble.startScan([], function(device) {
            console.log(JSON.stringify(device));
        },  function(error) {
            console.log("Start scan ERROR");
        });

        setTimeout(ble.stopScan,
            50000,
            function() { console.log("Scan complete"); },
            function() { console.log("stopScan failed"); }
        );
```

Thanks a lot and for this nice plugin :)

Best regards,

**Comment by don** [comment]
Your Macbook has BLE, but it's not going to show up in a scan unless it's publishing a BLE service.

Try using [bleno](https://github.com/sandeepmistry/bleno) to create a BLE Peripheral. The [echo example](https://github.com/sandeepmistry/bleno/tree/master/examples/echo) is a good place to start.

**Comment by tchauviere** [comment]
Hi @don

Thank you a lot for this hint !

Best regards,
