### ISSUE TITLE
Read Nfc data using BLE

### ISSUE THREAD

**Issue by harshaddevale-tudip** [don/cordova-plugin-ble-central#304]
Hi Don,

I am using BLE plugin to connect with ACR1255 NFC device. In app i need to read NFC data through ACR1255 using bluetooth. I have some questions.
1) Is it possible to read NFC data using BLE plugin? 
2) If no then should i use ionic-nfc-reader plugin to read data 
3) is it neccessary to use nfc enabled android device? 
Or please suggest any plugin to read nfc data using bluetooth.

**Comment by don** [comment]
I'm not familiar with the ACR1255, but I'm guessing it sends the NFC data to a connected Bluetooth client when a NFC tag is scanned.

1) You can't read NFC directly with this plugin, but you should be able to read data from the ACR1255.
2) [ionic-nfc-reader](https://github.com/don/ionic-nfc-reader) is for Android devices with built in NFC readers, it won't help here
3) If you have an Android device with NFC, it might be easier to read the NFC tag directly with that device. When you're using the ACR1255, you won't need NFC on the phone

If the ACR1255 just returns the bytes of data on the tag, my javascript [NDEF library](https://github.com/don/ndef-js) might be helpful for decoding the data.
