### ISSUE TITLE
BLE polling command

### ISSUE THREAD

**Issue by harshaddevale-tudip** [don/cordova-plugin-ble-central#305]
I am able to connect with BLE device and I am getting all services and characteristics, now I have send some commands.I am trying to send polling request to acr1255 nfc device using BLE plugin.
I am not sure how to establish the polling whether by using read or write command and if it is write then in which format i can send the command.

**Comment by harshaddevale-tudip** [comment]
Any update here please?

**Comment by don** [comment]
You can poll a characteristic by continually [reading](https://github.com/don/cordova-plugin-ble-central#read) it, but it's usually better to subscribe to changes *if* the characteristic supports notification. See [ble.startNotification](https://github.com/don/cordova-plugin-ble-central#startnotification).

The commands you send the the device are device specific. You'll need to get that from the ACR1225 documentation. When you send data from JavaScript you need to send an ArrayBuffer. See the examples for [ble.write](https://github.com/don/cordova-plugin-ble-central#write) for ideas on how to format your data.
