### ISSUE TITLE
I scan for devices on Android, and the result is undefined.

### ISSUE THREAD

**Issue by biy-gxnn** [don/cordova-plugin-ble-central#307]
I scan for devices on Android, and the result is undefined. How can I find devices ?

**Comment by don** [comment]
If there are no devices advertising Bluetooth Low Energy services, you won't find any scan results. The best thing is to find a Bluetooth low energy device that is advertising services. The [TI SensorTag](ti.com/sensortag) works well.

You can implement a Bluetooth peripheral using your computer and [bleno](https://github.com/sandeepmistry/bleno).  You can use [ble-peripheral](https://github.com/sandeepmistry/arduino-BLEPeripheral) on an Arduino. If you have an extra iOS device [LightBlue Explorer](https://itunes.apple.com/us/app/lightblue-explorer-bluetooth/id557428110?mt=8) can create virtual peripherals. The latest Android devices can create Bluetooth peripherals. You could try something like [BLE SIM](https://play.google.com/store/apps/details?id=io.github.webbluetoothcg.bletestperipheral&hl=en).
