### ISSUE TITLE
Uncaught ReferenceError: ble is not defined

### ISSUE THREAD

**Issue by miloliva** [don/cordova-plugin-ble-central#31]
This error is happening on base cordova and phonegap as well. "Uncaught ReferenceError: ble is not defined". Cordova 4.2.0.

**Comment by don** [comment]
I am unable to duplicate this on iOS or Android. Can you try the following?

    cd /tmp
    cordova create issue31 com.example.issue31 Issue31
    cd issue31
    cordova platform add android
    cordova plugin add com.megster.cordova.ble

Edit www/js/index.js and change `onDeviceReady` to

    onDeviceReady: function() {
        app.receivedEvent('deviceready');

        ble.isEnabled(
            function() {
                alert("Bluetooth is enabled");
            },
            function() {
                alert("Bluetooth is DISABLED");
            }
        );
    },

Run on Android

    cordova run 

Try on iOS

    cordova platform add ios
    open platforms/io/Issue31.xcodeproj

Run on iOS from Xcode.

Please let me know if this works for you.
