### ISSUE TITLE
is ble.scan stopped when app is killed

### ISSUE THREAD

**Issue by hervethouzard** [don/cordova-plugin-ble-central#310]
Hello,

I'd like to know if a ble.scan() is stopped when the application is closed?
Idem, if I am connected to a peripheral, does the fact to close the app will disconnect the app?

bye,
Hervé

**Comment by don** [comment]
On Android, scan should work in the background. On iOS, you'll need to add [extra configuration to run in the background](https://github.com/don/cordova-plugin-ble-central#background-notifications-on-ios). I have a sample project for background scanning and notifications https://github.com/don/ble-background

**Comment by hervethouzard** [comment]
Hello Don,

Thank you very much for your answer.
In fact I wanted to know if the scan will be (well) stopped when the application is closed.
I don't want to see it running in the background

Bye

**Comment by don** [comment]
iOS should stop the scan in the background unless you explicitly allow background scanning.

If you want to be sure add an event handler for [pause](http://cordova.apache.org/docs/en/latest/cordova/events/events.html#pause).

    document.addEventListener("pause", onPause, false);

    function onPause() {
        ble.stopScan();
    }

**Comment by hervethouzard** [comment]
Hello Don,

thank you very much for your help.
This ticket can be closed.

Bye

**Comment by apperside** [comment]
Hi, I did not understood if it works even if I kill the app, do it? Many thanks
