### ISSUE TITLE
Not able to startNotification after stopping it.

### ISSUE THREAD

**Issue by silverhawk184** [don/cordova-plugin-ble-central#316]
Hello,

If startNotification and then use stopNotification and then startNotification on the same service, does not error but the success callback is never fired either.

To fix, I have to reload the page before starting notifications again.

**Comment by don** [comment]
Can you provide a very simple project to demonstrate?

Are you seeing on iOS or Android? If Android, provide model and Android version. 

Can you provide any details about the peripheral?
