### ISSUE TITLE
Question about Android context

### ISSUE THREAD

**Issue by hoongoon86** [don/cordova-plugin-ble-central#322]
Hi, 

Do we have a particular reason why not specify activity?
I mean, in peripheral.java, 
we use `device.connectGatt(activity, false, this)` to connect BLE,
Would it be wrong if I specify the activity like,
`activity.getApplicationContext()` ?

I was looking for a faster connection.

**Comment by don** [comment]
I don't think it matter if activity or context is passed to `connectGatt` since an `Activity` is a `Context`.

Try editing the code locally. If one is faster, let me know or send a pull request.
