### ISSUE TITLE
Call to startStateNotifications hangs in Developer app.

### ISSUE THREAD

**Issue by mebrunet** [don/cordova-plugin-ble-central#323]
I'm not sure what's happening here, but my calls to startStateNotifications are hanging in the Developer app on both iOS and Android. I have a button that triggers:

```
console.log('here')
ble.startStateNotifications(function(state) { console.log(state); });
console.log('done')
```

In the Phonegap Developer app, when I click the button I see 'here' but not 'done' in the console. Seems to work fine when I build the app out. Any thoughts?

**Comment by hoongoon86** [comment]
Do you get any error messages? or do you see anything regarding state when you change bluetooth state?

**Comment by mebrunet** [comment]
Nothing unfortunately. I haven't built the developer app from source (i.e. it's downloaded from the stores) so I can't remote debug it. I'll give that a try to see if I get anything more helpful.

**Comment by don** [comment]
Are you seeing this on iOS or Android? What phone and OS version are you running? What version of the PhoneGap Developer App?

**Comment by mebrunet** [comment]
I was seeing it on both iOS and Android... Nexus 5 Android 6.0.1, and iPhone 5 running iOS 10.0.2. Developer app is 1.7.2 now, and I'm pretty sure that's where it was at when I tried it before.

I'm just using a setInterval with ble.isEnabled to recreate the functionality. Which works fine.

**Comment by don** [comment]
It's possible the PhoneGap Developer App is using an older version of the plugin. I'll try and duplicate and talk to the Adobe team if it's a version issue.

**Comment by ddugue** [comment]
They are currently using 1.1.4:
[](https://github.com/phonegap/phonegap-app-developer/blob/master/config.xml#L67)


I think you can close this issue
