### ISSUE TITLE
ble plugin can not scan on android 6.0.1

### ISSUE THREAD

**Issue by wzhsh90** [don/cordova-plugin-ble-central#326]
Hi:
 my plugin version:1.1.1  
 mobile os version: android 6.0.1

pre-condition:
 access permssionn
  <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />
  <uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION" />

issue:
  bluetoothAdapter.startLeScan return true but onLeScan not called.

solution: 
   Settings -> Location, I have it turned On and then it work well.

  any good idea to solve this problem?

**Comment by hoongoon86** [comment]
[https://github.com/don/cordova-plugin-ble-central/issues/242](url)
Please refer this link. 
BLE scanning in Android 6 requires location permission.
If you don't want this, I believe you should restrict sdk to 21 or lower.

**Comment by don** [comment]
@wzhsh90 this is an Android restriction so there's not much the plugin can do. 

@hoongoon86 has a good idea to target the older android-21 sdk. Please update this issue if it works.
