### ISSUE TITLE
I can not scan my phone from the tablet using BLE

### ISSUE THREAD

**Issue by hichamrifai** [don/cordova-plugin-ble-central#327]
Hi,
I have been trying to run the  ble.scan() to scan for devices around. I am able to detect iphone and beacons but not android devices.  I can only detect my phone if I use a beacon simulator on the android phone.  Did I miss a small detail like the order of adding the plugin?  could you help me with that?
Thanks
Regards
Hicham

**Comment by don** [comment]
The plugin will only find your tablet if the tablet is advertising a Bluetooth LE service. I think the nRF Connect app will advertise services on newer Android devices.  See #292 for more details.

**Comment by hichamrifai** [comment]
Thanks for your reply! does this applies even if the phone and the tablet are paired.  
Thanks
Hicham

**Comment by don** [comment]
@hichamrifai pairing is typically for Bluetooth Classic. Bluetooth low energy devices need to advertise a service so it can be discovered.
