### ISSUE TITLE
readRSSI in Ionic2

### ISSUE THREAD

**Issue by DaniloCodecoCarvalho** [don/cordova-plugin-ble-central#338]
Hi.
I'm using the ble-central plugin and it works great but my APP needs to disconnect when I'm leaving.
When I tried to use the readRSSI function I realized that the function is only available in Ionic 1.x.

Is that right?
Is possible to readRSSI in Ionic 2?

Thank you.

**Comment by don** [comment]
This plugin isn't specific to Ionic 1 or Ionic 2. 

I think Ionic's wrapper might be missing this call. https://ionicframework.com/docs/v2/native/ble/. I'd suggest adding this new function to the [wrapper](https://github.com/driftyco/ionic-native/blob/master/src/plugins/ble.ts) and submitting a pull request to @driftyco.

Alternately you can always call [ble.readRSSI](https://github.com/don/cordova-plugin-ble-central#readrssi) directly.
