### ISSUE TITLE
Scan needed before connecting?

### ISSUE THREAD

**Issue by Rlopez** [don/cordova-plugin-ble-central#340]
Hi there!
I have an app that locally stores name and address of BLE devices (as returned by Scan). In later runs, if I try to connect to the stored BLE device without performing a scan() I'll get a "Peripheral 20:91:48:DD:AF:24 not found." Doing a Scan() makes the issue goes away 

So, in essence:
ble.connect("20:91:48:DD:AF:24") //fails
ble.scan(...)
ble.connect("20:91:48:DD:AF:24") //works

I haven't seen any mention of that requirement in the docs, so I am not sure if it is a bug or intended, any advice welcome :)

**Comment by bipintek** [comment]
I am also facing the same issue. Once scan() has been called, connect() works even if it is called many times.

**Comment by don** [comment]
Yes, you need to call scan() once so the plugin can get a list of the devices.

**Comment by Rlopez** [comment]
wouldn't it be possible to store some extra data so that the scan call is not needed?

**Comment by lastmjs** [comment]
@Rlopez I was thinking the same thing
