### ISSUE TITLE
Native Android error while disconnecting while connection is failing

### ISSUE THREAD

**Issue by Rlopez** [don/cordova-plugin-ble-central#348]
To repro do establish a connection and then kill the remote BT device (say power its radio off), then, and before we get the error callback in ble.connect()), do a ble.disconnect(), often you will get a:

> couldn't disconnect:[object Object] with error:Attempt to invoke virtual method 'void android.bluetooth.BluetoothGatt.close()' on a null object reference

What makes the issue sort of bad is that the application will not be able to recover from the error unless it is reloaded

Could it be related to this [Google Code issue](https://code.google.com/p/android/issues/detail?id=183108)?

**Comment by don** [comment]
See #412
