### ISSUE TITLE
Ionic 2 scan callbacks not called on android 6 with location enabled

### ISSUE THREAD

**Issue by Danger08** [don/cordova-plugin-ble-central#359]
Does not return any error callbacks or detect devices. Maybe i can get any help Thanks

**Comment by Danger08** [comment]
BTW im using this code :)
BLE.scan([],5)
.subscribe(res=>{

console.log(JSON.stringify(res));
}

**Comment by don** [comment]
The [Ionic BLE object](https://ionicframework.com/docs/v2/native/ble/) is a wrapper around my plugin. 

See if you can get my [BluefruitLE example](https://github.com/don/cordova-plugin-ble-central/tree/master/examples/bluefruitle) working with your hardware.
