### ISSUE TITLE
Keep scanning on background

### ISSUE THREAD

**Issue by twinsit** [don/cordova-plugin-ble-central#361]
Hi,

For a project I need to create an app that makes it possible to have continuous scanning (android phone will only be used for this). The phone will be connected to a power source.

The idea is that all BLE devices are detected and in case of a certain manufacturer (or if it is a beacon), the UDID is sent to a webservice.

In fact we need every 2 seconds all detected devices on our server. Is this something that is possible with your plugin?

Thanks

Wouter

**Comment by don** [comment]
@twinsit you can use [ble.startScan](https://github.com/don/cordova-plugin-ble-central#startscan) to scan forever. If you want to track devices you might need [ble.startScanWithOptions](https://github.com/don/cordova-plugin-ble-central#startscanwithoptions) so you see duplicates. See https://github.com/don/cordova-plugin-ble-central#quick-example-2
