### ISSUE TITLE
Fail connect to ble, return error "peripheral disconnected"

### ISSUE THREAD

**Issue by chubzchoc** [don/cordova-plugin-ble-central#362]
I do scan method and the other 2 times. First, I scan bluetooth, connect, write data and disconnect. Then I scan new bluetooth and want to connect with it. But when I use ble.connect(), I got error message: "peripheral disconnected". At the first section, connecting bluetooth is success, but at last section, I can't connect with ble device. It returns error when I call ble.connect.

How to solve this?
thank you

**Comment by don** [comment]
Are you seeing on iOS or Android?

This happens every time with different devices, I'd look at something in your code.
If it only happens with certain devices, I'd look into those devices.

**Comment by chubzchoc** [comment]
I'm using in Android..

**Comment by chubzchoc** [comment]
Hi Don, 
I have solved this issue.. 
I've test my code to connect another BLE device and it's work..
When I get error, I using TI Sensortag.
thanks

**Comment by don** [comment]
@chubzchoc glad you solved it

**Comment by nadeem2378** [comment]
@chubzchoc what is TI Sensortag? i am having the same error.

**Comment by mburger81** [comment]
We got this error also many many many times.

If we try to connect to device we get this error and in this case we have to retry many times to connect to devices, after several tentatives finally it works.

We have this problem on many different devices, if we do a connection over android interface, at least there is never showing a connection error and it is very fast.

So what could the problems be for that?
