### ISSUE TITLE
"Uncaught ReferenceError: ble is not defined"

### ISSUE THREAD

**Issue by cristinatocu** [don/cordova-plugin-ble-central#363]
Hello, I have the following issue. I created an android build release for the BLE app described in this tutorial.

http://makezine.com/projects/controlling-a-lock-with-an-arudino-and-bluetooth-le/

The app works fine when deploying and executing it through PhoneGAP. However, when trying to use the build release I get the following errors:

>E/chromium: [ERROR:interface_registry.cc(99)] Failed to locate a binder for interface: autofill::mojom::AutofillDriver
D/CordovaWebViewImpl: onPageFinished(file:///android_asset/www/index.html)
E/AndroidProtocolHandler: Unable to open asset URL: file:///android_asset/www/cordova_plugins.js
D/SystemWebChromeClient: file:///android_asset/www/js/index.js: Line 60 : Uncaught ReferenceError: ble is not defined
I/chromium: [INFO:CONSOLE(60)] "Uncaught ReferenceError: ble is not defined", source: file:///android_asset/www/js/index.js (60)
D/ViewRootImpl: ViewPostImeInputStage processPointer 0
D/ViewRootImpl: ViewPostImeInputStage processPointer 1
D/ViewRootImpl: ViewPostImeInputStage processPointer 0
D/SystemWebChromeClient: file:///android_asset/www/js/index.js: Line 60 : Uncaught ReferenceError: ble is not defined
I/chromium: [INFO:CONSOLE(60)] "Uncaught ReferenceError: ble is not defined", source: file:///android_asset/www/js/index.js (60)
D/ViewRootImpl: ViewPostImeInputStage processPointer 1
D/ViewRootImpl: ViewPostImeInputStage processPointer 0
D/SystemWebChromeClient: file:///android_asset/www/js/index.js: Line 60 : Uncaught ReferenceError: ble is not defined
I/chromium: [INFO:CONSOLE(60)] "Uncaught ReferenceError: ble is not defined", source: file:///android_asset/www/js/index.js (60)
D/ViewRootImpl: ViewPostImeInputStage processPointer 1
D/ViewRootImpl: ViewPostImeInputStage processPointer 0
D/SystemWebChromeClient: file:///android_asset/www/js/index.js: Line 60 : Uncaught ReferenceError: ble is not defined
I/chromium: [INFO:CONSOLE(60)] "Uncaught ReferenceError: ble is not defined", source: file:///android_asset/www/js/index.js (60)
D/ViewRootImpl: ViewPostImeInputStage processPointer 1
D/CordovaActivity: Paused the activity.
D/CordovaActivity: Stopped the activity.
V/ActivityThread: updateVisibility : ActivityRecord{b222251 token=android.os.BinderProxy@2bbbac7 {com.megster.bluefruitle/com.megster.bluefruitle.MainActivity}} show : false
D/CordovaActivity: Started the activity.
D/CordovaActivity: Resumed the activity.
I/Timeline: Timeline: Activity_idle id: android.os.BinderProxy@2bbbac7 time:23552244
D/ViewRootImpl: ViewPostImeInputStage processPointer 0
D/ViewRootImpl: ViewPostImeInputStage processPointer 1
D/ViewRootImpl: ViewPostImeInputStage processPointer 0
D/ViewRootImpl: ViewPostImeInputStage processPointer 1
D/ViewRootImpl: ViewPostImeInputStage processPointer 0
D/ViewRootImpl: ViewPostImeInputStage processPointer 1
D/ViewRootImpl: ViewPostImeInputStage processPointer 0
D/SystemWebChromeClient: file:///android_asset/www/js/index.js: Line 60 : Uncaught ReferenceError: ble is not defined
I/chromium: [INFO:CONSOLE(60)] "Uncaught ReferenceError: ble is not defined", source: file:///android_asset/www/js/index.js (60)
D/ViewRootImpl: ViewPostImeInputStage processPointer 1
D/ViewRootImpl: ViewPostImeInputStage processPointer 0
D/SystemWebChromeClient: file:///android_asset/www/js/index.js: Line 60 : Uncaught ReferenceError: ble is not defined
I/chromium: [INFO:CONSOLE(60)] "Uncaught ReferenceError: ble is not defined", source: file:///android_asset/www/js/index.js (60)
D/ViewRootImpl: ViewPostImeInputStage processPointer 1
D/ViewRootImpl: ViewPostImeInputStage processPointer 0
D/ViewRootImpl: ViewPostImeInputStage processPointer 1
D/ViewRootImpl: ViewPostImeInputStage processPointer 0
D/ViewRootImpl: ViewPostImeInputStage processPointer 1
D/ViewRootImpl: ViewPostImeInputStage processPointer 0
D/ViewRootImpl: ViewPostImeInputStage processPointer 1
D/ViewRootImpl: ViewPostImeInputStage processPointer 0
D/SystemWebChromeClient: file:///android_asset/www/js/index.js: Line 60 : Uncaught ReferenceError: ble is not defined
I/chromium: [INFO:CONSOLE(60)] "Uncaught ReferenceError: ble is not defined", source: file:///android_asset/www/js/index.js (60)
D/ViewRootImpl: ViewPostImeInputStage processPointer 1
D/ViewRootImpl: ViewPostImeInputStage processPointer 0
D/ViewRootImpl: ViewPostImeInputStage processPointer 1
D/CordovaActivity: Paused the activity.
D/CordovaActivity: Stopped the activity.
V/ActivityThread: updateVisibility : ActivityRecord{b222251 token=android.os.BinderProxy@2bbbac7 {com.megster.bluefruitle/com.megster.bluefruitle.MainActivity}} show : false
Application terminated.

I also looked at the issue #31 but it does not seem to work. Is there any fix for this error?

**Comment by don** [comment]
`Uncaught ReferenceError: ble is not defined` means the plugin isn't installed correctly

Are you using Cordova 6.5.0 and cordova-plugin-ble-central version 1.1.4?

Did you try removing and re-installing the plugin?

    cd path/to/project
    cordova plugin rm cordova-plugin-ble-central
    cordova plugin add cordova-plugin-ble-central

Also make sure your Android SDK is up to date.
