### ISSUE TITLE
Can i connect 2 ble at the same time? 

### ISSUE THREAD

**Issue by puneet9** [don/cordova-plugin-ble-central#364]
Hello Don,

I am trying to connect two accelerators using ble and want to read their reading simultaneously which means both should be connected at the same time. Is there any solution for that?

**Comment by don** [comment]
Yes, the plugin supports multiple simultaneous connections. The number of connections will be limited by your phone hardware. I know people been able to simultaneous talk to 7 peripherals from an iPhone.

**Comment by puneet9** [comment]
Thanks Don
