### ISSUE TITLE
How to find service_uuid and characteristic_uuid?

### ISSUE THREAD

**Issue by styfle** [don/cordova-plugin-ble-central#365]
I am able to scan and connect to my device but not write any data.

```js
ble.write(device_id, service_uuid, characteristic_uuid, data, success, failure);
```

How can I find the `service_uuid` and the `characteristic_uuid` for my device?

Thanks! 😄

**Comment by don** [comment]
The service_uuid and characteristic_uuid control where the data is written.

Read the docs for the peripheral or use [nRF Connect](https://play.google.com/store/apps/details?id=no.nordicsemi.android.mcp&hl=en) or [LightBlue Explorer](https://itunes.apple.com/us/app/lightblue-explorer-bluetooth-low-energy/id557428110?mt=8) to see what services your peripheral offers.

Check out my book [Make:Bluetooth](https://www.amazon.com/Make-Bluetooth-Projects-Raspberry-Smartphones/dp/1457187094) to learn more about Bluetooth LE and how to use this plugin.
