### ISSUE TITLE
startNotification is not working for automatic request on ble device

### ISSUE THREAD

**Issue by AShakthivel** [don/cordova-plugin-ble-central#366]
Hello don,

Thanks for giving such a wonderful plugin. I am using a BLE device which is used to get the values in a real time. I used your [ble.startNotificaiton](https://github.com/don/cordova-plugin-ble-central#startnotification) and it is working only for manual request. I want to get the data from the device in real time. When it is changing the value I'm not able to get the data with out manual request. I guess when the `characteristic_uuid` is changing, then then the data is received from the ble device. But somehow it is not working. Is there any way to debug this issue or any supports available that can help me to achieve this task?

Thanks in advance,
Shakthivel A.

**Comment by don** [comment]
@AShakthivel once you register a callback for startNotifcation it should be call every time that characteristic value changes on the peripheral (as long as you are connected.)

What do you mean by manual request? Normally characteristic UUID will not change.
