### ISSUE TITLE
Windows 10 support

### ISSUE THREAD

**Issue by VinceFa** [don/cordova-plugin-ble-central#368]
Hi ! I would like to know if Windows support (especially Windows 10) is still planned.

**Comment by don** [comment]
@VinceFa currently Windows 10 doesn't support scanning for peripherals yet, you need to pair BLE peripherals before they can be used. 

Microsoft is working on this and scanning functionality is supposed to be in [Windows 10 preview SDK](https://www.microsoft.com/en-us/software-download/windowsinsiderpreviewSDK). 

So soon it will be possible to implement this for Windows 10. I'll probably add this if I need it for a project or someone hires me to add it for their project.

**Comment by VinceFa** [comment]
Thanks for your answer ! Is the scanning functionality the only missing part of the plugin (for W10) ? Or do you mean that you will add all the W10 support later ? I have a doubt since there's no mention at all about Windows  in the readMe file. Anyway, thanks a lot for your plugin :)

**Comment by don** [comment]
Currently any Windows code is stubs for PhoneGap Developer App, nothing actually works.

The Windows Bluetooth APIs currently require manual pairing of BLE devices from Windows, so as it stands the scanning feature of the plugin can not be implemented on Windows. Windows 10 preview SDK adds the new API calls needed to implement all the features.

**Comment by don** [comment]
See #470

**Comment by one0410** [comment]
Hello Don, any update for windows support ?

**Comment by mexxwill** [comment]
@don any news update this? :)

**Comment by peitschie** [comment]
The Windows platform has been deprecated as a cordova platform.
See https://github.com/apache/cordova/blob/master/deprecated.md#deprecated-platforms
