### ISSUE TITLE
How to change pin mode to Analog

### ISSUE THREAD

**Issue by oularrea** [don/cordova-plugin-ble-central#370]
Hello, I would like to ask a question
I'm working with a redbearlab device and I need to know how to put the pins in analog mode and then how can I get those values in real time with the startNotifications method of this plugins

Many thanks that I have tried for several days, but I can not read the values of the pins.

I anticipate that they will always be the pins from 18 to 23

Thank you very much for your answers in advance.

**Comment by don** [comment]
You need to change the pin type in the Arduino sketch. The characteristic you want to track must have the BLENotify property. Then in Cordova, you subscribe for notifications using ble.startNotification() on that characteristic.

See [slides 32]( http://don.github.io/slides/2016-10-01-arduino-ble/#/32) through 37 for a Bluetooth LE thermometer built with [blePeripheral](https://github.com/sandeepmistry/arduino-BLEPeripheral) on an Arduino Uno and the RedBear BLE shield. You should be able to modify this to work for your needs.

[Arduino Sketch](https://github.com/don/mfny2016-arduino-ble/blob/master/Thermometer/Thermometer.ino)
[Cordova App](https://github.com/don/mfny2016-arduino-ble/tree/master/cordova/thermometer)

Also checkout my book [Make:Bluetooth](https://www.amazon.com/Make-Bluetooth-Projects-Raspberry-Smartphones/dp/1457187094) for Cordova and Arduino examples.
