### ISSUE TITLE
isConnected() not reflecting REAL connection status of a device

### ISSUE THREAD

**Issue by xiangjunhuang** [don/cordova-plugin-ble-central#377]
Hi,

It's quite offten, a BLE device is connected to a mobile phone through different APP. Or maybe just connected by a previous run of the same APP, and for some reason, the connection was there till next run of this APP. then when a APP is loaded again, if you check the device's connection status through BLE.isConnected(id), it will get "not connected" result.

I believe this need to be fixed.

**Comment by don** [comment]
isConnected reports the status from the apps point of view. The peripheral is not connected to the app so I believe the current behavior is correct. 

If you have the UUID or MAC address of the device that is connected to the other app, you should be able to call connect and connect the your app to it.

An enhancement is to allow the app to get a list of connected devices or return the connected devices in the scan results. See #379 Maybe you can work with @fraxool on a pull request.
