### ISSUE TITLE
Adding custom advertisement data

### ISSUE THREAD

**Issue by abrahamguo** [don/cordova-plugin-ble-central#378]
Is there a way to use this library to write custom advertisement data to a BLE device? We cannot use characteristics, because they are only available after a BLE device has already been connected. We need to broadcast some custom information before connecting to the beacon.

Thanks!

**Comment by don** [comment]
@abrahamguo this plugin handles the central role, so there's no advertising or broadcasting. 

[cordova-plugin-ibeacon](https://github.com/petermetz/cordova-plugin-ibeacon) will let you create a beacon.

[cordova-plugin-ble-peripheral](https://github.com/don/cordova-plugin-ble-peripheral) (iOS-only) will let you create peripherals and advertise services. 

If those don't work, it might be best to create a custom plugin that does exactly what you need.
