### ISSUE TITLE
Bluetooth device becomes invisible after it has been paired...

### ISSUE THREAD

**Issue by fraxool** [don/cordova-plugin-ble-central#379]
Hello,

I think it's a duplicate of #372 which has been closed. But the issue is still here. 

If you use a Bluetooth device - like a smart watch - which can be paired with an iPhone, the Bluetooth device is not visible anymore. So it's not possible to connect, to write or to notify.

I'm using the last version (1.1.4) of the plugin.

Hope it will be solved soon!

Thanks,
Axel

**Comment by don** [comment]
If you have the UUID of the device you should be able to connect.

[CBCentralManager:retrieve​Connected​Peripherals​With​Services:​](https://developer.apple.com/reference/corebluetooth/cbcentralmanager/1518924-retrieveconnectedperipheralswith?language=objc) should return connected devices *if* you specify the service.

Android has [BluetoothManager.getConnectedDevices](https://developer.android.com/reference/android/bluetooth/BluetoothManager.html#getConnectedDevices(int))

The fix is probably to add a flag to [ble.startScanWithOptions](https://github.com/don/cordova-plugin-ble-central#startscanwithoptions) to return connected devices. Or perhaps to add a getConnectedDevices API call. The new API call is tricky because iOS needs a service but Android doesn't.

**Comment by fraxool** [comment]
Thanks for the reply.

`If you have the UUID of the device you should be able to connect.`

I have the UUID. So with this UUID, I should be able to connect without adding a new API call like "getConnectedDevices" ? I'm not really sure how to connect if I can't "scan" the device. 
Should I just use the function "BLE.connect()" with the known UUID if the device has previously been paired ? 

Because I have tested to check if the device is connected (with the isConnected function) and it returned false.

**Comment by don** [comment]
For iOS the UUID is generated so there's not a good way to get this without the new API. You should be able to disconnect the other app and scan to get the UUID for testing.

Ultimately scan should probably return connected devices. It'd be great if you could take a stab at implementing this.

**Comment by florianchappuis** [comment]
Hi, I have the same issue than you fraxool? Have you managed to find a solution?

I have a peripheral bluetooth low energy (Nordic NRF51), I'm pairing up with it with my smartphone from the settings interface. They are bonded together, if i call scan() method, it isn't found. If I call connect method with the right MAC address, it says Peripheral MAC_ADDRESS not found. If i try to read a service, it returns : 
[INFO:CONSOLE(1362)] "ERROR", source: file:///android_asset/www/build/main.js (1362)

Could you help me?

**Comment by fraxool** [comment]
@florianchappuis I personally never found a solution so I ended up using another library (evothings) which works well with pairing.

**Comment by JonasWestAlro** [comment]
Hi, 

Still no news on this one? :)

**Comment by ddugue** [comment]
Hey guys,
Is this an issue on both iOS and Android?
By the way, the plugin requires the device to have been scanned before being connected to.

**Comment by JonasWestAlro** [comment]
I haven't tried on Android yet. 
I am running towards a deadline, so I will try the evothings as well :)

**Comment by florianchappuis** [comment]
I used the evothings library, which i had to adapt because it way in javascript and ionic is in typescript, but it worked pretty well. Maybe they updated it. It was for a school project so i don't use it anymore

**Comment by JonasWestAlro** [comment]
Yeah, I also had be make some small adjustments to make it work. Though when I am scanning, connected devices doesn't popup :( 

Did you just connect directly or something? @florianchappuis

**Comment by don** [comment]
On iOS, the plugin still needs to know about the UUID. Try [ble.peripheralsWithIdentifiers](https://github.com/don/cordova-plugin-ble-central#peripheralswithidentifiers) or [ble. connectedPeripheralsWithServices](https://github.com/don/cordova-plugin-ble-central#connectedperipheralswithservices) if you don't want to scan.

Note that on recent versions of the plugin with Android, you connect using a MAC address without scanning.  Added [ble.bondedDevices](https://github.com/don/cordova-plugin-ble-central#bondeddevices) for Android.
