### ISSUE TITLE
plugin understanding related questions 

### ISSUE THREAD

**Issue by alexdoso** [don/cordova-plugin-ble-central#380]
Hello, I am pretty new to hybrid app making with Javascript, hence please help me with my little stupid questions, since I cannot get it or how to document myself, so here is the first:  

In **https://github.com/don/cordova-plugin-ble-central/blob/master/examples/sensortag/www/js/index.js** there is code that looks like this: 
`showDetailPage: function() {
        mainPage.hidden = true;
        detailPage.hidden = false;
    },`   

from where **.hidden** property to mainPage or detailPage is invoked from ? I cannot find "**hidden**" elsewhere on the entire plugin folder, there is no track of it even in ble.js

**Comment by don** [comment]
@alexdoso hidden is a global html attribute (see https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/hidden). The showDetailPage function is showing and hiding parts of the user interface by manipulating the DOM with JavaScript.

Lots of Cordova development is web development. There are lots of tutorials on Cordova/PhoneGap. Unfortunately there are hundreds of ways to do everything.  http://stackoverflow.com is a good place to ask generic development questions.

My book [Make:Bluetooth](https://www.amazon.com/Make-Bluetooth-Projects-Raspberry-Smartphones/dp/1457187094/ref=sr_1_3?ie=UTF8&qid=1490879543) covers using Cordova with BLE.
