### ISSUE TITLE
 EXC_BAD_ACCESS

### ISSUE THREAD

**Issue by claudiovolpato** [don/cordova-plugin-ble-central#389]
hi Don,
when compiling your code with xcode 8.1 and run it on iOS 9.3.5 the following line of code:
  
 // check and handle disconnected peripherals
    for (CBPeripheral *peripheral in peripherals) { ....

to get : EXC_BAD_ACCESS

Can you help me? Thanks.

**Comment by don** [comment]
I won't have access to iOS 9 devices until next week. Does this error happen every time?

**Comment by claudiovolpato** [comment]
Hi Don,
yes every time :-(

**Comment by claudiovolpato** [comment]
Seems to be an initialization problem for the NSMutableSet * peripherals variable.
  Unfortunately I do not know object-C :-(

**Comment by claudiovolpato** [comment]
Ho Don, Did you find a minute for me? :-)

**Comment by claudiovolpato** [comment]
Hi Don, i have found the problem:
in pluginInitialize i have substitute

    peripherals = [NSMutableSet set];
with
    peripherals = [NSMutableSet new];

now works.
Thanks anyway :-)

**Comment by don** [comment]
@claudiovolpato thanks for updating me with the answer, I'll look at getting this into the next release
