### ISSUE TITLE
BluetoothDevice.TRANSPORT_LE not found in Peripheral.java

### ISSUE THREAD

**Issue by tgallagher2017** [don/cordova-plugin-ble-central#390]
I'm not sure the environment matters, but I'm using Oracle Eclipse Package for Enterprise which provides the Mobile Application Framework (MAF), on a Mac with Java 8.  I get the following error when I compile:  
com/megster/cordova/ble/central/Peripheral.java:74: error: cannot find symbol
    [javac]             gatt = device.connectGatt(activity, false, this, BluetoothDevice.TRANSPORT_LE);
    [javac]                                                                             ^
    [javac]   symbol:   variable TRANSPORT_LE
    [javac]   location: class BluetoothDevice

**Comment by don** [comment]
Your SDK level is too low.  [BluetoothDevice.TRANSPORT_LE](https://developer.android.com/reference/android/bluetooth/BluetoothDevice.html#TRANSPORT_LE) was added in android-23.

You need to compile with Android-23 or greater. I recommend using the latest Android-25. You can still target lower level SDKs for deployment like Android-19 for deployment.

The plugin conditionally checks for API level 23 before using TRANSPORT_LE. https://github.com/don/cordova-plugin-ble-central/blob/master/src/android/Peripheral.java#L71-L75
