### ISSUE TITLE
$cordovaBLE.connect() not calling the .catch part of the promise

### ISSUE THREAD

**Issue by Heckthor** [don/cordova-plugin-ble-central#392]
Hi Don,
I have a quick question. I'm developing on iOS and the plugin works great: scans, connects and transfer data back and forth with no problem whatsoever; however, when disconnecting the peripheral or trying to make the connect() function fail, the .catch is not called. I assume, since everything else works, that my code is correct. Here is the relevant part of the code:

```
$cordovaBLE.connect(deviceID)
      .then(function(peripheral){
        localStorage.connectedDeviceID = deviceID;
        ble.startNotification(deviceID, BleBoard.serviceUUID,
        BleBoard.rx, function(buffer){
        //do whatever
        },
        function(err){
          console.log(err);
        });
        $state.go('options');
      })
      //The following never gets called
      .catch(function(err){
        console.log("Disconnected?");
        console.error(err);
      });
```

**Comment by don** [comment]
I'm not sure which API you're using. Did you wrap my API in a promise? The failure callback for connect is long lived and can be called anytime after success, so a Promise won't work. An Observable world be a better choice.
