### ISSUE TITLE
Multiple problems with "bluefruitle" example...

### ISSUE THREAD

**Issue by zsdan88** [don/cordova-plugin-ble-central#393]
Hi I am trying to get to grips with the plugin, and would like to connect to a BLE device - I think it is the HM-10 or similar. I am testing on actual and virtual peripherals but cant seem to hold a connection using an untouched version of the "bluefruitle" example?

When in the app it scans fine and shows a list of peripherals and mac addresses - but when selecting one - it just give me this: "ERROR: Peripheral null not found". Also I occasionally get another alert with "ERROR: [object Object]". 

Something is obviously not working so any help would be appreciated! I have attached a log of when the errors occur if this helps.

I am running Android 5.1. Using very recent Android SDK and Cordova.

<img width="1043" alt="screen shot 2017-04-21 at 11 58 36" src="https://cloud.githubusercontent.com/assets/27854131/25274813/e378f998-2689-11e7-9539-3938e3d0605c.png">

Thanks!

**Comment by don** [comment]
The bluefruitle example is expecting the peripheral to have the Nordic Semiconductor UART service. I'm guessing that your device doesn't have this.
