### ISSUE TITLE
Cannot Read on Android

### ISSUE THREAD

**Issue by smanda7** [don/cordova-plugin-ble-central#397]
I am trying to pair a Samsung Galaxy note 4 with a adafruit bluefruit trinket. I am able to scan, connect to my device successfully, and run isConnected to keep checking the status of the connection. When I try to read data being sent from the adafruit board, I keep getting a "Read failed" error on my app. I have given the ble.read function the bluetooth address, UART service UUID, and tried both the Tx and Rx UUIDs given for the board as input, but I still keep getting the "Read failed" error. Any thoughts on why this is happening?

**Comment by don** [comment]
See if you can get my bluefruit example working https://github.com/don/cordova-plugin-ble-central/tree/master/examples/bluefruitle
