### ISSUE TITLE
How to get UUID, major, minor in scan result?

### ISSUE THREAD

**Issue by Linerd00** [don/cordova-plugin-ble-central#4]
Thanks this plugin, everything works well on IOS devices.

But I can't get enough info in callback returned data. I develop mobile app using cordova, don't know much about Objective C, could anyone tell me what can I do (I guess it is necessary to change plugin Objective C codes, right?) to get UUID, major, minor in the result of ble.scan(services, seconds, success, failure);?

And after pair with iBeacon device, ble.read() only return read status, not the characteristic value. What codes should I change to return the value or do I misuse it?

I just simply use the example code:
==================== scan (after connect successfully) =====================
ble.scan([], 5, scanSuccess, scanFail);
function scanSuccess(data){
    alert("scanSuccess: " + JSON.stringify(data));
}
function scanFail(data){
    alert("scanFail: " + JSON.stringify(data));
}
==================== read (after write password successfully) ================
ble.read(device_id, service_uuid, characteristic_uuid, readSuccess, readFailure);
function readSuccess(data){
    alert("readSuccess: " + JSON.stringify(data));
}
function readFailure(data){
    alert("readFailure: " + JSON.stringify(data));
}
## Any help is much appreciated.

The reason I need more info is I need to develop an app to auto configure the beacon:

After scan, generate a beacon list, click one beacon:
if its characteristics are default value, auto write them
if all its characteristic (uuid, major, minor) are written well, call web service to update database

**Comment by jonalling** [comment]
@Linerd00 what other plugin did you end up using to scan for UUID, Major, Minor?

**Comment by Linerd00** [comment]
@jonalling I used this one: https://github.com/petermetz/cordova-plugin-ibeacon
Sorry about the late reply, I never check the notifications of this account till now...I guess you have already found the answer

**Comment by don** [comment]
@jonalling you can manually parse the advertising info but I'd go with @Linerd00 and use https://github.com/petermetz/cordova-plugin-ibeacon
