### ISSUE TITLE
Data decreases after 17 sec

### ISSUE THREAD

**Issue by puneet9** [don/cordova-plugin-ble-central#400]
Hello don,

i am connecting ble using your plugin in cordova, and expecting 50 readings per second when setting Hz to 50 hz on ble, i get 50 readings for first 17 seconds bt after that it just shrinks to 5 readings per second, is it do something with the startnotification thing or the array buffer gets overwhelmed?can you please help me with this query?

**Comment by don** [comment]
I think you're sending data too fast for the Bluetooth stack. On iOS, I find that I need 30ms between notifications. On Android things need to be even slower.

If you really need to send data at 50Hz, Bluetooth Classic would be a better choice.
