### ISSUE TITLE
Invalid Action on write

### ISSUE THREAD

**Issue by drekbr** [don/cordova-plugin-ble-central#403]
Hi folks!

I'm trying to build an app on Android to control a Bluetooth relay board. I can connect but, when i try to write, i receive the error "Invalid Action". I have tested the same command with the nRF Connect app, using the same service and characteristic, and everything works right.

The code that i'm using is:

var command = new ArrayBuffer();
command[0]=0xC5;
command[1]=0x04;
command[2] = 0x31;
command[3] = 0x32;
command[4] = 0x33;
command[5] = 0x34;
command[6] = 0x35;
command[7] = 0x36;
command[8] = 0x37;
command[9] = 0x38;
command[10] = 0xAA;

var command2 = new Uint8Array(command);

ble.write(boardID, serviceID, characID, command2.buffer,
   function() {
     document.getElementById('systemMessage').innerHTML = "<p>Command sent: " + comando2.buffer + "</p>";
   }, function(error) {
     document.getElementById('systemMessage').innerHTML = "<p>Command " + comando2.buffer + " to " + boardID + ", " + serviceID + ", " + characID + " NOT sent: " + error + "</p>";
   });

After sent, i have the HTML: Command [object ArrayBuffer] to XX:XX:XX:XX:XX:XX, 0000ffe0-0000-1000-8000-00805f9b34fb, 0000ffe1-0000-1000-8000-00805f9b34fb NOT sent: Invalid Action

Am i doing something wrong?

Thanks.

**Comment by don** [comment]
Construct the buffer using Uint8Array. Replace `var command = new ArrayBuffer();` with `var command = new Uint8Array(10);`

Check the properties on the 0000ffe1-0000-1000-8000-00805f9b34fb characteristic and ensure that it's allows WRITE. It's possible it has the WRITE_WITH_RESPONSE property and you need to call  ble.writeWithoutResponse.
