### ISSUE TITLE
How to tell which device disconnected?

### ISSUE THREAD

**Issue by ccravens** [don/cordova-plugin-ble-central#404]
Hello:

when I'm connected to a BLE device and it unexpectedly disconnects (loss of power, out of range, etc), the connect function triggers the "error" callback as expected. However there is no information about what device disconnected! All I receive is the following:

```
{
  "available": true,
  "platform": "Android",
  "version": "6.0.1",
  "uuid": "58f4234e73d283f",
  "cordova": "6.0.0",
  "model": "SM-J320V",
  "manufacturer": "samsung",
  "isVirtual": false,
  "serial": "74fc393f"
}
```

How can I tell which device (MAC address, name or id) disconnected?

**Comment by don** [comment]
I try to pass the peripheral object that disconnected to disconnect function, but there are some cases that might not send it.

Alternately, use a closure so your disconnect function has a reference to the device id.
