### ISSUE TITLE
Sending bluetooth message automatically 

### ISSUE THREAD

**Issue by nonlinearmind** [don/cordova-plugin-ble-central#405]
Hello,

I've been using this plug-in very successfully, but I'm trying to do something with it now that has been having trouble. I want my Cordova app to communicate with my Web server, and depending on the response, to then automatically send a Bluetooth message to my Arduino device.   I found that I am able to send the Bluetooth message when there is an event listener and user interaction, but I cannot get it to send the Bluetooth message automatically from the success callback of a web post. I'm wondering why this is and how I would go about doing it.

**Comment by don** [comment]
@nonlinearmind you should be able to send bluetooth messages from the callback of a web post.

I expect there's a scoping error. It's likely that `ble` or your function is out of scope in your web post callback. Make sure you're debugging the JavaScript with chrome://inspect (android) or the safari debugger (ios).  I usually solve this with [Function.prototype.bind()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function/bind).
