### ISSUE TITLE
ERROR when disconnecting

### ISSUE THREAD

**Issue by asierdanjou** [don/cordova-plugin-ble-central#412]
Hi, 
Sometimes when trying to disconnect I get this error:

_ERROR: Attempt to invoke virtual method 'void android.bluetooth.BluetoothGatt.close()' on a null object reference._

my disconnect function is next one:

    _disconnect: function(event) {
        ble.disconnect('00:A0:50:A3:25:9E', app.onOkDis, app.onError);
    },_

Any idea why does It catch this onError event ? 
Regards,
Asier.

**Comment by acutetech** [comment]
My apologies to all for not reading this before posting #416, which is probably the same as this issue. Asier - do you see the other cases I reported? What phone(s) are you using?

**Comment by asierdanjou** [comment]
I'm using a Samsung galaxy S4 with Android 5.0.1
Yes, I read the others cases. In my phone sometimes it goes as expected, and other times happens which you described at second case but peripheral always gets disconnect although it has reported error.
I do a simple code just for testing Connect and Disconnect functions.
I've tested 'cordova.exec( app.onOkDis, app.onError, 'BLE', 'disconnect', [deviceId]);' instead 'ble.disconnect(deviceId, app.onOkDis, app.onError);' but same issue happens.

**Comment by don** [comment]
The disconnect implementation needs better null handling.

**Comment by asierdanjou** [comment]
Any example for null handling ?

**Comment by acutetech** [comment]
For me this worked: change disconnect() so it only calls gatt.disconnect(), then in onConnectionStateChange(), in the else{} case, add this:
            gatt.close();
            gatt = null;
            connectCallback = null;

**Comment by ccravens** [comment]
Since I'm getting an error in iOS I'm going to open up a new issues since I don't think these are related

**Comment by don** [comment]
This is one of the many disconnect problems that happens on some Android devices. Hoping #592 fixes it.
