### ISSUE TITLE
Indicate issue

### ISSUE THREAD

**Issue by shraddha1112** [don/cordova-plugin-ble-central#42]
Hello,
I am developing an application with Ionic Cordova. We have our custom eval kit. It has 6 characteristics which i can read and write. But I cannot register to indicate for particular characteristic. I am not getting success callback it is giving invalid action. 
'IndicateUUID':'xxxx',
  ble.indicate( device.id, UUIDs.ServiceUUID, UUIDs.IndicateUUID, indicateSuccessCallBack, failure);

Please help.

Regards,
Shraddha

**Comment by shraddha1112** [comment]
It seems indicate is not implemented in android? Is it so? 
I tried using startNotification for same but I cannot get notification as well. Not even for battery. 
Please help we are in phase of delivery for release. 

Regards,
Shraddha

**Comment by don** [comment]
Indicate is not implemented on iOS or Android yet. I'm working on this, but it might take a bit.

startNotification works on both iOS and Android. 

Use something like [nRF Master Control Panel](https://play.google.com/store/apps/details?id=no.nordicsemi.android.mcp&hl=en) to verify notification is enabled for your battery service (notification is optional.) 

Are you able to register for notifications for the battery service but just not seeing changes?

**Comment by shraddha1112** [comment]
Hello,
 I am getting battery service notification on anroid. But we want indicate. Will it take long time to do so? 

Regards,
Shraddha

**Comment by don** [comment]
`startNotification` supports notification and indication in version 0.1.6
