### ISSUE TITLE
Can't download. Link is broken.

### ISSUE THREAD

**Issue by jaean123** [don/cordova-plugin-ble-central#420]
When I try to install using 'cordova plugin add', I get an error. I think the link is broken. Please have it fixed soon. Thank you.

C:\Users\jaean\Google Drive\Research\robotApp>cordova plugin add cordova-plugin-ble-central
Error: Failed to fetch plugin git+https://github.com/Telerik-Verified-Plugins/Bluetooth-Low-Energy.git via registry.
Probably this is either a connection problem, or plugin spec is incorrect.
Check your connection and plugin name/version/URL.
Failed to get absolute path to installed module

**Comment by don** [comment]
It looks like your computer is trying to download from Telerik not from npm or github. Maybe there's a configuration on your computer or in your project. You might need to update your version of Cordova, Nodejs, or npm.

try `npm install -g cordova` to update cordova

You can also try installing the plugin from github `cordova plugin add https://github.com/don/cordova-plugin-ble-central`

![capture](https://user-images.githubusercontent.com/3133/27308185-51e1588e-551b-11e7-93e4-a6827522b100.PNG)
