### ISSUE TITLE
Read light and humidity parameters

### ISSUE THREAD

**Issue by mfeltre** [don/cordova-plugin-ble-central#423]
Hello everyone, is there any  way wich I can get those parameters from my SensorTag CC2650?

Thanks,

Matteo

**Comment by don** [comment]
@mfeltre yes, you will be able to read the light and humidity sensor from the CC2650.

Check out the [SensorTag User Guide](http://processors.wiki.ti.com/index.php/CC2650_SensorTag_User%27s_Guide) for how the BLE services work. 

For the [humidity sensor](http://processors.wiki.ti.com/index.php/CC2650_SensorTag_User%27s_Guide#Humidity_Sensor) you need subscribe for notifications on characteristic f000aa01-0451-4000-b000-000000000000, then write `new Uint8Array([1]).buffer` to f000aa02-0451-4000-b000-000000000000 to enable the sensor. The light sensor should behave in a similar way.

Take a look at the [Sensor Tag example](https://github.com/don/cordova-plugin-ble-central/tree/master/examples/sensortag) and [Sensor Tag CC2650 example]
