### ISSUE TITLE
response  data

### ISSUE THREAD

**Issue by janceymario** [don/cordova-plugin-ble-central#434]
Question Description: Hello, I have one question when I used this plug-in. After I send data to Bluetooth, Bluetooth will reply to me with some data. My question is how can I get the response data from Bluetooth? 
1.    function: Ble.write (device_id, service_uuid, characteristic_uuid, data, success, failure). 
Should I get the Bluetooth response data from the “success” callback? 
2.    Or should I use ble.read to get the response ?

**Comment by tiandongmao** [comment]
You can call ble.startNotification (device_id, service_uuid, characteristic_uuid, data, success, failure) before ble.write.

**Comment by don** [comment]
With Bluetooth LE the properties of the characteristic determine if you can read, write, or notify. Like @tiandongmao says, notifications are generally the most convenient way to get data from the peripheral back to the phone. You'll need to get more info about the peripheral to determine how to communicate with it. If there's no documentation, try connecting with LightBlue Explorer to see what's available.
