### ISSUE TITLE
when invoke ble.scan ,failure method callback

### ISSUE THREAD

**Issue by kitikousei** [don/cordova-plugin-ble-central#435]
adb log

07-27 00:45:16.338 18591 18664 E Adreno-GSL: <ioctl_kgsl_device_getproperty:830>: Either IOCTL_KGSL_DEVICE_GETPROPERTY 16 unsupported by kernel or 4 bytes is the wrong size
07-27 00:45:16.340 18591 18664 E Adreno-GSL: <ioctl_kgsl_device_getproperty:830>: Either IOCTL_KGSL_DEVICE_GETPROPERTY 16 unsupported by kernel or 4 bytes is the wrong size

android version 6.0.1 MXB48T

**Comment by kitikousei** [comment]
![wx20170727-010522](https://user-images.githubusercontent.com/3617913/28633865-c3fa4f52-7267-11e7-9fa0-d0e4655faaeb.png)

**Comment by don** [comment]
What data are you passing to scan? The first parameter should be a list of UUIDs. UUIDs should be 128 bit or 16 bit Strings.

    ble.scan(['FFE0'], success, failure);

Some Android devices can't filter when scanning. If that's the case try scanning for all devices by passing an empty list.

    ble.scan([], success, failure);
