### ISSUE TITLE
device discover

### ISSUE THREAD

**Issue by ls19491314** [don/cordova-plugin-ble-central#436]
Hello, thank you very much for you to bring such a good plug-in, when I use, ios phone has been connected in advance ble equipment, no broadcast, how can I scan to the current equipment has been connected? Thank you, you worked hard!

**Comment by don** [comment]
Right now there's *not* a good way to get a device that's already connected to your phone.

I've been thinking about having scan return connected devices. On iOS it could use `func retrieveConnectedPeripherals(withServices: [CBUUID])` and `BluetoothManager.getConnectedDevices` on Android.

**Comment by don** [comment]
Closing as duplicate of #379
