### ISSUE TITLE
Make this plugin hookable by other plugins

### ISSUE THREAD

**Issue by zabojad** [don/cordova-plugin-ble-central#442]
Hey @don !

I love your plugin and use it quite a lot recently!

I'm starting to have quite complicated Cordova apps that uses this plugin with several peripherals at the same time. It works great so far.

I'm however facing the need to hook some logic of the plugin with native code. Here is one example use case to illustrate that: I need to update through BLE the firmware of one of those peripherals and that task takes many loops and time to perform so it would be better to run it out of the webview but still be able to use the Bluetooth connexion made with this plugin.

I've seen an example of a cordova plugin that depends on another one to perform its job: the [cordova-plugin-file-transfer](https://github.com/apache/cordova-plugin-file-transfer/blob/master/doc/fr/index.md) depends on the [cordova-plugin-file](https://github.com/apache/cordova-plugin-file) through the use of the PluginManager API.

I was thinking that we could use the PluginManager API to be able to hook into cordova-plugin-ble-central from other plugins that would implement peripheral specific logic (in my example, the firmware update). I think this feature should allow to hook all PluginResult from cordova-plugin-ble-central (like notifications, read results, write results, etc...) before they are sent back to the webview so that they can be treated by those other plugins.

Would you accept a pull request that adds the possibility to hook your plugin native code or should I not bother work on a PR that you would anyway never merge :)?

Thanks in advance for your answer and again thank you for your work on this plugin so far!

**Comment by don** [comment]
@zabojad yes, I'll consider pull requests if you get a good version of hooks working.

For Nordic DFU @tomasbedrich has a [fork](https://github.com/fxe-gear/cordova-plugin-ble-central) that add an `upgradeFirmware` method. https://github.com/fxe-gear/cordova-plugin-ble-central It would be great to figure out how to have an UpgradeFirmware plugin that used this plugin for most functionality.
