### ISSUE TITLE
IOS: isEnabled, isConnected, connect,... Not firing on call

### ISSUE THREAD

**Issue by kaddyadriano** [don/cordova-plugin-ble-central#458]
Thank you for the plugin! Works well on android however I am having problems with IOS. isEnabled, isConnected, connect and maybe more functions are only being triggered when I slide up the 'quick options menu'. 
![Options Menu](https://thumb.ibb.co/dWtqrv/IMG_1541.jpg)

I am using iOS 10.3.3. Please let me know if there is a solution for the methods to fire when they are called without waiting on sliding up the menu! Thank you in advance!

**Comment by snow-dev** [comment]
Same problem here, and I should build fro production on Friday :(!

**Comment by kaddyadriano** [comment]
@don Anything about this issue?

**Comment by don** [comment]
@kaddyadriano I haven't had time to look into it. It would help if you could create the simplest possible app that duplicates the issue and share it via a GitHub.

**Comment by snow-dev** [comment]
Ok, tomorrow I can work on that example :).

**Comment by kaddyadriano** [comment]
@don I have created a test app that you can look at [BLE Test App](https://github.com/kaddyadriano/cordova-plugin-ble-central-test). Thanks in advance!

**Comment by kaddyadriano** [comment]
@don anything?

**Comment by kaddyadriano** [comment]
@don I have looked at the code and there is a deprecated constant https://developer.apple.com/documentation/corebluetooth/cbcentralmanagerstate it's being used inside cordova-plugin-ble-central/src/ios/BLECentralPlugin.m on line 51 - 56
It's also used in online 221 and 223 inside isEnabled method. There may be other places.
It was replaced by https://developer.apple.com/documentation/corebluetooth/cbmanagerstate
I hope that helps.

**Comment by kaddyadriano** [comment]
I have figure out what the issue was. Not the plugin but the CSP was missing ```gap:```. Here is what my CSP looks like:
```html
<meta http-equiv="Content-Security-Policy" content="default-src * 'unsafe-inline' file://* *; script-src 'self' 'unsafe-inline' 'unsafe-eval' *; font-src * data:; style-src 'self' 'unsafe-inline' *; media-src *;img-src 'self' data:; child-src * ; frame-src * gap: 'unsafe-inline'" />
```

**Comment by don** [comment]
@kaddyadriano thanks for the update. Nice work tracking down the missing `gap:` in the CSP.
