### ISSUE TITLE
BLE Enable / Disable Notifications

### ISSUE THREAD

**Issue by ccravens** [don/cordova-plugin-ble-central#460]
Would like to have a notification if Bluetooth is disabled or enabled while the app is in use.

**Example:**
While user is using the app, the user disables bluetooth on the phone. The app receives a notification from the cordova-plugin-ble-central plugin that bluetooth has been disabled.

While user is using the app, the user enables bluetooth on the phone. The app receives a notification from the cordova-plugin-ble-central plugin that bluetooth has been enabled.

**Comment by don** [comment]
@ccravens try [ble.startStateNotifications](https://github.com/don/cordova-plugin-ble-central#startstatenotifications). It should do what you need.

**Comment by ccravens** [comment]
@don Thank you for pointing that out! I don't know how I missed that in the docs
