### ISSUE TITLE
device title with umlauts

### ISSUE THREAD

**Issue by ruhl** [don/cordova-plugin-ble-central#462]
The user can change the device name of the ble-device.
If he enters umlauts, they will be displayed as unprintable characters.

As test, I entered "Büro" as name. It writes 66, 252, 114, 111 to the device.
If I read back the device name, I get 66, 65533, 114, 111.
So all characters are OK, but 'ü' changes from 252 to 65533.

I tested also with nRF Connect, showing me 66, 252, 114, 111 for the device name.
So the name is saved as it should be.
Only the reading fails.

**Comment by hervethouzard** [comment]
It seems the name is encoded in UTF-8 (to bytes are used for the "special" character.

**Comment by ruhl** [comment]
But the remote device can hold only 1 byte.
If I write to the device, it also writes only 1 byte.
And also if I check the name with another application, it shows the raw data with 1 byte (252).

So it seams that somewhere between the Android and the application the data are converted and 252 will became 65533.
I don't know what I could make or change to fix this.

**Comment by don** [comment]
@ruhl Can you check the value here using a Java debugger? https://github.com/don/cordova-plugin-ble-central/blob/155827ff192d0f87947971c7cbf6f23f0e46de5b/src/android/Peripheral.java#L99

I think @hervethouzard is right that this is a UTF-8 issue. If the value is OK in Java, need to figure out if it's the JSON Object, Cordova bridge, or JavaScript code mangling the chars.

**Comment by ruhl** [comment]
Do you have a hint for me how I could debug it?
I tried with LOG.d, but got no output.
I'm new to Ionic and web-applications.

I will try more tomorrow, thanks.

**Comment by don** [comment]
I think the easiest way is to run in Android Studio and set a breakpoint. Alternately you could add something like `LOG.d(TAG, "device.getName() " + device.getName());`

**Comment by ruhl** [comment]
With LOG.d I got no data, but with the debugger I can see the name as "B?ro" -> 66, 65533, 114, 111.
So it seems the error is behind device.getName().

**Comment by don** [comment]
That sounds like it's in the Android code. Does it happen on multiple Android devices or just one phone? I can try and duplicate this but it'll be a while before I get to it.

**Comment by ruhl** [comment]
I tested it on two phones with the same result.
I don't know if there would be any possible solution, but if you have time, perhaps you could check it.
Else I will take it as it is.

**Comment by don** [comment]
@ruhl I created a new BLE peripheral named "Büro" using [blePeripheral](https://github.com/sandeepmistry/arduino-BLEPeripheral) and when I called ble.scan and ble.connect the name looked ok on iOS and Android.

If you're writing the name to a characteristic from Javascript, it looks like your data was encoded incorrectly. Since Büro has an u umlaut it needs encode with utf-8, meaning you'll get 5 bytes [66, 195, 188, 114, 111] instead of 4 bytes [66, 252, 114, 111].

    var encoder = new TextEncoder('utf-8');
    var data = encoder.encode('Büro');
    console.log(data);
    // prints Uint8Array(5) [66, 195, 188, 114, 111]
