### ISSUE TITLE
dependency of cordova-plugin-compat deprecated

### ISSUE THREAD

**Issue by dimitriscsd** [don/cordova-plugin-ble-central#466]
If you try to install this plugin with the new cordova-android 6.3.0 it tells you that cordova-plugin-compat is not required anymore as the functionality is now part of the platform.

The suggestion on that plugins page is to include version 1.2.0 which should decide if it needs to be installed or not.

Please sort this out for ble central.

**Comment by ddugue** [comment]
Hey @don ,

I've create a simple PR: #483

**Comment by ddugue** [comment]
We can close this issue since the PR has been accepted
