### ISSUE TITLE
peripheral/advertiser mode

### ISSUE THREAD

**Issue by titoasty** [don/cordova-plugin-ble-central#49]
now that server mode is stable on android, it would be a great enhancement to add it

**Comment by don** [comment]
Peripheral mode exists for Android, but it's not necessarily stable or widely supported.

I think peripheral mode is different enough that it will be a different plugin rather than mixing with this one. I have some experimental code but nothing that can be published yet.

**Comment by titoasty** [comment]
Yes you are totally right about making another plugin.
I'm really interested and in need of it, so if I can be useful on this, I can help you for android and probably windows phone versions.

**Comment by apptum** [comment]
hey don, as I'm searching for a phonegap library to advertise/broadcast as a beacon (in background) - you are not by any chance working on something like that?

**Comment by don** [comment]
@apptum other things have been distracting me from the peripheral plugin so I don't have anything publishable yet. For advertising as a beacon you might try https://github.com/petermetz/cordova-plugin-ibeacon, although it might be iOS only for what you need.

**Comment by apptum** [comment]
@don thanks for the hint! Peters plugin is great, but it seems it's no longer in development and though it can advertise as beacon, it can't do so in background :( But hopefully he just pauses.

**Comment by don** [comment]
http://github.com/don/cordova-plugin-ble-peripheral

**Comment by apptum** [comment]
@don no way! Hail the Don!
