### ISSUE TITLE
ble.Connect connectFailure callback method not run when bluetooth is turned off

### ISSUE THREAD

**Issue by alanstallwood** [don/cordova-plugin-ble-central#492]
Hi,

I'm running android 8 on a Pixel C tablet. When bluetooth is turned off the ble.Connect connectFailure callback method is not run.

Found this in logcat which might be of relevance:
```
11-13 14:33:03.861  1422  1422 I GsaVoiceInteractionSrv: O received Intent { act=android.bluetooth.adapter.action.STATE_CHANGED flg=0x4000010 (has extras) }
11-13 14:33:03.865  1092  1357 E BluetoothMap:
11-13 14:33:03.865  1092  1357 E BluetoothMap: java.lang.IllegalArgumentException: Service not registered: android.bluetooth.BluetoothMap$2@47f7903
11-13 14:33:03.865  1092  1357 E BluetoothMap:  at android.app.LoadedApk.forgetServiceDispatcher(LoadedApk.java:1466)
11-13 14:33:03.865  1092  1357 E BluetoothMap:  at android.app.ContextImpl.unbindService(ContextImpl.java:1622)
11-13 14:33:03.865  1092  1357 E BluetoothMap:  at android.content.ContextWrapper.unbindService(ContextWrapper.java:697)
11-13 14:33:03.865  1092  1357 E BluetoothMap:  at android.bluetooth.BluetoothMap$1.onBluetoothStateChange(BluetoothMap.java:64)
11-13 14:33:03.865  1092  1357 E BluetoothMap:  at android.bluetooth.IBluetoothStateChangeCallback$Stub.onTransact(IBluetoothStateChangeCallback.java:55)
11-13 14:33:03.865  1092  1357 E BluetoothMap:  at android.os.Binder.execTransact(Binder.java:674)

```

No such issue exists on Pixel XL phone running android 8 or other android/ios devices.

**Comment by ddugue** [comment]
From what I can gather, it seems to be an issue with a bluetooth profile set up on the phone that listen to the intents and try to unbind an unexisting connection from the Context.

Follow up questions:
- Is there any other bluetooth app on the Pixel C?
- Does the dongle you are trying to connect support the Bluetooth MAP profile?
- What operations are you doing on the dongle before disconnecting?
- Do you have any bluetooth paired device to your pixel C (Car system, bluetooth audio, ...)

In any case, I do not think it is related to this plugin, but I would like to get to the bottom of this issue to learn more about all the weird Android behaviors. Especially if another bluetooth app can interfere with another bluetooth app functionality.

**Comment by alanstallwood** [comment]
Nothing else is using bluetooth
I'm not sure about MAP. We're using GATT to communicate.
The device periodically sends messages to the tablet every 30 seconds or less. Each message is acknowledged by the tablet. I'm turning bluetooth off on the tablet to simulate a disconnect.
Nothing else paired

**Comment by ddugue** [comment]
Since you are turning bluetooth off to simulate disconnection, how are you providing the disconnect callback?

When are you turning the bluetooth off? Before calling ble.disconnect or after calling ble.disconnect?

**Comment by alanstallwood** [comment]
The callback function is passed as the 3rd parameter to ble.Connect

ble.Disconnect isn't called at all.

**Comment by ddugue** [comment]
Oh, so it is in fact the connect callback error which is not called!

Instead of turning the bluetooth off on the tablet to simulate a bad connection, can you try turning off the bluetooth device?

**Comment by ddugue** [comment]
Alright,
So, _normally_ android should fire the disconnect event, but that implementation is firmware specific. It is entirely possible that the tablet firmware, upon disabling bluetooth, clear the whole memory linked to the bluetooth stack. Including the callbacks.

A solution for your app, would be to listen to the state notifications with `ble.startStateNotifications` and `ble.stopStateNotifications` and trigger your callback code when a connection is active and the bluetooth gets shutted down.

Meanwhile, that feature (triggering connection callback error, when disabling bluetooth) could be implemented in the plugin quite easily. I don't mind doing it, we just need to make sure it wouldn't cause any backward compatibility issue.

@don what do you think?

**Comment by don** [comment]
@ddugue using state notifications is a good workaround. I'm fine if you patch the plugin. There are some other disconnect problems with some devices. See #412 and others.

**Comment by Jatindersyall12** [comment]
@don 

I am facing connection callback issue. I want to connect two BLE devices with GATT server but below code say's it's already connected, but my devices never connected. Can you please help me out on this.

bluetoothGatt = device.connectGatt(
            this,
            true,
            object : BluetoothGattCallback() {
                override fun onConnectionStateChange(gatt: BluetoothGatt, status: Int, newState: Int) {
            
                    when (newState) {
                        BluetoothProfile.STATE_CONNECTED -> {
                            gatt.discoverServices()
                        }
                        BluetoothProfile.STATE_DISCONNECTED -> {

                            //deviceStatusListener?.onDisconnect()
                            //closeConnection()
                        }
                    }

Looking for your's valuable feedback soon.

Thanks Jatinder Syall

**Comment by peitschie** [comment]
Hi @Jatindersyall12,

Would you mind raising a new issue to discuss this?

Thanks!

**Comment by Jatindersyall12** [comment]
@peitschie created a new issue for this.
