### ISSUE TITLE
How to use UART of Linkitone

### ISSUE THREAD

**Issue by suvi-ngaige** [don/cordova-plugin-ble-central#496]
I am new to linkitone board. I want to communicate over uart using linkitone. I go through SDK, there is no example regarding this. So can anyone help with the basic code for UART to read and write the value.

**Comment by vietquocnguyen** [comment]
For read/notify, use `6e400003-b5a3-f393-e0a9-e50e24dcca9e` and for write, use `6e400002-b5a3-f393-e0a9-e50e24dcca9e`

**Comment by don** [comment]
Also check out https://github.com/don/cordova-plugin-ble-central/tree/master/examples/bluefruitle

See #495
