### ISSUE TITLE
startScanWithOptions is not working in background after some time

### ISSUE THREAD

**Issue by SatheeshKumarBalu** [don/cordova-plugin-ble-central#503]
**Device**: redmi Note 4 and Samsung model / Android 7.0
**Application**: Running in background always by Service
**Permission**: Bluetooth, Location service and Internet connection are enabled
**Issue**: In background I just stopping the scan and again starting scan after 30sec by using **startScanWithOptions**. but the scan was not started and it was not detecting any devices. In foreground its working fine.
**Reproduce**:  The same issue is happening in some other mobile model also many times. but the issue is not consistent. 
**Note**: No more than 2 other application are running in mobile while testing

**Comment by don** [comment]
@SatheeshKumarBalu so this is working on most devices but failing on a few? Are you seeing any errors in `adb logcat` or errors in the JavaScript console with chrome://inspect.

**Comment by SatheeshKumarBalu** [comment]
Thanks for your response @don . 
After few more testing we can consistently reproduce the issue in one scenario.

Application running in background -> screen locked -> keep the mobile ideal for 30min -> App logic just try to stop the scan and again start the scan after 30sec by using startScanWithOptions. after that the scan was not started and it was not detecting any devices.

The problem is I can't able to get any error so far, because the test case is like mobile in ideal condition. 
Generally Its working fine in background but **not working in mobile ideal state for 30min**.

**Comment by don** [comment]
I don't have an answer for this but we can talk about a solution if you track down the cause. Using the new  [ble.autoConnect()](https://github.com/don/cordova-plugin-ble-central#autoconnect) function be an alternate solution if you're scanning to connect to a device.
