### ISSUE TITLE
ble.connect not working on Android 7.1.1

### ISSUE THREAD

**Issue by mardugas** [don/cordova-plugin-ble-central#506]
I'm writing a small app to read measurements from a blood pressure device
(service 1810, characteristic 2A35).
It works fine on Android 4.4.
When installed on an Android 7.1.1. device, ble.startScan works ok (ACCESS_COARSE_LOCATION permission is granted & accepted by the user). But ble.connect doesn't work.
Any ideas? Thanks, Martin

**Comment by FLATT-Dev** [comment]
I have 2 identical Galaxy 3 phones. One has the latest kernel build, Oct 24 2017, and another is  Oct 16 2016. Connect works on the older phone but does not on the newer one.. I get the error "Peripheral disconnected" from the plugin. I have access to  BLE device firmware and I do not see it ever getting a GATT MTU exchange event or GATT connect event. I'm looking into it, will poist if I find anything

**Comment by zerox1212** [comment]
Anyone find out what the problem is? I was trying to avoid writing native apps for my simple BLE theromometer, but `onConnect: function(peripheral)` just returns `null`. `onError: function(reason)` is never called.

**Comment by paredesivan** [comment]
@FLATT-Dev in a samsung galaxy s3? that cell phone does not have version 4.3?

**Comment by paredesivan** [comment]
estuve mirando la documentacion de android y no menciona cambios en las versiones 7.0. el problema debe venir por otro lado

**Comment by FLATT-Dev** [comment]
@paredesivan, the Android version I have on this phone is 6.0.1. I  dug a little deeper found that  onConnectionStateChange callback returns status 133. Some posts online suggest putting the connection attempt  on a UI thread. Tried that and it did not help. Strangely, I have an identical phone where connection does work. So I'm befuddled

**Comment by zerox1212** [comment]
Eventually my BLE on Android stopped returning null to `onConnect` and started working. It seems like when I first installed PhoneGap Developer App and ran my app for the first time (I selected "Allow" on location) `onConnect` would return null. After I closed the app entirely and ran it again it is now working. For me it seems like an issue that only happens on the first run when you have to give permissions.

**Comment by paredesivan** [comment]
@zerox1212 maybe yes

**Comment by don** [comment]
I heard early versions of 7.0 and 7.1 had some problems but I haven't seen this. Does anyone have any stack traces or a way to reproduce this?

**Comment by mardugas** [comment]
Hi Don,
how can I generate a suitable stack trace ?

**Comment by don** [comment]
@mardugas connect your phone to your computer 
run `adb logcat` 
when you see an error cut and paste the relevant parts from the console

If you have [Android Studio](https://developer.android.com/studio/index.html) installed, you can run your app through Android Studio and filter to just show log messages from your app.

**Comment by mardugas** [comment]
Here is the stack trace (I hope I selected the relevant parts). Any help is appreciated.

BLEPlugin: action = startScanWithOptions
...
BluetoothGatt: onClientConnectionState() - status=133 clientIf=5 device=D6:26:D2:4C:07:D8
BLEService: Connect fail.

[logcat7.1 extractBT.txt](https://github.com/don/cordova-plugin-ble-central/files/1644715/logcat7.1.extractBT.txt)

**Comment by paredesivan** [comment]
function escanear(dispositivos, tiempoBusqueda) {

            console.log("entra en scanear");

            var defer = $q.defer();

            if (dispositivos == null) dispositivos = [];

            ble.scan(dispositivos, tiempoBusqueda, exito, falla);

            function exito(valor) {
                defer.resolve(valor);
                console.log("escaneados"+JSON.stringify(valor));
            }

            function falla() {
                defer.reject();
            }

            return defer.promise;

        }

esta es mi funcion de mi servicio y funciona bien

**Comment by don** [comment]
@mardugas I'm not seeing an error just the generic connection failure message with status 133 gatt error. Can you use other Bluetooth apps on this same phone to connect to the device?

**Comment by mardugas** [comment]
Other Bluetooth apps are working on the same phone (e.g. hands-free phone).
I could see the same error pattern (connection failure with BT) on a different smartphone (homtom, android 7)

**Comment by crizhon** [comment]
I'm facing the same problem with Moto Z 7.x, some devices work fine and others do not connect, but work fine in Samsung s4 Mini 4.4 and Samsung J5 6.1, any solution?

**Comment by don** [comment]
@crizhon there no easy answer. Try and restart the phone, or at least Bluetooth. The Bluetooth stack crashes on some devices. Enable the [Bluetooth HCI Snoop Log](https://blog.bluetooth.com/debugging-bluetooth-with-an-android-app) and debug in Wireshark.

I think these are device/os specific issues rather than issues with this plugin. If anyone is still having problem, please open a new issue and include the simplest example that causes the problem.
