### ISSUE TITLE
BleCentralPlugin.m 'NSInvalidArgumentException', reason: '-[NSNull isEqualToString:] 647

### ISSUE THREAD

**Issue by py12345** [don/cordova-plugin-ble-central#507]
Hi,
In findPeripheralByUUID function, after a disconnection, this function run with a null uuid. 
Maybe it is call when we test the connection of the device.
Thank you

**Comment by don** [comment]
@py12345 how do I reproduce this?

Connect to a device, disconnect, call connect with null?
