### ISSUE TITLE
Memory Leak?

### ISSUE THREAD

**Issue by luisenrike** [don/cordova-plugin-ble-central#508]
So, I made an ionic app and I was monitoring the memory usage in Android Studio when I discovered that the allocated memory was always increasing. The allocated memory starts increasing when this line of code runs: `this.ble.startNotification(device.id, this.service, this.characteristic).subscribe(() => { });`, as you can see, I'm doing nothing in the `subscribe` handler.

I don't know if that is the expected behavior or maybe there is a memory leak somewhere.

[Video](https://streamable.com/uptzl)

**Comment by don** [comment]
@luisenrike how many times are you calling start notification? Typically you call startNotification once per characteristic and keep the notification. This will use some memory. Is this causing your app to crash?

Can you provide me a simple app that demonstrates the leak?

**Comment by luisenrike** [comment]
Hi @don, thanks for your reply. 

I only call `startNotification` once. The app is not crashing, but, after a while, it will drain the battery and the phone will heat up. The BLE device is sending a lot of data every 100 ms, so, maybe this is normal.

I made a simple ionic app:

https://github.com/luisenrike/ionicbleapp

https://streamable.com/ns78j
