### ISSUE TITLE
why invoke gatt.writeDescriptor(descriptor) in registerNotifyCallback

### ISSUE THREAD

**Issue by NanYoMy** [don/cordova-plugin-ble-central#509]
hi don, i found sometime, after subscribing notification, no command could send to my BLE device successfully. then i find all the commands are blocked in the "command queue". the reason is because, when we start notification, it will invoke gatt.writeDescriptor(descriptor), if the callback onWriteDescriptor didn't comes, all command will never process.

**Comment by NanYoMy** [comment]
forget it，we had made some mistakes. I solve this problem! by the way, setNotifyValue in iOS will writeDescriptor by default.

**Comment by subratpalhar92** [comment]
make sure you are using write() instead of writeWithoutResponse(), this solved my issue on ios
