### ISSUE TITLE
BLE Scanning invokes cordova resume/pause events

### ISSUE THREAD

**Issue by vietquocnguyen** [don/cordova-plugin-ble-central#510]
For some reason when BLE is scanning, the pause/resume events are triggered. Also, while it is scanning and I leave the app, a second later, it brings the app to the foreground. I'm guessing so that it can do BLE stuff. 

Can anyone explain this behavior / a way for BLE to not trigger the pause/resume events?

```
document.addEventListener("pause", onPause, false);

function onPause() {
    // Handle the pause event
}
```

**Comment by don** [comment]
I'm not sure why Cordova does this.
