### ISSUE TITLE
Scanning in background (iOS)

### ISSUE THREAD

**Issue by twinsit** [don/cordova-plugin-ble-central#511]
I have an app where I need to scan for BLE devices. I need to know the RSSI of these devices, so that I know if the device is still in the allowed range. If not, then I have a warning inside the application.

On android this works like it should be, on iOs there is an issue.
When I go to the background, then I can't scan anymore. 

When I check the Core Bluetooth implementation docs I can see  "When the app The CBCentralManagerScanOptionAllowDuplicatesKey scan option key is ignored, and multiple discoveries of an advertising peripheral are coalesced into a single discovery event." Does this mean that I can't make it work like this?

And is there another way? I need to have always the latest RSSI. Unfortunately the devices are beacons, so I can't connect to them.

**Comment by don** [comment]
@twinsit since you're looking for beacons, you might try https://github.com/petermetz/cordova-plugin-ibeacon. On iOS beacons are part of CoreLocation and sometimes work better in the background. (It still can be slow.)

@crabbydavis background scanning on iOS is a pain ¯\_(ツ)_/¯
