### ISSUE TITLE
ble bond

### ISSUE THREAD

**Issue by amitvikram1985** [don/cordova-plugin-ble-central#526]
Hi,
I am using this plugin in one of my app which is  for both android and ios.
I have one issue regrading ble bond. I am not able to set bond because there is  no any function to set bond.

Please help me to set bond,This is important for  me.
Thanks in advance.

Amit.

**Comment by hermannle** [comment]
Hi,
I've got the same problem as Amit. Bonding is a crucial security feature for industrial applications. It decides whether to use this framework or not.

**Comment by don** [comment]
@amitvikram1985 if you try and access a characteristic that requires elevated encryption your phone should try and prompt you to begin bonding.

@hermannle if you need bonding for a project, I'm happy to talk. Features usually added when I need them for a customer's project or someone hires me to add them.

**Comment by don** [comment]
Bonding currently needs to happen outside of the app in Android. Android now has ble.bondedDevices() to get the bonded devices. I create new issue #605 to track bonding.
