### ISSUE TITLE
Read the RSSI for a connected device

### ISSUE THREAD

**Issue by manouBayi** [don/cordova-plugin-ble-central#53]
Hello,
I'm looking for a way to constantly get RSSI value of a ble device to make some distance-rssi approximation.

Thanks

**Comment by robrow** [comment]
Hi,
could you use the RSSI value stored in advertising packets?

**Comment by don** [comment]
This is possible. I need to add a new API call the looks something like https://github.com/don/BluetoothSerial#readrssi

**Comment by manouBayi** [comment]
ok , I'll try by adding 'BluetoothSerial '
      De : Don Coleman <notifications@github.com>
 À : don/cordova-plugin-ble-central <cordova-plugin-ble-central@noreply.github.com> 
Cc : manouBayi <bayi.camara@yahoo.fr> 
 Envoyé le : Jeudi 28 mai 2015 7h21
 Objet : Re: [cordova-plugin-ble-central] Read the RSSI for a connected device (#53)
   
This is possible. I need to add a new API call the looks something like https://github.com/don/BluetoothSerial#readrssi—

**Comment by don** [comment]
@manouBayi I don't think BluetoothSerial will help you. A new gerRSSI function needs to be added  to this plugin.

**Comment by manouBayi** [comment]
ok, thank you

      De : Don Coleman <notifications@github.com>
 À : don/cordova-plugin-ble-central <cordova-plugin-ble-central@noreply.github.com> 
Cc : manouBayi <bayi.camara@yahoo.fr> 
 Envoyé le : Mercredi 3 juin 2015 14h03
 Objet : Re: [cordova-plugin-ble-central] Read the RSSI for a connected device (#53)
   
@manouBayi I don't think BluetoothSerial will help you. A new gerRSSI function needs to be added to this plugin. —

**Comment by Andy-Donegan** [comment]
Hi,
I am now looking for a way to update the RSSI as well.

Found this link on SO would this be the correct way to go about and implement within the Plugin ?

I have to be honest I would not have a clue where to put this code, but if I am on the correct track I will give it  a go.

http://stackoverflow.com/questions/18625819/continual-bluetooth-le-signal-strength-on-android

if(newState == BluetoothProfile.STATE_CONNECTED) 
{
   TimerTask task = new TimerTask()
   {
      @Override
      public void run()
      {
         mBluetoothGatt.readRemoteRssi();
      }
   };
   Timer rssiTimer = new Timer();
   rssiTimer.schedule(task, 1000, 1000);
}

**Comment by mrAddy** [comment]
Do we have any idea on when this enhancement will be implemented, or any workaround to achieve it ?

**Comment by don** [comment]
There's no work-around, it just needs to be implemented. I don't have a current timeline to implement. This would be nice to have, but I'm probably not going to add it until one of my projects needs it.

**Comment by snowbreeze** [comment]
Can anyone please implement this

**Comment by snowbreeze** [comment]
I have implemented it on android.. dont have ios and wp

**Comment by don** [comment]
https://github.com/don/cordova-plugin-ble-central#readrssi
