### ISSUE TITLE
scan() and startScan(); doesn't work at all on either iOS or Android.

### ISSUE THREAD

**Issue by rooz121359** [don/cordova-plugin-ble-central#530]
Hello,

Thank you for this plugin. 

However, I can't seem to make this work at all!

I'm trying to use the following code to start a scan but I never see anything being scanned even though I know there are BLE devices only 10 cantemeters away of my app device!

Tried this:
```

ble.scan([], 5, function(device) {
    console.log(JSON.stringify(device));
}, failure);
```

and this:

```
ble.startScan([], 5, function(device) {
    console.log(JSON.stringify(device));
}, failure);
```

_Tried this on iOS 11.2 iPhone 6+ and Android 6 Alcatel Pixi 4._

I know the plugin is installed properly because I can run this successfully on both iOS and Android:

```
ble.isEnabled(
  function(){
    // Bluetooth is enabled
	console.log('Bluetooth is enabled');
  },
  function(){
    // Bluetooth not yet enabled so we try to enable it
    ble.enable(
      function(){
        // bluetooth now enabled
		console.log('bluetooth now enabled');
      },
      function(err){
        alert('Cannot enable bluetooth');
      }
    );
  }
);
```

I run the scan and startSca code from a click function like so:

```
$(document).on('click', ".letmepairBtn", function(){

ble.startScan([], 5, function(device) {
    console.log(JSON.stringify(device));
}, failure);

});
```

Is there something that i'm missing or this plugin is dead?

**Comment by rooz121359** [comment]
Okay, I seem to have made it work on iOS but still not scanning on Android.


I use this code which started working on iOS:



```
ble.isEnabled(
  function(){
    // Bluetooth is enabled
	console.log('Bluetooth is enabled');
	
	ble.startScan([], function(device) {
    console.log(JSON.stringify(device));
    }, function(){

    });
	
	
  },
  function(){
    // Bluetooth not yet enabled so we try to enable it
    ble.enable(
      function(){
        // bluetooth now enabled
		console.log('bluetooth now enabled');
      },
      function(err){
        alert('Cannot enable bluetooth');
      }
    );
  }
);
```

I have this in my config.xml file:

<plugin name="cordova-plugin-ble-central" source="npm" />

<preference name="pgb-builder-version" value="2" />
<preference name="phonegap-version" value='cli-7.1.0' />
<preference name="android-build-tool" value="gradle" />
<preference name="android-minSdkVersion" value="23" />
<preference name="android-targetSdkVersion" value="23" />

**Comment by rooz121359** [comment]
Anyone?

**Comment by don** [comment]
This sounds like an error in you application code. Look for errors in the log file with 'adb debug' and use chrome://inspect to find errors in the web view.

Try this sample app on your devices https://github.com/don/ble-scan

**Comment by rooz121359** [comment]
@don cheers don. appreciate the reply.

I will give that ago to see if that helps. Just out of interest, have you tried that code on both iOS and Android?

**Comment by don** [comment]
I haven’t run that example code lately but it was tested on iOS and Android. I regularly use other apps written with this plugin on both iOS and Android.
