### ISSUE TITLE
scan() and startScan(); runtime error on Android.

### ISSUE THREAD

**Issue by Kleinast** [don/cordova-plugin-ble-central#534]
Ionic Framework: 3.9.2
Ionic App Scripts: 3.1.8
Angular Core: 5.0.3
Angular Compiler CLI: 5.0.3
Node: 8.9.4
OS Platform: Windows 10
Navigator Platform: Win32
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.140 Safari/537.36

My code on ionic:
app.module.ts
```
import { BLE } from '@ionic-native/ble';

  providers: [
    BLE
  ]

```
home.ts
```
import { BLE } from '@ionic-native/ble';

constructor(
    private BLE: BLE
  ) {
  }

ionViewDidEnter() {
    this.BLE.startScan([]).subscribe(device => {
     console.log(JSON.stringify(device));
   });

   setTimeout(() => {
      this.BLE.stopScan();
    }, 5000);
  }

```

Did I do something wrong ? or is it a not normal it didn't work ?

Thanks in advance

**Comment by don** [comment]
You didn't provide any details about the error.
See the https://github.com/don/ionic-ble-examples for working Ionic examples.

**Comment by valenzuela21** [comment]
Hello Problem Scan  Bluetooth Ble Native 
![20180722_134522](https://user-images.githubusercontent.com/20249209/43048954-97e948ea-8db5-11e8-847b-693cdf97943d.jpg)
Ionic

**Comment by valenzuela21** [comment]
Problem with the image above can someone help me!
I followed all the steps to the letter and nothing.
https://don.github.io/slides/2017-07-20-ionic-madison/#/

**Comment by valenzuela21** [comment]
I am communicating communicating with Bluefruit LE - Bluetooth Low Energy (BLE 4.0) - nRF8001 Breakout - v1.0.
I will have problems with UUID services?
