### ISSUE TITLE
on startNotification we get always an ArrayBuffer with 2 bytes [1,0]

### ISSUE THREAD

**Issue by mburger81** [don/cordova-plugin-ble-central#537]
If we register a `startNotification` we get always on the fly a 2 byte ArrayBuffer which contains always [1, 0].

We use Ionic Native which should only wrap your cordova plugin.

If we register 5 times on the same GATT we get 5 times called the callback with this strange ArrayBuffer. I think this should not be a problem on Ionic and also  the devices do not an notification with that beacuse that would not make sense we register it many times on different timings and we get ALWAYS this data.
Is this a BUG or is this BLE standard, or do you have an idea?

**Comment by don** [comment]
@mburger81 my guess is that your peripheral sends 0x0100 when you start notifications. It's not a standard, probably just your device behavior. You could try using a Bluetooth app like LightBlue Explorer or nRF Connect and see if you get the same behavior.
