### ISSUE TITLE
write function not working for long string

### ISSUE THREAD

**Issue by mazedm80** [don/cordova-plugin-ble-central#538]
i cant send 6 or 7 letter with write function but when its long the bluetooth device not receiving anything...
but i can send those data from other serial softwere, any solution regarding this ?

**Comment by cairinmichie** [comment]
What ble device are you using? I had this issue with the esp because it registers a different receive event when the string is longer the 8 chars.

**Comment by mazedm80** [comment]
HM-10

**Comment by don** [comment]
For some hardware you need to break long messages into multiple writes.
