### ISSUE TITLE
Disconnect is a gamble game.

### ISSUE THREAD

**Issue by Domvel** [don/cordova-plugin-ble-central#539]
The disconnect function behaves completely randomly. The promise (callback) is a lie.
There are several states: (promise(then, catch) == callback(success, failed))

1. The function works as expected. connection / promise resolved. (ok)
2. Promise rejected. Cannot disconnect. But the devices are disconnected. (the disconnection was successfully, but the promise is rejected as 'cannot disconnect').
3. The primise resolved successfully. (success callback) but the connection still exists. Also the isConnected-Methos returns 'not connected'. 

btw: sometimes on the 2nd state (disconnected but failed callback) the first try of reconnection failed with error: '__zone_symbol__currentTask: null'. The second try is successfully.

issue request: 
fix the problem of the disconnect method. The feedback should be trusted. The promise / callback state should be correct. Tell the truth. Do not lie. No more empty promises. :)

issue priority: 
high - If a connection only resolved on the app side, but the peripheral stills connected. (also on successfully callback) the app cannot connect again. Because the peripheral is hidden for scanns while connected. Workaround: Go to the OS Settings and restart Bluetooth.

```ts
this.ble.disconnect(deviceId).then(
  () => console.log('Successfully disconnected.');
).catch(
  (error) => console.log('Cannot disconnect.');
);
```

devices: samsung galaxy tab active (android 5.1), Lenovo TB-8704F (android 7.1)
Ionic: core 4.4.0, ble: 4.5.3
Cordova: android: 6.3.0, ble: 1.1.4

**Comment by don** [comment]
Should be fixed by #592
