### ISSUE TITLE
Device Name Change No Updates

### ISSUE THREAD

**Issue by khjde1207** [don/cordova-plugin-ble-central#540]
We used this : 
ble.startScanWithOptions([], { reportDuplicates: true }) .subscribe(device=>{
console.log(device)
});
log : 
{"name":"GRACTOR0","id":"30:AE:A4:6E:DA:22","advertising":{},"rssi":-53}

After changing the name from the Arduino device to "GRACTOR50", send

cached data is still coming out.
log: 
{"name":"GRACTOR0","id":"30:AE:A4:6E:DA:22","advertising":{},"rssi":-53}

Device name is cached. 
![2018-02-27 10-09-24](https://user-images.githubusercontent.com/18232924/36705265-9116f268-1ba7-11e8-9fe5-d3737e65fc37.png)

**Comment by 1459726992** [comment]
I have the same problem 
Can you tell me how to solve it？
