### ISSUE TITLE
RSSI update on scan

### ISSUE THREAD

**Issue by mirkomancin** [don/cordova-plugin-ble-central#543]
Is it possible to update RSSI device info during scan without stop and restart scan? I read in the code that the list of peripherals is emptied before the scan (into `findLowEnergyDevices ` method). Is it possible to insert new option on scanWithOptions that select if or not empty this list?

**Comment by VolodymyrAndrushchak** [comment]
@mirkomancin 

According to the RSSI. You can use `readRSSI` [method](https://github.com/don/cordova-plugin-ble-central#readrssi). Also, the scan method returns an updated RSSI level of BLE devices.

In `scanWIthOption` you can set empty array or set UUID for scanning only specified devices.

**Comment by mirkomancin** [comment]
readRSSI works only if you are connected to device. Else, if I try to rescan and I try to connect to a device not yet found by the scan fails because it is not in the list of peripherals. I would have a method to refresh rssi of alla peripherals founded during scanning operation without connect to them

**Comment by VolodymyrAndrushchak** [comment]
@mirkomancin 
Okay
In my case, I use the `scanWithOption` and I get an RSSI from this method. I don't know where you use this plugin (I use on Android and iOS platform) but in my case, it works

**Comment by mirkomancin** [comment]
But the problem remain. Because if I have device at distance of 15m,
latency between scan and discovery is of few seconds. And if I try to
connect during this time, I receive an error because list not contain my
peripheral

Il 12 mar 2018 11:13, "VolodymyrAndrushchak" <notifications@github.com> ha
scritto:

**Comment by VolodymyrAndrushchak** [comment]
@markterrill 
which platform do you use?

**Comment by mirkomancin** [comment]
Android

Il 12 mar 2018 11:27, "VolodymyrAndrushchak" <notifications@github.com> ha
scritto:

**Comment by VolodymyrAndrushchak** [comment]
@mirkomancin 
I also had the same problem on Android. I don't think that it's possible to configure from a cordova level. 
I used  `connect` and `readRSSI` methods on Android. Yes, I also had the same latency. It also depends on the configuration of your ble devices. These devices send a signal periodically and you can reprogram you ble. 
I don't know if you use this plugin on iOS, but on this platform(iOS) it works perfectly.

**Comment by mirkomancin** [comment]
It is sufficient It is sufficient to don't empty the list of periherals
when starting the scan with a flag to be added in the options. I don't know
how to recompile this feature, else I have already write it into my code.

Il 12 mar 2018 11:37, "VolodymyrAndrushchak" <notifications@github.com> ha
scritto:

@mirkomancin <https://github.com/mirkomancin>
I also had the same problem on Android. I don't think that it's possible to
configure from a cordova level.
I used connect and readRSSI methods on Android. Yes, I also had the same
latency. It also depends on the configuration of your ble devices. These
devices send a signal periodically and you can reprogram you ble.
I don't know if you use this plugin on iOS, but on this platform(iOS) it
works perfectly.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/don/cordova-plugin-ble-central/issues/543#issuecomment-372264120>,
or mute the thread
