### ISSUE TITLE
notifications freezes for some ms 

### ISSUE THREAD

**Issue by paulrodz** [don/cordova-plugin-ble-central#546]
start notify freezes data for some ms  which leads to data loss and thus my graph is not being plotted correctly,.the BLE device has multiple values . Is there any work around. thanks

**Comment by don** [comment]
How do you determine it's freezing? Which part freezes startNotification or the callback?

You're missing data from notifications? Notifications aren't guaranteed, so it's possible the OS is dropping some if you're sending too many too fast. For iOS I've seen notifications dropped if they are sent faster than every 30 milliseconds.
