### ISSUE TITLE
How to get characteristic from successful connection to BLE by IOS?

### ISSUE THREAD

**Issue by kim0z** [don/cordova-plugin-ble-central#550]
Hi,
From the response of the connection from IOS to BLE I'm not able to find the characteristic id, any idea?  
screenshot of the response son of the connection:  
[https://ibb.co/mc9r2S](url)

**Comment by don** [comment]
The screenshot link doesn't work.

The [peripheral object](https://github.com/don/cordova-plugin-ble-central#peripheral-data) passed to the connection callback has the service and characteristic info.

Also, check out the example code https://github.com/don/cordova-plugin-ble-central/tree/master/examples

**Comment by kim0z** [comment]
I did used the service and characteristic info from the peripheral object passed to the connection, works.

thanks
