### ISSUE TITLE
make a URI string

### ISSUE THREAD

**Issue by logindharam** [don/cordova-plugin-ble-central#551]
I am using Nordic DFU device and how to make a uri string for 'upgradeFirmware' function

thanks in advance

**Comment by don** [comment]
I'm not sure. The upgradeFirmware is provided by a [fork of this plugin](https://github.com/fxe-gear/cordova-plugin-ble-central).

Based on @fxe-gear's [example](https://github.com/fxe-gear/cordova-plugin-ble-central#quick-example) it looks like you just pass a file url.

    var device_id = "BD922605-1B07-4D55-8D09-B66653E51BBA"
    var uri = "file:///var/mobile/Applications/12312-1231-1231-123312-123123/Documents/firmware.zip";

    ble.upgradeFirmware(device_id, uri, console.log, console.error);
