### ISSUE TITLE
Is the development dead?

### ISSUE THREAD

**Issue by Domvel** [don/cordova-plugin-ble-central#553]
The development seems to be dead. Maybe a organization or fork will help? In best case the official BLE plugin for cordova / ionic should be moved to a new active fork.

Sad to look at the stacking issues and pull-requests. There are so many problem with this software. In many cases, because it's obsolete or not clean implemented.
Please do not get me wrong. I am glad that this software exists. It is open source. But sad to see it dying.

**Comment by don** [comment]
Creating issues like this is not helpful.
