### ISSUE TITLE
startStateNotifications on iOS not working if connected to device

### ISSUE THREAD

**Issue by jake-freshinup** [don/cordova-plugin-ble-central#555]
I have a function that alerts me when bluetooth status changes, using startStateNotifications

Before I connect to a device, I can toggle my devices bluetooth on/off and the alert always fires showing me the current state.

Once I connect to a bluetooth device, if I disable my bluetooth I do not get any further notifications.  Also, I had placed an alert in the failure callback during connection and that doesnt seem to fire either.

**Comment by don** [comment]
I can not duplicate this. Try running this project https://github.com/don/ble-state-notifications/tree/issue-555 On my iPhone 7 with iOS 11.3 the app updates the Bluetooth state even when connected to a peripheral.

**Comment by subratpalhar92** [comment]
make sure you are using write() instead of writeWithoutResponse(), this solved my issue on ios
