### ISSUE TITLE
There is git <<<<<<< HEAD in version 1.1.7

### ISSUE THREAD

**Issue by almas** [don/cordova-plugin-ble-central#556]
BLECentralPlugin.m Line:286

**Comment by giladrom** [comment]
Plugins/cordova-plugin-ble-central/BLECentralPlugin/BLECentralPlugin.m:267:1: error: version control conflict marker in file
<<<<<<< HEAD
^
Plugins/cordova-plugin-ble-central/BLECentralPlugin/BLECentralPlugin.m:286:1: error: version control conflict marker in file
<<<<<<< HEAD
^
2 errors generated.

**Comment by don** [comment]
@almas Thanks for reporting this. Fixed and 1.1.8 is published.
