### ISSUE TITLE
Ionic 3/4 plugin

### ISSUE THREAD

**Issue by soesantos** [don/cordova-plugin-ble-central#557]
Hi bro,
Do have plan make plugin for support ionic 3/4 plugin....?

Very hard to implement to ionic 3/4 print qrcode now...

Thank you very much
GBU

**Comment by don** [comment]
@soesantos this plugin works with Ionic. The Ionic native call this plugin. https://ionicframework.com/docs/native/ble/

I have Ionic examples https://github.com/don/ionic-ble-examples that have been written with Ionic 3. They should work with Ionic 4.

**Comment by soesantos** [comment]
hi don,
i try to print QR code generated to ionic card div (red mark) this is Base64 String of Image  ,

i send code "write" to printer 
"
let PrintData = document.getElementById("SKU")
bluetoothSerial.write(PrintData, success, failure);
"
but the output on the printer is print the string of base64 image not print qr code picture
eg. 
![whatsapp image 2018-05-03 at 2 26 46 am 1](https://user-images.githubusercontent.com/38737763/39545046-23b42e42-4e7a-11e8-896c-8da4a4ceb8d8.jpeg)
![whatsapp image 2018-05-03 at 2 03 31 am](https://user-images.githubusercontent.com/38737763/39543962-d141d87e-4e76-11e8-902d-a8b0f2529f48.jpeg)

**Comment by don** [comment]
@soesantos the printer is printing the encoded image. You probably need to send a command code to have it print images. You might need a printer specific plugin like https://github.com/giorgiofellipe/cordova-plugin-datecs-printer

**Comment by laaaaanceeee** [comment]
Would you create a peripheral one?

**Comment by alejandrojcc** [comment]
Hi @soesantos, can you print qrcode?
