### ISSUE TITLE
Request MTU Size

### ISSUE THREAD

**Issue by Domvel** [don/cordova-plugin-ble-central#567]
Feature request for API method `requestMtu` [reference](https://github.com/develop-algoritma/cordova-plugin-ble-central#requestmtu)

This is an Android issue. For larger characteristics (>20 bytes) it is required that the developer request a higher MTU size. A write request must complete in one message. (MTU size > Characteristic Size + Meta)

### requestMtu

```js
ble.requestMtu(deviceId: string, mtuSize: number, [success], [failure]);
```

On iOS this is not required. It's a Android only feature for this plugin.

**Comment by Domvel** [comment]
@don Please merge and release. :)

**Comment by Domvel** [comment]
# Use Case

You want to send more than 20 bytes to a characteristic with more than 20 byte size? On Android?
Maybe this doesn't work and fails with Error 14 "Unlikely". 

Known issue: The data to write has to be match in one message. So the MTU size has to greater than the data to send / characteristic size. 
The default MTU size is 23 (20 bytes payload + 3 byte header). But the meta data length depends on different things. Whatever ... a easy calculation: Use the max. MTU size (e.g. 512) or your characteristic size + a hand full bytes. (For more information about this topic, ask the internet.) A exact MTU size does not matter in our (my) case.

Now you can call the MTU method after device connection like: 

```js
ble.requestMtu(this.device, 512, () => {
  console.log('MTU Size ok.');
}, error => {
  console.log('MTU Size failed.');
});
```

That's it. Happy writing.

**Comment by don** [comment]
Thanks for the pull request. I'll test and merge this week.

**Comment by tempestwf** [comment]
Hi

We are in need of this functionality. Any idea when it will be packaged into a release so we can point our package.json at it?

Thanks very much.

Will

**Comment by don** [comment]
@tempestwf planning on a release this week

**Comment by I-Connect** [comment]
Not sure if it is (always) needed but I have found a delay/sleep of 100 ms is needed within my app after requestMTU before executing other BLE reads/writes. Maybe only for larger messages...?

Also in general between other reads and writes? I have been struggling with this for multiple hours now and I found that using a sleep of 10ms after each BLE action resolves my issues.
This probably prevents BLE stack congestion...? 

Can you confirm if this is needed?

**Comment by vallettea** [comment]
I also needed to wait 100ms after MTU change otherwise no packets could be transfered
