### ISSUE TITLE
How to get connected device?

### ISSUE THREAD

**Issue by Lanseer** [don/cordova-plugin-ble-central#571]
I want to show the device with connected status, but i can not find a method, anyone can help?

**Comment by Domvel** [comment]
You have to store the connected device (device id or whole object). You can check the connection by the method `isConnected`. There is no feature to list all connected devices.

**Comment by Lanseer** [comment]
@Domvel  thanks for your replay.

**Comment by Domvel** [comment]
@Lanseer np. but please use this place only for bug reports and feature requests. Not for usage question. Use a forum for ionic, cordova or stackoverflow instead. And don't forget to close this issue. :)
