### ISSUE TITLE
How to monitor the connected device state?

### ISSUE THREAD

**Issue by Lanseer** [don/cordova-plugin-ble-central#572]
ble.isConnected method reports the connection status, but only once,I want to receive a notification when connection status changed every time, how to do it?

**Comment by Domvel** [comment]
Please read the [docs](https://github.com/don/cordova-plugin-ble-central/blob/master/README.md#connect). There you can read that the `connectFailure` callback is long running and also invoked if the connection lost / disconnects. (In ionic it's an Observable.)
For usage question, please use forums like ionic, cordova or stackoverflow. This is only a bug and feature tracker. :)

**Comment by don** [comment]
I updated the documentation for [isConnected](https://github.com/don/cordova-plugin-ble-central#isconnected) to make this clearer.

**Comment by Lanseer** [comment]
@Domvel  @don  thanks a lot,I will
