### ISSUE TITLE
Unable to start scan with multiples service UUIDs

### ISSUE THREAD

**Issue by lulumahot** [don/cordova-plugin-ble-central#573]
I try to start a scan on two service UUIDs on Android but the callback is never called.

If i try with only one UUID at a time it works fine.

Are you able to reproduce it ? 

Some logs for adb logcat : 

> 05-17 12:41:23.365 30029 30060 D BtGatt.GattService: registerClient() - UUID=f293edb3-8d2b-4d4f-a2a0-41d0a828c3b9
05-17 12:41:23.366 30029 30053 D BtGatt.GattService: onClientRegistered() - UUID=f293edb3-8d2b-4d4f-a2a0-41d0a828c3b9, clientIf=5
05-17 12:41:23.366 13008 17559 D BluetoothLeScanner: onClientRegistered() - status=0 clientIf=5 mClientIf=0
05-17 12:41:23.366 30029 30446 D BtGatt.GattService: start scan with filters
05-17 12:41:23.371 30029 30070 D BtGatt.ScanManager: handling starting scan
05-17 12:41:23.375 30029 30053 D BtGatt.GattService: onScanFilterEnableDisabled() - clientIf=5, status=0, action=1
05-17 12:41:23.375 30029 30053 D BtGatt.ScanManager: callback done for clientIf - 5 status - 0
05-17 12:41:23.375 30029 30070 D BtGatt.ScanManager: addFilterToController: 2
05-17 12:41:23.377 30029 30053 D BtGatt.GattService: onScanFilterConfig() - clientIf=5, action = 0 status = 0, filterType=2, availableSpace=44
05-17 12:41:23.377 30029 30053 D BtGatt.ScanManager: callback done for clientIf - 5 status - 0
05-17 12:41:23.377 30029 30070 D BtGatt.ScanManager: configureFilterParamter 500 10000 1 0
05-17 12:41:23.379 30029 30053 D BtGatt.GattService: onScanFilterParamsConfigured() - clientIf=5, status=0, action=0, availableSpace=12
05-17 12:41:23.379 30029 30053 D BtGatt.ScanManager: callback done for clientIf - 5 status - 0
05-17 12:41:23.379 30029 30070 D BtGatt.ScanManager: configureRegularScanParams() - queue=3
05-17 12:41:23.379 30029 30070 D BtGatt.ScanManager: configureRegularScanParams() - ScanSetting Scan mode=2 mLastConfiguredScanSetting=0
05-17 12:41:23.379 30029 30070 D BtGatt.ScanManager: configureRegularScanParams - scanInterval = 8000configureRegularScanParams - scanWindow = 8000
05-17 12:41:23.379 30029 30053 D BtGatt.GattService: onScanParamSetupCompleted : 0

**Comment by don** [comment]
This is an Android limitation. Android is looking for a device that has both UUID1 *and* UUID2.

I disagree with Android's implementation, but there's not way to change this. I think you need to scan once for each UUID.

**Comment by lulumahot** [comment]
I see you're using the old Android Bluetooth API and I know this is possible using the new one. Is there any reason you're using the deprecated API (other than compatibility) ?

**Comment by don** [comment]
> Is there any reason you're using the deprecated API?

Mostly because the plugin is has been around for a while and Cordova runs on really old Android. At some point I'll upgrade once Cordova drops KitKat support.
