### ISSUE TITLE
"Turn on Bluetooth to allow app to connect to accessories" IOS alert message

### ISSUE THREAD

**Issue by AlecMRogers** [don/cordova-plugin-ble-central#578]
The alert mentioned in the title can be turned off with the following change to line 42 of BLECentralPlugin.m:

    manager = [[CBCentralManager alloc] initWithDelegate:self queue:nil options:@{CBCentralManagerOptionShowPowerAlertKey: @NO}];

**Comment by don** [comment]
The code is working as designed. An enhancement would be to make dialog configurable by passing options to connect.

**Comment by don** [comment]
Duplicate of #174
