### ISSUE TITLE
Calling isEnabled/startStateNotifications on ios brings up a dialog asking the user to enable bluetooth (if bluetooth is off).

### ISSUE THREAD

**Issue by cairinmichie** [don/cordova-plugin-ble-central#580]
I would much rather control how the dialog looks/works, how do I disable this?

**Comment by don** [comment]
That is a problem the dialog is shown for isEnabled and startStateNotifications. It might be possible to skip the check for those two functions. The biggest problem with disabling the dialog is that there's no other legal way to send the user the the Bluetooth settings. Ideally this would be a configuration to enable/disable this. I'll look into this next week when I have more time.

**Comment by cairinmichie** [comment]
I created a pull request that shows how to disable it. I then used the [Cordova-open-native-settings](https://github.com/guyromb/Cordova-open-native-settings) plugin to open the iOS settings, and your plugin to open android settings.

**Comment by don** [comment]
@cairinmichie do you have iOS apps using [cordova-open-native-settings](https://github.com/guyromb/Cordova-open-native-settings) that have been approved for the store by by Apple?

**Comment by cairinmichie** [comment]
Yes.

**Comment by don** [comment]
Add showBluetoothSettings for iOS in #591 based on code from [cordova-open-native-settings](https://github.com/guyromb/Cordova-open-native-settings)
