### ISSUE TITLE
TAG the current master and update NPM package.

### ISSUE THREAD

**Issue by Domvel** [don/cordova-plugin-ble-central#588]
@don Please could you tag the current master (because the merge #568) and update the NPM package. Also the ionic native wrapper. 😃 👍

**Comment by don** [comment]
I'll try and get a release out soon. I haven't messed with the Ionic wrappers. I'd appreciate if you submit  a pull request to their repo with the new function.

**Comment by Domvel** [comment]
Me too. I have no experience how the workflow is for the ionic wrapper. But I could try to post a pull-request for the ionic-native/ble wrapper repo. It feels lika a looong way from a change in this repo to ionic. 🤔 I think the ionic wrapper needs the npm version of this plugin. Otherwise it's not consistent. I can't post feature changes without knowing the version. I can't add a new method which does not yet exist in the cordova plugin.

**Comment by don** [comment]
Released 1.2.0
