### ISSUE TITLE
How to connect to HM-10?

### ISSUE THREAD

**Issue by 00alkskodi00** [don/cordova-plugin-ble-central#589]
Hi i am noivce, how can i connect to HM-10 and how can i send string "s" and how can i get back data.
i dont now how i make thak 2 weeks whitout comunication, this working to scan:

(function () {
    "use strict";

    document.addEventListener('deviceready', onDeviceReady.bind(this), false);
    document.getElementById("b1").addEventListener('click', findDevice);

    function onDeviceReady() {
        // Obsluha událostí pozastavení a obnovení Cordova
        document.addEventListener( 'pause', onPause.bind( this ), false );
        document.addEventListener( 'resume', onResume.bind( this ), false );
        
        // TODO: Cordova je načtená. Tady můžete udělat všechny inicializace, které Cordova vyžaduje.
        var parentElement = document.getElementById('deviceready');
        var listeningElement = parentElement.querySelector('.listening');
        var receivedElement = parentElement.querySelector('.received');
        listeningElement.setAttribute('style', 'display:none;');
        receivedElement.setAttribute('style', 'display:block;');
    };

    

    
    function findDevice() {0
        console.log('Start scanning')

        // Start scanning. Two callback functions are specified.
        evothings.easyble.startScan(
            deviceFound,
            scanError)

        function deviceFound(device) {
            console.log('Found device: ' + device.getName())
            console.log(JSON.stringify(device.advertisementData))
        }

        // Function called when a scan error occurs.
        function scanError(error) {
            console.log('Scan error: ' + error)
        }
    }

})();

CONSOLE OUTPUT:
Found device: HMSoft

{"kCBAdvDataManufacturerData":"SE102uqy7So=","kCBAdvDataLocalName":"HMSoft\u0000\u0000\u0000\u0000\u0000\u0000\u0000","kCBAdvDataTxPowerLevel":0,"kCBAdvDataServiceUUIDs":["0000ffe0-0000-1000-8000-00805f9b34fb"],"kCBAdvDataServiceData":{"0000b000-0000-1000-8000-00805f9b34fb":"AAAAAA=="}}

i am novice in JavaScript...

**Comment by don** [comment]
Hi @00alkskodi00 this would be a better question for StackOverflow than entering as an issue here. The HM-10 does serial-like communication service over Bluetooth, so the [bluefruitle example](https://github.com/don/cordova-plugin-ble-central/tree/master/examples/bluefruitle) should be close to what you need. Note that the HM-10 service is ffe0. It probably uses ffe1 for both transmit and receive where the bluefruit/nordic code uses separate characteristics for transmit and receive.
