### ISSUE TITLE
ble.bondedDevices not work in Android

### ISSUE THREAD

**Issue by ikarownicacio** [don/cordova-plugin-ble-central#611]
Sorry if I wrote the wrong code but the code below on android does not work it does not return anything in the list of devices.

I'm testing in Phonegap App Developer

```
ble.bondedDevices(
  function(device) {
    alert(JSON.stringify(device));
  }, 
  function() {
    alert('Error');
  }
);
```

If I check if the bluetooth is active works perfectly, I do this to verify that the plugin has been installed right and is working
```
ble.isEnabled(
	function() {
		alert("Bluetooth is enabled");
	},
	function() {
		alert("Bluetooth is *not* enabled");
	}
);
```

I need to get a list of paired devices is there any example code on this?

PS: Sorry for the awful English, thank you.

**Comment by don** [comment]
@ikarownicacio this function should return BLE peripherals that are bonded with your phone. If you are not seeing any results, it's possible there is nothing bonded.

Try using [nRF Connect](https://play.google.com/store/apps/details?id=no.nordicsemi.android.mcp&hl=en_US). Scan for a device. Connect and bond to it. Disconnect and close nRF Connect.

Once you have a bonded peripheral, you should get results from ble.bondedDevices.
