### ISSUE TITLE
Disconnect detection is late. Set timeout time.

### ISSUE THREAD

**Issue by Domvel** [don/cordova-plugin-ble-central#615]
Currently a peripheral disconnect is detected after 20 seconds. When the peripheral disconnects for example by removed the power supply. It's a bit too long.

Is there are way to set the timeout time? Maybe the connect method could take a timeout time as argument. Or is this a fixed time of the android BLE API?

Maybe related to #425.

**Comment by don** [comment]
Unfortunately that 20 second delay is Android. I haven't seen any way to make it faster.

**Comment by Domvel** [comment]
I have read a few articles about that. The 20 seconds seems to be hardcoded in the Android source code. There are tickets about it [here](https://issuetracker.google.com/issues/37074926) and [here](https://issuetracker.google.com/issues/37119344). That's weak. I don't know if reflection will help.
