### ISSUE TITLE
remove cordova-plugin-compat dependency

### ISSUE THREAD

**Issue by camelwoo** [don/cordova-plugin-ble-central#617]
cordova-plugin-compat is deprecated, and could not install on Cordova 7, so suguested to remove this dependency.

**Comment by don** [comment]
The cordova-plugin-compat is only installed for older versions of Cordova. Some versions of Cordova print a confusing warning about cordova-plugin-compat not being installed, but this plugin should still be installed. 

If you're seeing something else please include the console output and platform details here.

**Comment by don** [comment]
No problem, it's a confusing message, I did the same thing.

I might be able to remove that plugin and have Cordova 6 users manually install it.

**Comment by don** [comment]
Fixed by #705
