### ISSUE TITLE
BLE drops connection intermittently

### ISSUE THREAD

**Issue by leydar** [don/cordova-plugin-ble-central#629]
[ble_hy6_1.log](https://github.com/don/cordova-plugin-ble-central/files/2290077/ble_hy6_1.log)
[ble_mg5_3.log](https://github.com/don/cordova-plugin-ble-central/files/2290078/ble_mg5_3.log)

Thank you very much for your work on the BLE plugin. 

I'm facing an issue with an Ionic app on a couple of mobiles that is probably device specific. I have an IOT device which sends a notification of a characteristic change every second. After about half an hour an Ionic/Cordova app on Android using the BLE plugin drops the connection. I've attached the logcat output. This happens frequently but not consistently  on both a Huawei Y6 Android 6.0 and a Moto G5 Android 7.0. I know the Huawei implementation of BLE is notoriously unreliable but it's actually pretty good when there is less ambient bluetooth activity. 

Both mobiles sometimes heat up during comms but will also drop the connection on occasions where they don't. I have access to modify the code on both the app and IOT side if you have any suggestions. On the IOT device it looks just like a dropped connection. It's definitely the app that is disconnecting. This works consistently well on an iPhone SE and Huawei P20. I've left both running overnight and found them still receiving data in the morning. 

I need communication to remain reliable for about two hours or a way of silently reestablishing the a lost connection. Sometimes when the connection is dropped bluetooth has to be switch off and back on in order to reconnect. And third party BLE scanners on the afflicted phone cannot see nearby BLE devices. I saw that you added a method to clear the command queue which might help resolve this.

The initial connection works well and I subscribe to a notify characteristic with ble.startNotification(deviceid, service, characteristic).subscribe(). What I really need is either a way around this, a method of better troubleshooting the issue or a reason why it's happening. If I can say certain devices, chipsets, versions, age or environment are known to adversely affect the connection and aren't recommended, while not ideal, I could work with that. Currently the best I can tell users is to try it and YMMV.

In the attached logs ble_mg5 is from the Moto G5 and ble_hy6 is the Huawei. In both files searching for "MICRODUMP" will find the dump just after the app crashes.

Ionic:
   ionic (Ionic CLI)  : 4.0.6 (/usr/local/lib/node_modules/ionic)
   Ionic Framework    : ionic-angular 3.9.2
   @ionic/app-scripts : 3.1.11

Cordova:
   cordova (Cordova CLI) : 8.0.0
   Cordova Platforms     : android 7.0.0

System:
   Android SDK Tools : 26.1.1
   NodeJS            : v10.4.1 (/usr/local/bin/node)
   npm               : 6.3.0
   OS                : Linux 4.15

Plugins:
cordova-android-support-gradle-release 1.4.4 "cordova-android-support-gradle-release"
cordova-plugin-ble-central 1.2.2 "BLE"
cordova-plugin-brightness 0.1.5 "Brightness"
cordova-plugin-compat 1.2.0 "Compat"
cordova-plugin-crosswalk-webview 2.4.0 "Crosswalk WebView Engine"
cordova-plugin-device 2.0.1 "Device"
cordova-plugin-file 6.0.1 "File"
cordova-plugin-ionic 5.0.3 "cordova-plugin-ionic"
cordova-plugin-ionic-webview 2.0.1 "cordova-plugin-ionic-webview"
cordova-plugin-splashscreen 5.0.2 "Splashscreen"
cordova-plugin-sqlite-2 1.0.4 "SQLitePlugin"
cordova-plugin-statusbar 2.4.1 "StatusBar"
cordova-plugin-whitelist 1.3.3 "Whitelist"

**Comment by don** [comment]
closing old issue, hopefully you found a solution
