### ISSUE TITLE
Upgrade rxjs to work on angular 6

### ISSUE THREAD

**Issue by untilbit** [don/cordova-plugin-ble-central#630]
I can't use this plugin with Ionic 4 & Angular 6 because angular uses v6 of rxjs and this plugin is using an older version v5.

Please update it for Angular 6. It works well with Ionic 3 & Angular 5.

**Comment by TomDemulierChevret** [comment]
All ionic native plugins have a v5.0.0-beta.x release to be compatible with Angular 6 and Ionic 4. ;)

**Comment by untilbit** [comment]
This issue was fixed with the release of Ionic 4.
