### ISSUE TITLE
Notification Ready State (Promise)

### ISSUE THREAD

**Issue by Domvel** [don/cordova-plugin-ble-central#635]
Is there a way to get a ready state on `startNotification`?

My case: 
1. Subscribe a notification. `startNotification`.
2. Directly behind 1. send a message to receive a notification. 
Problem: Sometimes the notification is not yet ready at this time.
Workaround: Implement a delay. A read request on the notification characteristic does not help in this case.

Solution: Get a ready state. In best case a callback / promise. 
Let me think aloud:

```ts
ble.startNotification(deviceId, serviceId, charId).then(theObservable => {
  theObservable.subscribe(value => {/*...*/});
});
```
Currently the `startNotification` method only returns a observable which emits `next` events on notification received. And the `error` event on problems. The `complete` event is not possible to use in this case. Because the `next` events will not work after observable is completed.
So my idea is to wrap it in a promise first. `myObservable` is the object which is currenctly directly returned on `startNotification`. 

Or we implement another method with returns a `Promise` for a characteristic. Resolved promises always emit the `then` method also after resolved a long time ago. 

```ts
ble.isNotificationReady(deviceId, serviceId, charId).then(() => console.log('yes'), () => console.log('No'));
```

Any other ideas?
Sorry, I talk about the ionic (angular) implementation / modern javascript / rxjs. But I think this doesn't really matter. It's also valid for this native javascript callback-based implementation.

Any questions?

**Comment by peitschie** [comment]
This has been addressed by https://github.com/don/cordova-plugin-ble-central/pull/903

In cases where the notification subscription needs to be ready, I'd recommend using `ble.withPromises.startNotifications(deviceId, serviceId, charId)`

Alternatively, passing `{ emitOnRegistered: true }` to the `ble.startNotifications` callback can be used to have an event emitted when the subscription is ready.

See https://github.com/don/cordova-plugin-ble-central/blob/f4c490da075ce371040c429e59577579edba2a1f/www/ble.js#L216-L227
