### ISSUE TITLE
ble write works correctly on Android 8 but not on 6 and 7

### ISSUE THREAD

**Issue by gertdejong** [don/cordova-plugin-ble-central#637]
I wrote an app that writes successfully to a characteristic on android 8. When testing on an android 6 or 7 phone I am able  to connect, but writing doesn't work. I get no errors, but the led thats supposed to start flashing on the peripheral doesnt flash.

What are the differences between android 8 and earlier versions that are causing this?

**Comment by gjdejong** [comment]
Is ionic an active platform or not? this is an essential issue and I get no response!

**Comment by untilbit** [comment]
Same issue here.

**Comment by don** [comment]
Maybe you need writeWithoutResponse? This should work on Android 6 and 7.
Closing old issue
