### ISSUE TITLE
disconnect on iOS does not repond

### ISSUE THREAD

**Issue by intersides** [don/cordova-plugin-ble-central#641]
I am using the same code for andorid and ios (ionic 4, Angular 6) but in the iOS version, the promise is never resolved when calling disconnect, although the peripheral gets disconnected.

The peripheral was previously connected using autoconnect. 

`this.blePlugin.isConnected(this.connectedPeripheral.getId()).then((response)=>{

        console.debug("isConnected ...");

        console.warn("about to call this.blePlugin.disconnect on ", this.connectedPeripheral);

        this.blePlugin.disconnect(this.connectedPeripheral.getId()).then((pluginMessage?:any)=>{
         .... THIS IS NEVER CALLED
          }

        }).catch(exc=>{
          console.error(exc);
           .... IS NEVER CALLED EITHER
        });

      }).catch(exc=>{
        console.error("exception on checking if is connected", exc);
      });`

**Comment by don** [comment]
I think this is a problem with way the ionic wrapper is implemented.
