### ISSUE TITLE
Scanning before connecting

### ISSUE THREAD

**Issue by fernandoSynetic** [don/cordova-plugin-ble-central#643]
The documentation indicates that it is possible to connect without making a previous scan. It does not work for me.

I do:
ble.connect("FF:5D:1A:36:AF:07", function(data){alert (JSON.stringify(data, null, 2));},function(){alert ("No connect");});
I always get a "No conect".

If I do a previous scan, it works.
Any ideas?
Thank you

**Comment by cairinmichie** [comment]
From my experience, you need to scan before using `ble.connect`. iOS doesn't support connecting to devices without scanning for them first. If you want to do this on android you can use `ble.autoConnect`.

**Comment by fernandoSynetic** [comment]
thanks for the reply.
I am using android. I have also tried autoConnect but it does not work either.

Has this functionality ever worked?
Thank you.

**Comment by Domvel** [comment]
I also wrapped the scan and connect methods in an own async method to scan before connect. On Android you can connect without a scan. But in my case, the device name I want, also comes with a scan. If I only connect without knowing the meta data but the MAC ID, the name does not appear in the discovered data of the connect method. So a scan before connect is recommended.

**Comment by don** [comment]
@fernandoSynetic I'm not sure why this isn't working for you. I suggest stepping through the debugger with Android Studio to see what's happening

https://github.com/don/cordova-plugin-ble-central#scanning-before-connecting
