### ISSUE TITLE
Receiving only one notification on Android but all of them on iOS

### ISSUE THREAD

**Issue by defc0n1** [don/cordova-plugin-ble-central#652]
On Android I use ble.requestMtu to increase MTU since the peripheral is sending more data. On iOS I use the same code without requestMtu and I am receiving all notifications as intended. I do however not receive more then one notification on Android which always has the same content: {"0":0,"1":0,"2":128,"3":0}

I tested with LightBlue and nRF Connect and with the same process it works on Android as well.

**Comment by untilbit** [comment]
The plugin only sends one notification/callback when scanning.

@don Could you improve this? thanks in advance

**Comment by don** [comment]
I don't recommend using requestMtu. This issue is really old, so closing for now. Re-open if it's still a problem.
