### ISSUE TITLE
ble.write does not work on Android 8.0

### ISSUE THREAD

**Issue by Shkoderk0** [don/cordova-plugin-ble-central#653]
hello. I am using simple code to write BLE characteristics in my Cordova app developed for iOS and Android:

	    data[0] = 0x01;
	    data[1] = 0x05;
	    data[2] = 0x00;
	    ble.write(devuid, serviceUUID, rxCharacteristic, data.buffer, function() {
		console.log("UID write successful");
	    }, function(err) {
		console.log("UID write failure", err);
	    });

when I run above code first time, I get error "write failure", next time write command is delayed until device disconnect. then I get same write failure again. before that moment I have no success or error message. 

issue happens only under Android 8.0 (Xiaomi Mi6 with BLE5). but works fine under iOS (iPad Air, iPad Mini 2) and Android 7.1.2 (Lenovo K3). at the same Android 8.0 phone other commands works fine. ble.scan, ble.connect and even notification subscriptions. issue is only ble.write (and probably ble.read)

remote BLE device I am trying to connect is Raspberry Pi Zero W with BlueZ 5.50. also tried to connect RPi3 with BlueZ 5.48 and got same issue

**Comment by droghio** [comment]
Not sure if it is related but I saw a similar issue where on Android 6/8 (all I had to test) if there was a write failure the command queue would be halted. This appears to be an issue in the device peripheral where if a GATT item is not defined the write and read calls return before cleaning the command completed flag.

Ensuring the command completed calls was issued helped resolve this issue. I am running into other unrelated problems but if I have time to clean this it up I'll issue a PR.

**Comment by untilbit** [comment]
Same issue here.

**Comment by untilbit** [comment]
@droghio can you sare your solution here?

**Comment by droghio** [comment]
@untilbit I will submit my code changes within the next few days. Can you give any more background to the nature of the issue you were encountering? Do you get the same error messages described in the original report?

**Comment by untilbit** [comment]
@droghio My issue is a little bit different but I'm curious to see your solution to this issue.

All operations I use on my app like scan, connect, read works on Android version 5 and up.

Except the write operation. It doesn't work on Android 6 and 7. It gets delayed until device is disconnected and neither I receive success nor error message.

**Comment by don** [comment]
Make sure the characteristic support writes and you don't need [writeWithoutResponse](https://github.com/don/cordova-plugin-ble-central#writewithoutresponse).

This is an old issue about old Android versions. Closing for now.
