### ISSUE TITLE
Clear device cache on iOS

### ISSUE THREAD

**Issue by FLATT-Dev** [don/cordova-plugin-ble-central#654]
In issue #587 Don said

> I don't think there's any solution in iOS other than having the user turn Bluetooth on and 
> off.

Can you  confirm that this is the only way and cannot be done programmatically on iOS?
(the clearDeviceCache API is not even implemented on iOS)
Thanks
Andy

**Comment by don** [comment]
I still don't think there's a way to clear the cache on [CBCentralManager](https://developer.apple.com/documentation/corebluetooth/cbcentralmanager?language=objc).
