### ISSUE TITLE
the first scan when i install app,the device scan twice every time

### ISSUE THREAD

**Issue by baijygo** [don/cordova-plugin-ble-central#659]
but i scan again, it is to normal ,every device appear once

**Comment by droghio** [comment]
Can you post sample code, and iOS or Android?

**Comment by don** [comment]
I think this is not an issue. You're probably seeing a scan packet and a scan response packet from the device. The scan response can contain additional data. The scan is not guaranteed to return unique devices, but your app can use the UUID or MAC address to get a unique list.
