### ISSUE TITLE
Can not connect with my device (headset)

### ISSUE THREAD

**Issue by marioshtika** [don/cordova-plugin-ble-central#663]
Hello I am trying to connect with my bluetooth device, which in the available devices in Android settings it looks like a headset (even it is not a headset).
![screenshot 2019-02-19 at 11 09 14](https://user-images.githubusercontent.com/3079663/53075511-04e18b00-34f6-11e9-89dc-0e6a5425b397.png)

Is there a way to connect with this type of bluetooth device?

**Comment by droghio** [comment]
Are you trying to a classic Bluetooth device or BLE, can you provide specs?

**Comment by marioshtika** [comment]
It's a glucometer and I think it is BLE (I am not sure though).
I think it is using a different [profile](https://developer.android.com/guide/topics/connectivity/bluetooth#Profiles).
It looks like it is using the "Headset" profile, instead of "Health Device" profile.

Could the usage of a "Headset" profile, be the reason why I can not connect using this plugin?

Thank you in advance

**Comment by marioshtika** [comment]
I just find out that the device I am using it has Bluetooth v3 and only supports serial communication but not HDP.
Can I use this plugin to communicate with my device?

**Comment by droghio** [comment]
Unfortunately no. BLE is only available on certain BT4+ devices. Bluetooth 3 is exclusively classic and not compatible with this library. Despite the naming similarity the two are completely different protocols. There should be a few serial terminal apps in the android store that will let you interface with the device.

**Comment by don** [comment]
On **Android** you can use [cordova-plugin-bluetooth-serial](https://www.npmjs.com/package/cordova-plugin-bluetooth-serial) if the device supports RFCOMM
