### ISSUE TITLE
get current MTU

### ISSUE THREAD

**Issue by phatpaul** [don/cordova-plugin-ble-central#666]
Can I read the value of the current MTU between central-peripheral?
I know I can request it, but how to confirm the actual value?

Why would anyone need that?
I want to send a large array ~4kB on any device whether it supports larger MTU or not.  I want to split it into the fewest chunks as possible (for performance).

- If MTU is 23 - default, then the transfer will still work, but performance may be low, as I will chunk the data in 222 x 20B packets (18B data and 2B header).  This chunking/un-chunking is done in JS.

- If MTU is larger, say 512, then the same chunking algorithm is used  but there are far fewer chunks (now 8 x 507B data, 2B header) to send which should improve performance.

**Comment by hervehobbes** [comment]
Usually this is done by reading a specific device characteristic, for example its firmware version.
