### ISSUE TITLE
Notifications stop in between.

### ISSUE THREAD

**Issue by himalayaahuja** [don/cordova-plugin-ble-central#675]
Hi don, 
I have a case in my project wherein the ble device pings the data after every 100ms and I am able to receive the data as well but after a random amount of time or data sets I stop receiving  any pings to the service I have subscribed to..
let's say the device was supposed to ping 5000 json records in total with record frequency of 100ms I stop getting data say after 1500 or sometimes 2000 records..

What could be the issue.?

Happy to provide with more information if needed.
Using this plugin in Ionic v3 app with ionic ble wrapper.

**Comment by don** [comment]
There's not enough info to tell. This is an old issue, I'm hoping you have it fixed by now.
