### ISSUE TITLE
Scan stops on some Android devices when screen is locked

### ISSUE THREAD

**Issue by tushe** [don/cordova-plugin-ble-central#676]
https://stackoverflow.com/questions/48077690/ble-scan-is-not-working-when-screen-is-off-on-android-8-1-0

**Comment by don** [comment]
I can't do much to work around Android limitations. What you're seeing makse sense if you're not passing a list of UUIDs to [ble.startScan()](https://github.com/don/cordova-plugin-ble-central#startscan). Hopefully passing services ids fixes this.

If not the scan code might need to be updated to use the new scan APIs.
https://github.com/don/cordova-plugin-ble-central/blob/7295e9e5d591e29db3dfbd23dac19b8240482619/src/android/BLECentralPlugin.java#L615
