### ISSUE TITLE
enable not prompting enable

### ISSUE THREAD

**Issue by jaksawesome10** [don/cordova-plugin-ble-central#677]
I have the following code

```
ble.enable(

function() {

document.getElementById("console2").innerHTML = "Bluetooth is enabled";

},
function() {
	
document.getElementById("console2").innerHTML = "The user did not enable Bluetooth";
	
}

);
```
When there is a success or failure it updates a paragraph element's innerHTML giving the status.  When I run my app using this code on my android device it returns The user did not enable Bluetooth without prompting to enable bluetooth.

**Comment by don** [comment]
**enable** only work on Android
You can try the example from the docs https://github.com/don/cordova-plugin-ble-central#enable
