### ISSUE TITLE
Ionic bitmap image printing works on IOS but not on Android

### ISSUE THREAD

**Issue by maxlee94** [don/cordova-plugin-ble-central#683]
Ionic3 connect to the thermal printer by using BLE.
Convert the image png to bitmap then post to ionic and print to thermal printer.
It works on IOS but print like nothing or lots of 'special character' show.

**Comment by don** [comment]
This sounds like an application specific issue. It's possible there's too much data for Android and you need to break it up in chunks. Generally iOS can handle larger characteristic lengths.
