### ISSUE TITLE
Read large data with startNotification

### ISSUE THREAD

**Issue by neumotngayem** [don/cordova-plugin-ble-central#686]
Hi I am using startNotification to get the data from characteristic, but It just return the ArrayBuffer with the length is 20, while my data is around 47 byte.

**Comment by Ariaal** [comment]
you can get data three times.  Low-power Bluetooth does not exceed at most each 20byte . by the way,how can you get data ? is using startNotification ? why i can not get my data ?where you uesd it ?

**Comment by Ariaal** [comment]
you can get data three times. Low-power Bluetooth does not exceed at most each 20byte . by the way,how can you get data ? Did you use startNotification ? why i can not get my data ?where you uesd it ? i uesd it when i sent my data ,but it does not matter.

**Comment by don** [comment]
Not enough info here to debug. It sounds like the characteristic length might be 20 bytes.
