### ISSUE TITLE
StartNotification Problem

### ISSUE THREAD

**Issue by FabioPuviani** [don/cordova-plugin-ble-central#687]
Hi,

Thank's for this great plugin.

On IOS 12, if i use startNotification, Xcode logged this error:
"Looking for 569A2000-B87F-490C-92CB-11BA5EA5167C with properties 16"

If i try tu put random parameters inside the function, startNotification use the error callback, as i aspected.

**Comment by Ariaal** [comment]
I also encountered this problem.
Tell me if you solve it!
Thanks!

**Comment by FabioPuviani** [comment]
No not yet, I think I'll switch to another plugin

**Comment by Ariaal** [comment]
Do you add  cordova-custom-config ?

**Comment by FabioPuviani** [comment]
No, but i don't need background notification

**Comment by Ariaal** [comment]
The displayed write was successful, but my device failed to accept and no data was passed.

**Comment by LuchoManto** [comment]
i added custom-config, but startNotification still fails. I don't get that error though. Every time i attempt to run startNotification, the failure function executes.

**Comment by don** [comment]
The characteristic needs to support notifications or indications in order for startNotification to work. The peripheral controls if the characteristic is read, write, notify, etc.
