### ISSUE TITLE
Error reading 000036f6-0000-1000-8000-00805f9b34fb status=1

### ISSUE THREAD

**Issue by eudovic** [don/cordova-plugin-ble-central#690]
Hi I have an error on 36f6 Characteritcs, and i`m trying to understand it for a lot of days without a success...

{"name":"EMERSON","id":"C4:A8:28:07:EE:7C","services":["1800","1801","1803","1804","1802","fee7"],"characteristics":[{"service":"1800","characteristic":"2a00","properties":["Read"]},{"service":"1800","characteristic":"2a01","properties":["Read"]},{"service":"1801","characteristic":"2a05","properties":["Indicate"]},{"service":"1803","characteristic":"2a06","properties":["Read","Write"]},{"service":"1804","characteristic":"2a07","properties":["Read"]},{"service":"1802","characteristic":"2a06","properties":["WriteWithoutResponse"]},{"service":"fee7","characteristic":"36f5","properties":["Write"]},{"service":"fee7","characteristic":"36f6","properties":["Read","Notify"]},{"service":"fee7","characteristic":"feff","properties":["Write","Notify"],"descriptors":[{"uuid":"2902"}]}]}

 this.ble.read("C4:A8:28:07:EE:7C", "fee7","36f6").then(
    successread => console.log(successread),
    errorread => console.log(errorread)
  ).catch(errorread=>{ 
    console.log(errorread);
  });

Return me  :
 Error reading 000036f6-0000-1000-8000-00805f9b34fb status=1
bluetooth.ts:187

Can anyone helpme?

**Comment by don** [comment]
Try reading the characteristic with an app like LightBlue or nRF Connect. If that works, I'd write the simplest app without Ionic to read the characteristic. Once that's working, go back to your Ionic app.
