### ISSUE TITLE
read() Returning Empty Buffer

### ISSUE THREAD

**Issue by LeoSaucedo** [don/cordova-plugin-ble-central#692]
Hello,

I've been trying to use this plugin with Ionic 4 (Cordova v 5.0.3) and debugging on Android 9.0 using ADB. I am able to scan for the device and connect to it just fine, and am able to read all of its services and characteristics.

However, when I try to read a characteristic, I am getting an empty ArrayBuffer:
```js
this.ble.read(deviceId, serviceId, characteristicId).then((data) => {
    alert(JSON.stringify(data));
}, error => {
    alert(JSON.stringify(error));
}
```

This code returns an alert that displays `{}`, meaning the success callback is triggered and an ArrayBuffer object is being returned, but it is empty. I know that this characteristic has data, because on the same device I am able to connect using [A BLE Terminal App](https://play.google.com/store/apps/details?id=de.kai_morich.serial_bluetooth_terminal&hl=en_US).

What could be happening here, or what steps should I try to take in order to debug this issue?

Thank you.

EDIT: I've gone ahead and checked the logcat, and it looks like the correct Read command is being called, and the correct characteristic is as well. There is information on that characteristic as seen from other BLE apps, I just don't know why I'm not able to receive it.

**Comment by nickcom** [comment]
did you find the reason for this?

**Comment by butlet** [comment]
did u find the reason for this?
