### ISSUE TITLE
No api to read descriptor of characteristic

### ISSUE THREAD

**Issue by PeacePan** [don/cordova-plugin-ble-central#70]
I want to read the Characteristic Presentation Format Descriptor(0x2904) of Battery Level(0x2A19).

But there no any methods to read descriptor.

**Comment by don** [comment]
There's no API for descriptors at this time. It would be a nice enhancement in the future.

**Comment by PeacePan** [comment]
I got it.
Thank for your response.
This is a good plugin.

**Comment by dnat112** [comment]
Hello,
I also would really like the ability to read and write to a descriptor. Is anyone currently working on this? I would be happy to work with someone to get this feature implemented.
Thanks.

**Comment by don** [comment]
No one is working on this. Reading descriptors would be nice. What are your use cases for writing descriptors?

**Comment by drewcovi** [comment]
I'm in need of this, and have used it extensively in the evothings plugin. It's extraordinarily helpful to add context to a characteristic value. consider it metadata for any given property. otherwise there's no graceful way to establish range, human readable label for the value, etc.

**Comment by don** [comment]
See #111
