### ISSUE TITLE
[Question] i want all dectected devices info

### ISSUE THREAD

**Issue by Alyssa-aly** [don/cordova-plugin-ble-central#701]
Hi, I want to do a beacon scan, so I keep scanning like a beacon regionning .
Beacon is detected in plugin ios log (plugin log is ‘discovered’), But sometimes for my Cordova(ionic4).(my log ‘found’)

Most are not sent.
10 times for ios(logs in discovered), once for my cordova(my log ‘found’)).

I want to get all beacons like plugin.
I need to keep scanning altbeacon like ibeacon in ios.
What should I do?
It's the same with startscanwithoption().

`2019-09-20 20:35:57.192808+0900 MyAPP[748:82680] Discovered {
    advertising =     {
        kCBAdvDataIsConnectable = 0;
        kCBAdvDataManufacturerData =         {
            CDVType = ArrayBuffer;
            data = "GAG+rAAAR2FzX0RldGVjdG9yAAD/////xf8=";
        };
    };
    id = "C3147AED-E8CE-E3C3-A5E9-EF1AFFBC4F88";
    rssi = "-42";
}

2019-09-20 20:35:57.200193+0900 MyAPP[748:82680] Found {
  "id": "C3147AED-E8CE-E3C3-A5E9-EF1AFFBC4F88",
  "rssi": -42,
  "advertising": {
    "kCBAdvDataIsConnectable": 0,
    "kCBAdvDataManufacturerData": {}
  }
}

2019-09-20 20:35:57.201083+0900 MyAPP[748:82680] advertising Device2-2
2019-09-20 20:35:57.203545+0900 MyAPP[748:82680] advertising Device3 1801beac00004761735f4465746563746f720000ffffffffc5ff`

the logs are looks like this.

Most of them are just Discovered logs .

I am developing ios.

`Ionic:

   Ionic CLI                     : 5.2.5 (/usr/local/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.7.4
   @angular-devkit/build-angular : 0.801.3
   @angular-devkit/schematics    : 8.1.3
   @angular/cli                  : 8.1.3
   @ionic/angular-toolkit        : 2.0.0

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : android 8.1.0, ios 5.0.1
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 4.1.1, (and 17 other plugins)

Utility:

   cordova-res : 0.6.0 
   native-run  : 0.2.8 

System:

   ios-deploy : 1.9.4
   ios-sim    : 8.0.2
   NodeJS     : v12.8.1 (/usr/local/Cellar/node/12.8.1/bin/node)
   npm        : 6.10.3
   OS         : macOS Mojave
   Xcode      : Xcode 10.3 Build version 10G8

Alyssaui-iMac:gas-detector-v41 alyssa$ `
its my ionic info.

**Comment by don** [comment]
This would be a better question for StackOverflow. For beacons on iOS you really need CoreLocation, not CoreBluetooth. Try cordova-plugin-ibeacon.
