### ISSUE TITLE
How to retrieve the value weight of a characteristic weight measure?

### ISSUE THREAD

**Issue by didi110296** [don/cordova-plugin-ble-central#702]
Hello,
I have an embedded hardware that send to weight characteristic two values according to the ble gatt documentation :
`uint8_t flags` (the measurement unit) 
`uint32_weight` (the weight value)

With tools likes 'BLE Scanner' on android i can read the value correctly, but in my angular project with ble, i don't know how to read the weight value correctly.

I've tried to use that for read the weight but that don't work

`this.ble.startNotification(peripheral.id, '181D', '2A9D').subscribe(
      (buffer: ArrayBuffer) => {
        var data = new Uint32Array(buffer);
        this.weight.next(data[0]);
      }
    );`

I think i have to read `uint8_flags` and `uint32_weight` separatly.
Can you help me please?

Thanks.

**Comment by don** [comment]
This would be a better question for StackOverflow.

With this plugin, you get the data for the characteristic as an ArrayBuffer. Typically you need to convert it to a Uint8Array and write a function to parse the bytes based on the spec. Unfortunately many of the characteristics in the spec not as straightforward as I'd like. I think you need read the bit flags to determine pounds or kilograms. Then get the uint16 value for the weight and divide it by the factor to convert to lbs or kg.
