### ISSUE TITLE
Support for requestConnectionPriority API

### ISSUE THREAD

**Issue by vamshik113** [don/cordova-plugin-ble-central#703]
Hi Don,
For Android level 21 we have an option to set Connection interval in the form of Connection priority. If this feature could be added in the plugin it would be great...

**Comment by don** [comment]
@vamshik113 I'd consider a pull request for [requestConnectionPriority](https://developer.android.com/reference/android/bluetooth/BluetoothGatt.html#requestConnectionPriority(int)). I'd imagine the implementation would look similar to [requestMtu](https://github.com/don/cordova-plugin-ble-central#requestmtu)

**Comment by vamshik113** [comment]
Hi Don, I created a pull request for this feature. I have tested these changes locally using nordic sniffer and it worked. Pull request number **#714**

**Comment by don** [comment]
Fixed in #714
