### ISSUE TITLE
Support Android 2.2 and IOS13 ?

### ISSUE THREAD

**Issue by Rebaiahmed** [don/cordova-plugin-ble-central#709]
Hello, We have a point to choose between ionic and native implementation and one of the client requirement is the app supports Android 2.2 and newest versions and support IOS13

**Comment by dpetropoulos-lemco** [comment]
Bluetooth Low Energy (BLE) did not exist and is not supported on Android below v4.3 (API level 18)

[https://developer.android.com/guide/topics/connectivity/bluetooth-le](https://developer.android.com/guide/topics/connectivity/bluetooth-le)

This is valid for native implementation and Ionic, Cordova or any other. Your client must be informed that there are no Android pre v4.3 BLE compatible devices. 

From my experience, for widespread compatibility you need to target Android v5.1 and above as BLE implementation on Android between v4.3 and v5.0 varies. Hardware manufacturers having made substantial modifications to Android core, have caused BLE implementation on Android v4.3-5.0 to be buggy, botched and unreliable.

As for iOS 13, I cannot tell you anything yet as I have no experience on that.
