### ISSUE TITLE
No code for bluetoothSerial.clearDeviceDiscoveredListener()

### ISSUE THREAD

**Issue by sammy00747** [don/cordova-plugin-ble-central#719]
Hi!

Seems like although the usage for bluetoothSerial.clearDeviceDiscoveredListener() is present in the API docs, there seems to be no existing function definition for the same.

A quick solution is appreciated.

Thanks in advance.

**Comment by sammy00747** [comment]
I had to 'literally' write these lines in /node_modules/@ionic-native/bluetooth-serial/ngx/index.d.ts, after "setDeviceDiscoveredListener(): Observable<any>;":

/**
     * Clears notify callback function registered with setDeviceDiscoveredListener.
     * @returns {void}
     */
    clearDeviceDiscoveredListener(): void;

closing the issue, and waiting for these changes to be implemented.

**Comment by sammy00747** [comment]
Sorry to say but this issue is still not solved. Please look into it.

**Comment by don** [comment]
@sammy00747 it sounds like that code is missing from the Ionic Native wrapper, not this plugin.

**Comment by sammy00747** [comment]
Thanks for your response @don!! I would look into this.
