### ISSUE TITLE
Scanning for services doesn't work

### ISSUE THREAD

**Issue by ragcsalo** [don/cordova-plugin-ble-central#721]
I've tried:
`ble.startScan(services, success, failure);`
and also:
`ble.startScanWithOptions(services, options, success, failure);`
but if I use the services filter, no devices are discovered...

For services I tried both ["AAAA"] and ["0000aaaa-0000-1000-8000-00805f9b34fb"] but none of them worked. Is the service filter working at all?

**Comment by don** [comment]
Try scanning with and empty array for the services list []. See if it finds the device and UUID you're looking for. It's possible your peripheral wasn't advertising. Some Android devices are finicky about 16 vs 128 bit UUIDs. I try and use the 128 bit UUIDs everywhere.
