### ISSUE TITLE
Printer write response not coming

### ISSUE THREAD

**Issue by kalemayur8** [don/cordova-plugin-ble-central#723]
Hi Don,

Thanks for such good plugin, I have been using this since some time. I am facing one issue during write operation on printer.

does write success function returns response also ? if no then what is the way to collect printer response.

I tried bte.startNotification before bte.write which collects data byte by byte and difficult to understand. 

Appreciate your quick help

**Comment by natestone** [comment]
You need to convert the byte array to a string to read it.  Otherwise, it sounds like you're on the right track.  Here's a sample snippet.

`  bytesToString(buffer) {
    return String.fromCharCode.apply(null, new Uint8Array(buffer));
  }`

**Comment by kalemayur8** [comment]
We are sending multiple lines of data to printer in Synchronously , the notification method take huge time to receive this data byte by byte and hard to understand which response is of which write operation. Is there any better way ?

**Comment by don** [comment]
I don't know. This plugin is just providing the communication layer, you'll need to work out the device API with the printer manufacturer. If you can find and existing app that works with the printer, use Wireshark and a bluetooth sniffer to record the traffic to see what they are doing.
