### ISSUE TITLE
ionic3 ble ble.write() not work

### ISSUE THREAD

**Issue by 18487208910** [don/cordova-plugin-ble-central#732]
ionic3 ble  and use ble.write() to print data,this function successcallback 'ok',But the printer don`t work

**Comment by don** [comment]
This library just handles BLE. You're getting success from write() your data is probably written to the characteristic.

If your printer isn't working, there may be additional configuration or formatting. Stackoverflow would be a better place for this issue. Post details about the printer make and model, post some of the code you're using. Hopefully someone familiar with that printer can help.
