### ISSUE TITLE
Invariant Violation: Native module cannot be null

### ISSUE THREAD

**Issue by PomegranateApps** [don/cordova-plugin-ble-central#736]
I'm trying to add event listeners but I'm getting the following error.
`Invariant Violation: Native module cannot be null`

This is my code.
```
import { NativeModules, NativeEventEmitter } from 'react-native';
const BleManagerModule = NativeModules.BleManager;
const bleManagerEmitter = new NativeEventEmitter(BleManagerModule);
```

**Comment by don** [comment]
Are you sure you have the right repo? I don't recognize this code or that error.
