### ISSUE TITLE
iOS Native BLE Authorization Dialog Shows Immediately On First-Time Startup

### ISSUE THREAD

**Issue by jospete** [don/cordova-plugin-ble-central#739]
On a fresh app install when using this plugin, the native iOS dialog for Bluetooth Authorization shows up immediately on plugin load ("This app would like to use Bluetooth ... Don't Allow / OK").

This is because the plugin initializes the CBCentralManager immediately in the initialize() callback.

Proposed fix for this can be found here:
https://github.com/don/cordova-plugin-ble-central/pull/735

**Comment by aparraga** [comment]
This is because in the iOS project plist the plugin appear with load=auto
Author: could you please remove this attribute, because it's better to let the user know why the app needs the bluetooth with an splash or whatever BEFORE asking for that permission.
