### ISSUE TITLE
'phonegap' is not recognized as an internal or external command, operable program or batch file.

### ISSUE THREAD

**Issue by ZebNZ** [don/cordova-plugin-ble-central#740]
Hi all,

I am new to PhoneGap and am trying to install the BLE Plugin!

if I run this command in the CLI:
`phonegap plugin add cordova-plugin-ble-central` 
I get this error:
```
'phonegap' is not recognized as an internal or external command,
operable program or batch file.
```

What am I doing wrong?

Thanks,

Zeb

**Comment by ZebNZ** [comment]
......also do you need Node.js installed

**Comment by don** [comment]
You need to have PhoneGap or Cordova installed. I recommend Cordova. Check out the getting started guide https://cordova.apache.org/#getstarted

**Comment by ZebNZ** [comment]
Hi @don,

**I currently have "Phonegap" installed.**

I am running this command in the Windows CLI:
`phonegap plugin add cordova-plugin-ble-central
`
I get this error:
```
'phonegap' is not recognized as an internal or external command,
operable program or batch file.
```

What am I doing wrong?

Thanks,

Zeb
