### ISSUE TITLE
unrecognized selector ios

### ISSUE THREAD

**Issue by tjtritonwear** [don/cordova-plugin-ble-central#741]
I've added stacktrace info from crashlytics (iOS 13.3.1 (17D50) iPad Pro (10.5-inch))

Fatal Exception: NSInvalidArgumentException
-[CBService value]: unrecognized selector sent to instance 0x2823cb880

CBPeripheral+Extensions.m - Line 195
-[CBPeripheral(com_megster_ble_extension) serviceAndCharacteristicInfo:] + 195

CBPeripheral+Extensions.m - Line 70
-[CBPeripheral(com_megster_ble_extension) asDictionary] + 70

BLECentralPlugin.m - Line 574
-[BLECentralPlugin peripheral:didDiscoverCharacteristicsForService:error:] + 574

CoreBluetooth
(Missing)

UIKitCore
(Missing)

main.m - Line 32
main + 32

libdyld.dylib
(Missing)

**Comment by don** [comment]
I'm not sure what to do with this. Did this happen once? Does it happen all the time? Can you provide a simple app that duplicates the problem?

**Comment by tjtritonwear** [comment]
Well for starters you're not even checking if didDiscoverCharacteristicsForService is being called from an error, and are just proceeding as if any time that callback is fired it's a good situation.  You're probably going to want to handle the scenario that CoreBluetooth wasn't able to discover the services.

**Comment by don** [comment]
> didDiscoverCharacteristicsForService is being called from an error
That's a good catch. I'd appreciate a pull request for the fix.
