### ISSUE TITLE
Corrupted messages sent and received

### ISSUE THREAD

**Issue by andistancu** [don/cordova-plugin-ble-central#743]
Hi,

I am using your Chat example to test this library.

I am unable to make this run properly. I can't describe this any better, but the conversion to bytes and the reverse seems to not work as intended.

The "Hello" message arrives as "l �Zr⸮FK`&⸮Γ⸮J#@#x9]�5⸮=⸮	pdbα⸮J!@#x9]2:�r⸮bD"⸮IN⸮⸮J#`'x⸮⸮⸮⸮⸮⸮Cx⸮⸮Ch6⸮⸮⸮⸮:⸮]Ja⸮*A⸮⸮⸮⸮⸮⸮⸮⸮sk*-L⸮⸮`F⸮⸮⸮(⸮⸮+" in my Arduino. Similar things on the way back.

I feel like I'm not giving you enough information but I don't know what else to share. If anything comes to my mind, or as part of this conversation, I will update this message to make it useful for future searches.

Thank you for creating this plugin!

Thanks,
Andi

**Comment by don** [comment]
I'd guess the example code is expecting ascii text and you're sending unicode.
