### ISSUE TITLE
Ble.write gives "Peripheral Disconnected" after 10-15 second

### ISSUE THREAD

**Issue by riteshchanchal1987** [don/cordova-plugin-ble-central#748]
Hi,
Initially ble.write works between central (android) and peripheral (android). 
But , After receiving notification, when i try to write again, i get error response after 10 15 seconds as:
**{"name":"HMT-1","id":"30:95:E3:AF:ED:DC","errorMessage":"Peripheral Disconnected"}**

**Bluetooth(peripheral ) data :** 
{
	"name": "HMT-1",
	"id": "30:95:E3:AF:ED:DC",
	"advertising": {},
	"rssi": -72,
	"services": ["1801", "1800", "7d2ea28a-f7bd-485a-bd9d-92ad6ecfe93e"],
	"characteristics": [{
		"service": "1801",
		"characteristic": "2a05",
		"properties": ["Indicate"]
	}, {
		"service": "1800",
		"characteristic": "2a00",
		"properties": ["Read"]
	}, {
		"service": "1800",
		"characteristic": "2a01",
		"properties": ["Read"]
	}, {
		"service": "1800",
		"characteristic": "2aa6",
		"properties": ["Read"]
	}, {
		"service": "7d2ea28a-f7bd-485a-bd9d-92ad6ecfe93e",
		"characteristic": "7d2ebaad-f7bd-485a-bd9d-92ad6ecfe93e",
		"properties": ["Notify"],
		"descriptors": [{
			"uuid": "2902"
		}]
	}, {
		"service": "7d2ea28a-f7bd-485a-bd9d-92ad6ecfe93e",
		"characteristic": "7d2ebaad-f7bd-485a-bd9d-92ad6ecfe93e",
		"properties": ["Read", "Write"]
	}]
}

Please help me resolving this issue

**Comment by don** [comment]
I don't think this is a problem with the BLE plugin. "Peripheral Disconnected" means you lost the connection. I'd guess the peripheral closed the connection. Some devices require certain characteristics to be read or written after connecting. Check the protocol for your device.
