### ISSUE TITLE
Cannot find mobile phones or tablets

### ISSUE THREAD

**Issue by jlbgit** [don/cordova-plugin-ble-central#752]
Hi,
first of all thanks for the library! I'm running this with the Ionic native ble plugin and Angular on an Android 9 phone. 

Works great in general, but somehow I find everything else but mobile phones or iPads, for example. I'm not a Bluetooth expert, so maybe I'm missing something very basic here. But is there any way this could be fixed? Any opiton I could change or is there another Ionic plugin required? For me it would be quite crucial to be able to find other phones.

Many thanks!
Jan

**Comment by don** [comment]
If the phone or iPad is not advertising a Bluetooth Low Energy services, your app can't find it.
