### ISSUE TITLE
Give service and charachteristic id to write function when we don't know exactly the id's

### ISSUE THREAD

**Issue by akashkhairnar01** [don/cordova-plugin-ble-central#774]
I am building an app that can communicate with ble device for client but the device is not with me to see there service and charachteristic then how can i give service and charachteristic id as a parameter to read and write function without knowing it

**Comment by don** [comment]
I typically get service and characteristic info from the device and compare with the documentation. However if you have good documentation for your peripheral, you can write an app without having the device.
