### ISSUE TITLE
Disconnect when it ask for pair

### ISSUE THREAD

**Issue by akashkhairnar01** [don/cordova-plugin-ble-central#775]
I have write the connect function in that i have a start notification function when it going to start the notification then it ask to pair when i click on connect on both side in 2 sec the device gets disconnected
This is My code
var onScan = function(peripheral) {

      log(TAG, "Scan found: " + JSON.stringify(peripheral));
      console.log(JSON.stringify(peripheral));
      var template = $('#device-template').html();
       Mustache.parse(template);
       var rendered = Mustache.render(template, {device: peripheral, title: JSON.stringify(peripheral)});

       var $item = $(rendered);
       //TODO Add all chracterisitics to devices so you can connect to it
       $item.click(function(){
         setStatus("Connecting to "+ peripheral.name + ": " + peripheral.id );
         bluetooth.connect(peripheral.id, onConnect, onDisconnect);
       });
       $("#list-devices").append($item);

  }
  var onConnect = function(peripheral) {

      // ble.setPin('12345', onSuccess, onError);
      log(TAG, "onConnect peripheral: " + JSON.stringify(peripheral));
      device.status = CONNECTED;
      setStatus("Connected to " + peripheral.name);
      drawMessage("info", "Connected to " + peripheral.name);

      device.peripheral = peripheral;   //Sample peripheral data https://github.com/don/cordova-plugin-ble-central#peripheral-data

      bluetooth.startNotification(
        peripheral.id,
        peripheral.characteristics[2].service,
        peripheral.characteristics[2].characteristic,
        onData,
        onError
      );
  }

**Comment by peitschie** [comment]
Bonding control is now available on Android as of 1.6.3

See https://github.com/don/cordova-plugin-ble-central?tab=readme-ov-file#bond and related methods.

iOS does not expose any information about this unfortunately, so it's impossible to confirm the bonding state on iOS.
