### ISSUE TITLE
Multiple services, same UUID

### ISSUE THREAD

**Issue by bastiaanv** [don/cordova-plugin-ble-central#776]
Hi,

I've got myself in a rather special situation:
I've got a BLE enabled device which has multiple services with the same UUID. This device consumes BLE commands to turn on a light or to control the sun blinds. Each device, light bulbs, sun blinds, etc, is connected to this device. For example: Let's say I have the device connected to 4 lightbulbs and 2 sun blinds. The discovery of services and characteristics would look the following:

- Lightbulb 1 (service UUID: 00403148-59CE-40EE-90AA-AB6A874119C7)
- Lightbulb 2 (service UUID: 00403148-59CE-40EE-90AA-AB6A874119C7)
- Lightbulb 3 (service UUID: 00403148-59CE-40EE-90AA-AB6A874119C7)
- Lightbulb 4 (service UUID: 00403148-59CE-40EE-90AA-AB6A874119C7)
- Sun blind 1 (service UUID: 00803148-59CE-40EE-90AA-AB6A874119C7)
- Sun blind 2 (service UUID: 00803148-59CE-40EE-90AA-AB6A874119C7)

Is there a way to read a characteristic of the third lightbulb, for example?

**Comment by don** [comment]
You need to pass in the device_id for most of the apI calls like startNotification and write. That works if your phone is connected to all 6 devices. 

If you have another device that is proxying BLE calls to all 6 devices that won't work with this plugin. You can do this with the native SDKs.
