### ISSUE TITLE
How can we done Bluetooth advertisement in ble-cental?

### ISSUE THREAD

**Issue by vinothkumartyson** [don/cordova-plugin-ble-central#779]

**Comment by don** [comment]
https://github.com/don/cordova-plugin-ble-peripheral

**Comment by vinothkumartyson** [comment]
Thanks Don, But background bluetooth advertisement can't be done in  Ble-Peripheral plugin. is there any way to advertisement data using ble-central plugin?

**Comment by don** [comment]
The ble-peripheral plugin is the best way to advertise. Technically it could be added here but I'm keeping them separate. You should be able to make ble-peripheral work in the background. It might require some modification but it should work.
