### ISSUE TITLE
Anyone had any issues with iOS 9?

### ISSUE THREAD

**Issue by markygab** [don/cordova-plugin-ble-central#78]
I'm just about to check this out as app users with iOS 9 Beta are reporting that the app crashes immediately that they attempt to use BLE.

**Comment by OnkarBhattacharya** [comment]
Issue 1 : Property 'isConnected' not found on object of type 'CBPeripheral'
Issue 2 : Property 'UUID' not found on object of type 'CBPeripheral'.

Seems like both properties are removed. (Source : https://developer.apple.com/library/prerelease/ios/documentation/CoreBluetooth/Reference/CBPeripheral_Class/index.html#//apple_ref/occ/cl/CBPeripheral)

**Comment by don** [comment]
This plugin will work with iOS 9 in the future. I haven't spent any time on iOS 9 compatibility yet.

**Comment by thomasbaggio** [comment]
Do you plan to test iOS 9 compatibility before the official launch? We have an app that uses your plugin and we must publish it in September .Thanks a lot.

**Comment by don** [comment]
@thomasbaggio it's in a long queue of stuff to be done, ideally before iOS 9 launches

**Comment by thomasbaggio** [comment]
thanks! If I can .... do you plan to do also the Windows Phone version in the next months? (only to know)

**Comment by markygab** [comment]
@don Would you be open to accepting payment to expedite this iOS9 work?

**Comment by don** [comment]
@markygab sure reach out first + last at gmail

**Comment by don** [comment]
@thomasbaggio Ideally I'll add Windows 10 and Windows Phone support, but it'll be a few months at least. The Windows scanning APIs are really crippled so it probably won't work the same.

**Comment by thomasbaggio** [comment]
@don ok thanks! Take a look here.. you can use javascript instead of c#, it works for WP and also Windows:
https://github.com/randdusing/BluetoothLE/pull/151

**Comment by don** [comment]
iOS9 support is merged in from #62 

The plugin has been migrated to NPM. Use the new id `cordova-plugin-ble-central`

**Comment by markygab** [comment]
Thanks Don,

We got it all working today. I might send you you through some our implementation to take a look at tomorrow if that's still ok?

Cheers,
Mark

**Comment by morganRotaStabelli** [comment]
damn! I have gone crazy today to implement the same changes , fool that I did not before ensuring that you have already been resolved ... however I found a difference , I have implemented
( peripheral.state ! = CBPeripheralStateDisconnected )
instead
peripheral.isConnected
Do you think is a mistake ?

**Comment by wlzimmer** [comment]
Do we know when the cordova ble plugin will support ios 9.x???   If not, is there another library that has been tested with ios 9.x??

**Comment by wlzimmer** [comment]
Sorry I missed the Sep 2 notes.

**Comment by don** [comment]
This plugin works with iOS 9. If you are seeing any problems, please open a new issue with details and a stack trace.
