### ISSUE TITLE
Android queues commands, while iOS does not

### ISSUE THREAD

**Issue by geertijewski** [don/cordova-plugin-ble-central#783]
This plugin behaves differently on Android from iOS, if the connection drops out temporarily.

On iOS commands (read, write, readRSSI, registerNotifyCallback, ...) are just passed through to the OS. If the connection is temporarily severed then the command(s) just doesn't get through.
However on Android they are queued. If the callback commandCompleted() is never called, then packets keep queuing up and are executed as the connection link is restored.

Given that cordovas goal is to allow me to not pay attention to platform details (as much as possible), this difference in behavior seems wrong. Specifially it bites me in my usecase, which is as follows:
- i use Bluetooth to connect to small vehicle affixed on a trailer
- as the user drives the vehicle (which in turn drives the caravan) they move around the caravan
- which temporarily severs the connection link (distance, obstacles, radio interference, ...)
- the vehicle stops (because it doesn't get any new direction commands)
- the app shows the user that it can't communicate with the vehicle anymore  (and sends the STOP command)
- the radio link returns (most probably the user just moved back closer)

Now on an iOS device nothing happens. But on an android there might be some commands, which were sent as the radio link was severed, in the queue. Making the vehicle stop, then sputter in the last direction only to stop again.

----

Firstly `queueCleanup()` should be documented, to give the library users the chance to at least make the behaviour consistent. This is Pull Request #782

Then commit 38ea5496965a14fa9c686f65d3900ff77eeac1c7 could be reverted (well it doesn't revert cleanly, so I guess the functionalty would need to be removed by hand). However as I seen in the following commit 4dce37575b710e034c9dc4315e65fdbf9acef212 it seems like the queuing was implemented to fix a problem. It sounds like iOS does also queue (did queue?)

**Comment by peitschie** [comment]
I realise this is a fairly old ticket, but wanted to provide some clarity for future viewers.

The behaviour **should** be identical between Android and iOS with regards to how commands are handled.

The queuing mechanism on Android is purely to serialise access to the underlying stack, as Android seems to be far more sensitive to too many concurrent BLE actions going on at the same time. This explicitly cleaned up on disconnect, and new commands should not be able to accumulate while the peripheral is disconnected.

If you can find a use case where the commands are being queued while the connection is offline and are not being cleaned up, I'd definitely consider that a bug.
