### ISSUE TITLE
App goes in the background with ble.enable

### ISSUE THREAD

**Issue by scrabionau77** [don/cordova-plugin-ble-central#788]
Hi everyone. I am using the plugin on Android and iOS. On Android 9 I noticed that the ble.enable command sends the app in the background. This does not happen on Android 7. The authorization request popup appears without problems, but then I have to reopen the app manually. Has it happened to others? There is a solution?
It is not a problem that prevents operation but it is unpleasant to see this behavior!
Thanks in advance.

**Comment by peitschie** [comment]
This is a phone/OS quirk that the plugin has no control over. We use the official Android intents to trigger this flow, and there's very little that can be done to prevent the behaviour you're seeing.
