### ISSUE TITLE
ble is not defined

### ISSUE THREAD

**Issue by daniperezluna** [don/cordova-plugin-ble-central#79]
Hi, I'm triying to develop an app with ionic an ngCordova but when I launch the app I receive the following message: 

ReferenceError: ble is not defined
    at Object.isEnabled (ng-cordova.js:610)
    at new <anonymous> (controllers.js:35)
    at invoke (ionic.bundle.js:13012)
    at Object.instantiate (ionic.bundle.js:13020)
    at ionic.bundle.js:17289
    at self.appendViewElement (ionic.bundle.js:48435)
    at Object.switcher.render (ionic.bundle.js:46629)
    at Object.switcher.init (ionic.bundle.js:46549)
    at self.render (ionic.bundle.js:48295)
    at self.register (ionic.bundle.js:48253)

This is my app.js:

```
// Ionic Starter App

// angular.module is a global place for creating, registering and retrieving Angular modules
// 'starter' is the name of this angular module example (also set in a <body> attribute in index.html)
// the 2nd parameter is an array of 'requires'
// 'starter.services' is found in services.js
// 'starter.controllers' is found in controllers.js
angular.module('starter', ['ionic', 'starter.controllers', 'starter.services', 'ngCordova'])

.run(function($ionicPlatform) {
  $ionicPlatform.ready(function() {
    // Hide the accessory bar by default (remove this to show the accessory bar above the keyboard
    // for form inputs)
    if (window.cordova && window.cordova.plugins && window.cordova.plugins.Keyboard) {
      cordova.plugins.Keyboard.hideKeyboardAccessoryBar(true);
      cordova.plugins.Keyboard.disableScroll(true);

    }
    if (window.StatusBar) {
      // org.apache.cordova.statusbar required
      StatusBar.styleLightContent();
    }
  });
})

.config(function($stateProvider, $urlRouterProvider) {

  // Ionic uses AngularUI Router which uses the concept of states
  // Learn more here: https://github.com/angular-ui/ui-router
  // Set up the various states which the app can be in.
  // Each state's controller can be found in controllers.js
  $stateProvider

  // setup an abstract state for the tabs directive
    .state('tab', {
    url: '/tab',
    abstract: true,
    templateUrl: 'templates/tabs.html'
  })

  // Each tab has its own nav history stack:

  .state('tab.dash', {
    url: '/dash',
    views: {
      'tab-dash': {
        templateUrl: 'templates/tab-dash.html',
        controller: 'DashCtrl'
      }
    }
  })

  .state('tab.chats', {
      url: '/chats',
      views: {
        'tab-chats': {
          templateUrl: 'templates/tab-chats.html',
          controller: 'ChatsCtrl'
        }
      }
    })
    .state('tab.chat-detail', {
      url: '/chats/:chatId',
      views: {
        'tab-chats': {
          templateUrl: 'templates/chat-detail.html',
          controller: 'ChatDetailCtrl'
        }
      }
    })

  .state('tab.account', {
    url: '/account',
    views: {
      'tab-account': {
        templateUrl: 'templates/tab-account.html',
        controller: 'AccountCtrl'
      }
    }
  });

  // if none of the above states are matched, use this as the fallback
  $urlRouterProvider.otherwise('/tab/dash');

});

```

And this my controllers.js:

```
angular.module('starter.controllers', [])

.controller('DashCtrl', function($scope) {})

.controller('ChatsCtrl', function($scope, Chats) {
  // With the new view caching in Ionic, Controllers are only called
  // when they are recreated or on app start, instead of every page change.
  // To listen for when this page is active (for example, to refresh data),
  // listen for the $ionicView.enter event:
  //
  //$scope.$on('$ionicView.enter', function(e) {
  //});

  $scope.chats = Chats.all();
  $scope.remove = function(chat) {
    Chats.remove(chat);
  };
})

.controller('AccountCtrl', function($ionicPlatform,$scope,$cordovaBLE) {
  
  $ionicPlatform.ready(function(){
         
         $cordovaBLE.isEnabled(
    function() {
        alert("Bluetooth is enabled");
    },
    function() {
        alert("Bluetooth is *not* enabled");
    }
);
  });

})
```

**Comment by NewLunarFire** [comment]
ble is not defined if the platform you are testing your code on doesn't support BLE.

**Comment by daniperezluna** [comment]
I am testing my code directly on Android 4.4.2 who supports BLE.

**Comment by daniperezluna** [comment]
If you need more information about my devices I am using :

**Comment by NewLunarFire** [comment]
From the specs of the phone Bluetooth Smart should be supported, but just to make sure have you been able to connect to your peripheral from another application?

**Comment by don** [comment]
`ble` is defined by the plugin. If you're seeing errors about ble not defined, it's typically that the plugin didn't install correctly or you're trying to call a function before Cordova fires `ondeviceready`. Try uninstalling and re-installing the plugin first.

**Comment by daniperezluna** [comment]
I install again the plugin and it's works properly. I am using ionic and I can scan but I can't connect to my device. I have the macAddress but when I do ble.connect(peripheral.id, app.onConnect, app.onDisconnect); never connect to the device.

Someone knows why is it?

I have tried with the heart rate example, using the functions inside ionicPlatform and I have changed the values of the heartRate.service and heartRate.measurement.

I have a blood pressure monitor and those values are '1810' and  '2a35' but when the monitor sends data and I try to connect always say that is not possible.

I saw you use ble.notify but it is not present in factory.

**Comment by don** [comment]
@daniperezluna try connecting to your phone to the monitor using [nRF Master Control Panel](https://play.google.com/store/apps/details?id=no.nordicsemi.android.mcp&hl=en)

You'll need ble.startNotification to get blood pressure measurement, since that's sent with an indication and not readable.

**Comment by soumendub3** [comment]
@don I have the similar issue as *daniperezluna* started the issue with and I followed the instructions, uninstalled the plugin and reinstalled back but I cannot get the plugin to work. I am using ionic framework with AngularJS. 
@daniperezluna Also, what I am not following is how do you get $cordovaBLE in controllers.js? Are you still using the same code as posted above? If not, can you share your working code? Thanks.

**Comment by daniperezluna** [comment]
@soumendub3 Have you tried to debug it on your phone? My problem was that this message appears when I open the app in the browser

**Comment by don** [comment]
@soumendub3 I suggest you get simple Bluetooth examples working without Ionic or Angular, then work on adding Bluetooth support to your Ionic app.

I have a simple Ionic Bluetooth LE App you can try too. https://github.com/don/ionic-ble. Note that it does *not* use the ng-cordova wrappers.

Look at BLE in [services.js](https://github.com/don/ionic-ble/blob/455e4cb618b7f8b234b3ab4832c66f4f353ba2f4/www/js/services.js#L52) and BLECtrl and BLEDetailCtrl in [controllers.js](https://github.com/don/ionic-ble/blob/455e4cb618b7f8b234b3ab4832c66f4f353ba2f4/www/js/controllers.js#L16)

**Comment by soumendub3** [comment]
@don Thanks for the response Don - yes, I found your ionic-ble code and I started with your example. I had trouble with it as well and I created an issue in the project. I understand the BLE and BLEDetailCtrl and see how you defined them but my trouble there was different. Can you please take a look at that one? [Link to the issue](https://github.com/don/ionic-ble/issues/2)

**Comment by soumendub3** [comment]
@daniperezluna Yes, I tried on my phone and it was not related to browser.

**Comment by don** [comment]
@daniperezluna great news

@soumendub3 I'll continue this in the other project

**Comment by daniperezluna** [comment]
@soumendub3 Here you are my code https://github.com/daniperezluna/BlueHeart It's an app to read data from a Blood Pressure.

**Comment by wifixcort** [comment]
I have the same issue in ionic. If I write:
`
ble.isEnabled(function() {
     alert("Bluetooth is enabled");
      ble.scan([], 5, function(device) {
         console.log(JSON.stringify(device));
}, function(function(error){}){});     
        },
      function() {
           alert("Bluetooth is DISABLED");
       }
    );
`
works, but just in app.js, if I try to use in my controller.js it doesn't work

**Comment by abnuozal** [comment]
Make it like this in your controller:

`   $ionicPlatform.ready(function(){
     window.ble.isEnabled(
      //do something
);
   })`

**Comment by 20gg** [comment]
@wifixcort  you can try this way.bind Event with $scope ,just like 

> $scope.onIsEnabled = function(){
    ble.isEnabled(
    function() {
        console.log("Bluetooth is enabled");
    },
    function() {
        console.log("Bluetooth is *not* enabled");
    }
     );
  }

**Comment by wifixcort** [comment]
@20gg Thanks for your advice, I'll try it :+1:
