### ISSUE TITLE
Unable to connect to devices

### ISSUE THREAD

**Issue by rosterloh** [don/cordova-plugin-ble-central#8]
Hi @don, I have been trying to get your plugin to work for a few days now but I'm getting no joy.

I'm developing using Ionic on a Motorola G running KitKat 4.4.4 and `ble.scan([], 5, success, fail)` returns the results and I have even tried

```
ble.scan([], 5, function(dev) { 
  console.log(dev.name+' : '+dev.rssi+'dBm : '+dev.id+' : '+angular.equals(dev.id, 'D0:39:72:F1:E9:72')); }, 
function(err) { 
  $scope.onError(err); 
});
```

which returns true but connect always returns 'Peripheral D0:39:72:F1:E9:72 not found'

Any ideas?

My code for reference [here](https://gist.github.com/rosterloh/da0a6c917956683b813a)

**Comment by RangerMauve** [comment]
I've currently got a scan going, and I connect to the device almost as soon as I find it. I also happen to stop the scan almost as soon as I connect to the device. Would calling `stopScan()` directly after `connect()` screw up the `connect()` call?

**Comment by don** [comment]
@RangerMauve on _some_ hardware this seems to be a problem. For best results call `stopScan()` before `connect()` if the scan has not completed and you're seeing problems.

**Comment by RangerMauve** [comment]
@don Really? I thought it would have been the opposite, `stopScan()` after a successful `connect()`. I'll try both approaches and see how it turns out. Thanks!

**Comment by halindrome** [comment]
Interesting.   Is it safe to call stopScan from within the handler function
that is processing the matches coming out of the scan?

On Tue, Nov 3, 2015 at 9:26 AM, RangerMauve <notifications@github.com>
wrote:

> @don <https://github.com/don> Really? I thought it would have been the
> opposite, stopScan() after a successful connect(). I'll try both
> approaches and see how it turns out. Thanks!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/don/cordova-plugin-ble-central/issues/8#issuecomment-153388055>
> .
>



-- 
Shane McCarron
halindrome@gmail.com

**Comment by don** [comment]
@RangerMauve some hardware seems to connect fine while it is scanning. Other devices refuse to connect until the scan is complete. I'm not sure if its a hardware or Android version issue. Let me know what works for you.

@halindrome I think it's fine to call, but I'm not sure. Typically I'm listing the discovered devices in a UI and the user clicks to connect. If the app is scanning, I can stopScanning before connecting.

**Comment by JorgeMorata** [comment]
Hi,

There is another situation that makes the app fails:

If I connect to a device with autoconnect, and then I start notification from a characteristics, when I get away from the mobile, the plugin notify the device disconnected (normal behaviour).

At the same time, I do interval scanning for search more devices, but when i get close the phone another time, the first device is reconnected but the startNotification fails with this error 'Peripheral  XXXXX not found.'

I think you should be able to reconnect and resubscribe regardless of whether the device has been scanned or not (In my case the second scan should not interfere with the reconnection of the first device)

**Comment by bogde** [comment]
I'm having the same problem.

@JorgeMorata Did you find a solution?

It looks like in the **onDeviceConnected** callback, if i check for ble.isConnected(...) it actually says the device is NOT connected, which is odd, right? It seems that i can call ble.autoConnect(...) from that and then it works, but it just doesn't seem right. Anyone can provide any ideas?

**Comment by JorgeMorata** [comment]
Hi! I finally migrate the app to native for not having problems with bluetooth sorry :/

 

De: bogde <notifications@github.com> 
Enviado el: viernes, 18 de septiembre de 2020 10:41
Para: don/cordova-plugin-ble-central <cordova-plugin-ble-central@noreply.github.com>
CC: JorgeMorata <jorgemoratatoribio@gmail.com>; Mention <mention@noreply.github.com>
Asunto: Re: [don/cordova-plugin-ble-central] Unable to connect to devices (#8)

 

I'm having the same problem.

@JorgeMorata <https://github.com/JorgeMorata>  Did you find a solution?

It looks like in the onDeviceConnected callback, if i check for ble.isConnected(...) it actually says the device is NOT connected, which is odd, right? It seems that i can call ble.autoConnect(...) from that and then it works, but it just doesn't seem right. Anyone can provide any ideas?
