### ISSUE TITLE
Connect and read from barcode scanner in HID mode with Bluetooth Low Energy

### ISSUE THREAD

**Issue by stefanpu-nuvolo** [don/cordova-plugin-ble-central#807]
Hello, 
I have a Barcode Scanner Zebra DS2278. One of its setup options is **HID Bluetooth Low Energy (Discoverable)**.
I successfully discover and connect to the device using this setup on android. However, unlike connecting through native bluetooth of my phone(Motorola G6), I cannot use the scanner as HID, e.g. focus on input and read barcode to fill in the input. 
Is this possible with this plugin?

**Comment by don** [comment]
I haven't used this scanners, but if there's a BLE service, you should be able to write code to get barcodes. Ideally the manufacturer documents the service. If not you're stuck reverse engineering it. If you need Bluetooth Classic (on Android only) try [cordova-plugin-bluetooth-serial](https://github.com/don/BluetoothSerial).
