### ISSUE TITLE
ble.scan() doesn't return success or error Huawei Mate 10 pro

### ISSUE THREAD

**Issue by AmonM** [don/cordova-plugin-ble-central#813]
**Device:** Huawei Mate 10 pro, android 10, firmware: 10.0.0.159

**Error:** ble.scan() doesn't call success or error, but it used to work one or two months ago. Tried reverting app and it still didn't work.

**android manifest xml:** 
`  <uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION"/>
  <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION"/>
  <uses-permission android:name="android.permission.BLUETOOTH"/>
  <uses-permission android:name="android.permission.BLUETOOTH_ADMIN"/>`

Bluetooth and location are both enabled.

**Edit:** Forgot to add that I'm using plugin with Quasar 1.9.6.

**Comment by don** [comment]
This was fixed in version 1.3.0.

See #771
