### ISSUE TITLE
Android scan with multiple uuids

### ISSUE THREAD

**Issue by tellybrown** [don/cordova-plugin-ble-central#816]
Maybe update the docs a bit since this caused me some troubles.  I was expecting to pass a list of UUID's of services I was looking for and not a list a service UUID's required by the device.

[BluetoothAdapter.startLeScan](https://developer.android.com/reference/android/bluetooth/BluetoothAdapter#startLeScan(android.bluetooth.BluetoothAdapter.LeScanCallback))

Starts a scan for Bluetooth LE devices, looking for devices that advertise given services.

**Devices which advertise all specified services** are reported using the LeScanCallback#onLeScan callback.
Requires Manifest.permission.BLUETOOTH_ADMIN

**Comment by peitschie** [comment]
@tellybrown I don't quite follow the difference in what you describe here, sorry.

The startScan should be passed a list of all service UUIDs you want a device to support. I'm not sure what you mean by "service UUID's required by the device". Are you able to provide an example of this?
