### ISSUE TITLE
Get currently connected device?

### ISSUE THREAD

**Issue by chladnefazole** [don/cordova-plugin-ble-central#827]
Hello, is there any way to get the currently connected device with this plugin? How is this usually dealt with? Is there some security reason why it is missing? I am researching but having trouble finding any info.

Like in my regular phone settings, when I open Bluetooth I can see which device is currently connected.

I want the user to be able to see what is the current state of their BT connection, so they can disconnect/connect manually, and will not be confused when the app does it for them.

Functions `connect` and `isConnected` both require the device ID to be passed in, so I can't just call ex. `connect().subscribe()` and get back an Observable which fires whenever a device is connected OR disconnected.

**Comment by peitschie** [comment]
Hi @chladnefazole 

Unfortunately, there's no mechanism that provides this on current versions of iOS and Android. As you guessed, it's related to security on both, as being able to list any connected devices was seen as a privacy issue.

`bondedDevices` (https://github.com/don/cordova-plugin-ble-central#bondeddevices) is the closest this plugin can provide on Android. iOS has https://github.com/don/cordova-plugin-ble-central#peripheralswithidentifiers and https://github.com/don/cordova-plugin-ble-central#connectedperipheralswithservices, however, these both seem unreliable in my own use.

It's worth noting that on Android, a BLE device is connected **per application** which means that your app can't force the Bluetooth connection closed if the user has manually connected to it via the Android system Bluetooth panel.

Having said that, if you did discover a method for this I'd definitely be interested in hearing how you made it work.

I'll close this for now as it's a limitation of the underlying operating systems, and has no effective workaround in the plugin. However, feel free to continue the discussion here.
