### ISSUE TITLE
Queued commands hang on Android if service or BluetoothGatt is null

### ISSUE THREAD

**Issue by doug-a-brunner** [don/cordova-plugin-ble-central#829]
Several commands can hang up the queue on Android under some conditions. I'm not sure if null `BluetoothGatt` is a realistic concern, but I first noticed this issue when attempting to read a characteristic from a service that doesn't exist on the target device (I'm supporting two different variants of the hardware, which can only be distinguished in this way). I'll be making a PR for this shortly.

**Comment by peitschie** [comment]
Closing this out as https://github.com/don/cordova-plugin-ble-central/pull/830 has been merged. Thanks for your contribution again @doug-a-brunner !
