### ISSUE TITLE
Encryption array buffer

### ISSUE THREAD

**Issue by Allamprabhu11** [don/cordova-plugin-ble-central#831]
Is it possible to encrypt and decrypt the array buffer what we getting from the peripheral device?

Thanks

**Comment by tellybrown** [comment]
That seems outside the bounds of this project.  I'm sure there are many encryption plugins out there to use.

**Comment by peitschie** [comment]
Hi @Allamprabhu11 

The security of the connection is better handled using Bluetooth pairing or bonding, which will transparently encrypt the traffic between the phone and the peripheral.

Any additional layers of encryption beyond this need to be specifically implemented in the peripheral also, so there is no one-size-fits all solution, unfortunately.

I'll close this out as there's not really a feasible solution that works within the plugin for this need. However, feel free to continue the discussion here if desired.
