### ISSUE TITLE
ACCESS_BACKGROUND_LOCATION permission

### ISSUE THREAD

**Issue by tellybrown** [don/cordova-plugin-ble-central#833]
I am now pushing my app to the google play store which subsequently requests for extra information as to why I am requesting background location access.  I have no need of this access but your plugin essentially forces it upon me.  Which means I will never pass their review process because I have no real reason for this permission.
Shouldn't the permission requests be made by the owning application and not the plugin?
Is there someway via the build to remove this access or somehow add a block permission in the manifest?

**Comment by HankLloydRight** [comment]
See the discussion on this open issue:  https://github.com/don/cordova-plugin-ble-central/issues/821
