### ISSUE TITLE
on android, ble can hang with a disconnect between writeCharacteristic and onCharacteristicWrite

### ISSUE THREAD

**Issue by adamtegen** [don/cordova-plugin-ble-central#84]
When a disconnect occurs after writeCharacteristic, but before the onCharacteristicWrite is called, Android will not call onCharacteristicWrite().

This results in:
1. the javascript callback is not called with a failure for write
2. bleProcessing is stuck true, so subsequent write's read's and notify's aren't processed.

Tested with a Nexus 7 on Android 4.4.2

**Comment by don** [comment]
@adamtegen thanks for the pull request. It looks good I just want to test on some hardware before merging.

**Comment by don** [comment]
This should be fixed in 1.2.0
