### ISSUE TITLE
Android 8+: scanning callback is very long 

### ISSUE THREAD

**Issue by lubinx** [don/cordova-plugin-ble-central#855]
in function findLowEnergyDevices()
  bluetoothLeScanner.startScan() is using default SCAN_MODE_LOW_POWER, this cause scanning has very long interval

add follow code can resolve this problem
```java
        ScanSettings settings = new ScanSettings.Builder()
            .setScanMode(ScanSettings.SCAN_MODE_LOW_LATENCY)
            .build();
```

suggest
  add android scan mode options to ble.startScanWithOptions(), like reportDuplicates do

**Comment by peitschie** [comment]
This has been addressed in https://github.com/don/cordova-plugin-ble-central/pull/835
