### ISSUE TITLE
Does this work cross platform ?

### ISSUE THREAD

**Issue by savitaraghuvanshi** [don/cordova-plugin-ble-central#856]
@don , Thanks so much for creating this library . 
"My goal is to transfer msg between 2 mobile devices in offline mode" cross platform android to iOS and iOS to android .
I tried some Bluetooth react native libraries but they does not work cross platform . while they are ok android to android and ios to ios .
can i transfer data between 2 mobile devices cross platform using it ? 

If you do have any suggestions or if you know any libraries which can work cross platform in offline mode(Either using WIFI hot spot or Bluetooth or any other technology) it would be really great help to me ?

**Comment by peitschie** [comment]
This plugin works across platforms.

It sounds like you're asking a more general question about how to communicate between two mobile devices. Such a solution is possible via Bluetooth, but requires use of a Peripheral plugin as well to work, such as https://github.com/don/cordova-plugin-ble-peripheral.

I'm going to close this out for now as there isn't really a specific issue or question related to this plugin specifically. However, feel free to continue the discussion here!
