### ISSUE TITLE
StartNotification with Hrm response null

### ISSUE THREAD

**Issue by elepetit** [don/cordova-plugin-ble-central#857]
Hi,

trying to connect to a geonaute HRM device with success.(180d - 2a37)
But, not managed to subscribe to HRM with data back.
I've always 0 value.
Ionic 5 - last version of plugin - native wrapper

Anyone stuck too?

thx

**Comment by lluisclava** [comment]
Same issue

**Comment by elepetit** [comment]
Yes, i ´ve modified the plugin and works fine but will try this!! thanks

**Comment by peitschie** [comment]
Closing this as I presume this has been solved by the linked comment. It seems there was some issues with the Ionic wrapper that have hopefully been resolved.
