### ISSUE TITLE
Bluetooth is not connecting after killing Ionic App in IOS

### ISSUE THREAD

**Issue by ManikantaKandula** [don/cordova-plugin-ble-central#867]
@don I'm building Ionic App which uses BLECentralPlugin for both Android and IOS.In IOS after killing the app and trying to connect bluetooth manually but it is not connecting and user need to forget device in Phone Settings everytime and then connecting.
We got to know the solution. i.e., to use RestoredStatePeripheralsKey and RestoredStateScanServicesKey. 

For your below is the method changed in BLECentralPlugin.m file 
NSDictionary* dictionaryOptions = @{
          CBConnectPeripheralOptionNotifyOnNotificationKey:@true,
          CBCentralManagerRestoredStatePeripheralsKey:@"MyBluetoothManager",
          CBCentralManagerRestoredStateScanServicesKey:@"CoreBluetooth",
          CBCentralManagerOptionShowPowerAlertKey: @NO
          };
    peripherals = [NSMutableSet new];
  manager = [[CBCentralManager alloc] initWithDelegate:self queue:nil options:dictionaryOptions]; 

Please release new version of ble-central with these changes.
Thanks in advance

**Comment by peitschie** [comment]
Hi @ManikantaKandula ,

Those keys you've added there don't seem correct to me if the intent is to allow iOS restoration. The consts you have listed are used in the extract information out of the restoration state iOS will provide if a restore identifier key is provided to the `CBCentralManager`.

Having said that, I suspect you're asking for iOS restore support which I'm delighted to say is now present in 1.4.2. See https://github.com/don/cordova-plugin-ble-central/pull/888 and #717 for more details and caveats.

I'll close this issue based on the above, but feel free to continue the discussion or re-open it if I've missed your request here.
