### ISSUE TITLE
Add Browser Platform Support

### ISSUE THREAD

**Issue by mwbrooks** [don/cordova-plugin-ble-central#87]
We use this plugin in [phoengap/phonegap-app-developer](http://github.com/phonegap/phonegap-app-developer). Currently, we're in the process of [adding browser support](https://github.com/phonegap/connect-phonegap/milestones/Add%20browser%20support) to the `phonegap serve` command. This will allow developers to pair both their devices and their desktop browser to the PhoneGap CLI.

The general idea is that when someone is developing an app, they will eventually call a JavaScript function for BLE plugin. On the desktop, we don't want that call to throw an error because the function isn't defined. We also don't want that call to go into the ether with no indication that it isn't supported. With other plugins, we've taken three approaches with the desktop implementation:

1. Mock responses when it makes sense. For example, contacts uses localStorage to read/write to a fake set of contacts on the desktop.
2. Invoke the callback with an error object describing that the call is not support. This ensures that the developer has proper error coverage, since the mobile device will fire the success callback while the desktop will fire the error callback.
3. Some APIs don't have callbacks (e.g. vibration), so output a console log with an error describing how the vibration function is not supported on the desktop.

It would be best for the BLE to choose #2 or #3. I think the API is defined well enough to handle #2.

@surajpindoria or myself can help with the browser implementation or even do it entirely ourselves. Just let us know whether you're cool with adding browser support and any requirements / direction that you'd like.

Cheers,
Michael

**Comment by don** [comment]
Merged #90

**Comment by mwbrooks** [comment]
:+1:
