### ISSUE TITLE
[URGENT] App removed from Google Play: "Your app is not compliant with Google Play Policies"

### ISSUE THREAD

**Issue by nunoarruda** [don/cordova-plugin-ble-central#870]
Hi,

Thanks for the great plugin!

Unfortunately, our app was removed from Google Play because of the location access/permissions this plugin uses: `ACCESS_BACKGROUND_LOCATION`, ~~`ACCESS_COARSE_LOCATION`~~, and ~~`ACCESS_FINE_LOCATION`~~. This is the email we got:

![google-play-email](https://user-images.githubusercontent.com/1189149/139268795-31a2d38d-d284-4e65-9377-5e93c2d30b34.png)

I'm currently investigating if there's anything I can do on my side but decided to open this issue in case someone has any immediate feedback about this issue.

Anyone else having this issue? How did you fix it? Does this, perhaps, require changes to this plugin?

**Comment by nunoarruda** [comment]
Update: A new version of our app is back on Google Play.

The short-term solution for us was to replace https://github.com/don/cordova-plugin-ble-central with the fork https://github.com/Gargamil/cordova-plugin-ble-central which removes the `ACCESS_BACKGROUND_LOCATION` permission (we don't need this permission for our app). We also had to select the option `No, this app does not meet the Location permissions policy` in the [Location permissions declaration form](https://play.google.com/console/developers/app/app-content/permission-declarations).

A possible long-term solution for us is to replace cordova-plugin-ble-central with https://github.com/capacitor-community/bluetooth-le since cordova-plugin-ble-central looks to be unmaintained and thus not keeping up with these policy changes.

**Comment by andresmaiden** [comment]
Is there any fork on npm? I am using volt.build and they can add only plugins on npm.

**Comment by nunoarruda** [comment]
@andresmaiden No idea, but you may have better luck creating a fork yourself and publishing it to npm.

**Comment by peitschie** [comment]
Addressed via https://github.com/don/cordova-plugin-ble-central/pull/844
Use the new `ACCESS_BACKGROUND_LOCATION` in as documented in the README to opt-in to background scanning: https://github.com/don/cordova-plugin-ble-central#android
