### ISSUE TITLE
Problem with writing HEX to device

### ISSUE THREAD

**Issue by urosmesko** [don/cordova-plugin-ble-central#876]
I have a problem with Ionic BLE modul.
If i send hex 3E47545427562527 to FFF6 characteristic, then i receive 3e475139275625272525181f from FFF4 characteristic on Bluetooth BMS app, so device return data.
![Screenshot 2021-11-18 at 11 56 16](https://user-images.githubusercontent.com/6062157/142408049-71446a08-dc7a-4df6-ae27-c74327c3f29e.png)

But on ionic ble modul i dont receive notification:
//read from fff4 notification
    this.ble.startNotification(this.peripheral.id, 'FFF0', 'FFF4').subscribe(
      value => {
        console.log(value,this.bytesToString(value) );
      },
      error => {console.log('Unexpected Error', error)}
    );
//write to fff6 characteristic
let data = this.stringToBytes("3E47545427562527");
this.ble.writeWithoutResponse(this.peripheral.id, 'FFF0', 'FFF6',data).then(
  buffer => {
    console.log(buffer);
  }
);

**Comment by peitschie** [comment]
Out of interest, what ended up being the issue here @urosmesko ?
