### ISSUE TITLE
Need to access characteristic data.

### ISSUE THREAD

**Issue by idhruvnaik** [don/cordova-plugin-ble-central#882]
I am trying to access the characteristic's data with startNotification but not getting any success or failure callback.

Here's my code

```
ble.startNotification($scope.tableCode.deviceId, "1808", "2A18", function (data) {
                    alert("Result ==>" + JSON.stringify(data));
  }, function (error) {
                    alert("Start notification Error =>" + JSON.stringify(error));
  });
```

Prior to startNotification i had write the buffer data and got "OK" in success callback.

```
ble.write($scope.tableCode.deviceId, "00001808-0000-1000-8000-00805f9b34fb", "00002A52-0000-1000-8000-00805f9b34fb", dataByteArrayInLittleEndian.buffer, function (result) {
       alert("WRITE Success ==>" + JSON.stringify(result));
}, function (error) {
        alert("WRITE Error ==>" + JSON.stringify(error));
});
```

Do i need to enable indication or notification on device. If yes please provide steps for it.

**Comment by peitschie** [comment]
`startNotification` is a way for listening to BLE notifications sent by the peripheral to the phone. It only response when the peripheral changes the value, and won't directly read a characteristic... for that, you should be using `ble.read(...)` instead.
