### ISSUE TITLE
Getting error code 129.

### ISSUE THREAD

**Issue by idhruvnaik** [don/cordova-plugin-ble-central#883]
Whenever i try to write data i get 129 in error callback.

Here's my code.

```
var lastValueRetriever = 0x0106;
 const dataMostSignificantByte = (lastValueRetriever >> 8) & 0xFF;
 const dataLeastSignificantByte = lastValueRetriever & 0xFF;
 const dataByteArrayInLittleEndian = [dataLeastSignificantByte, dataMostSignificantByte];

```
```
ble.write($scope.tableCode.deviceId, "00001808-0000-1000-8000-00805f9b34fb", "00002A52-0000-1000-8000-00805f9b34fb", dataByteArrayInLittleEndian.buffer, function (result) {
       alert("WRITE Success ==>" + JSON.stringify(result));
}, function (error) {
        alert("WRITE Error ==>" + JSON.stringify(error));
});
```

**Comment by peitschie** [comment]
Hi @idhruvnaik 

There's unlikely to be anything in the plugin causing this issue. I'd suggest attempting to perform this write manually with a BLE debugging app like [nrf Connect](https://play.google.com/store/apps/details?id=no.nordicsemi.android.mcp), and see if this gives you any more hints.

Failing that, googling around for Android error code 129 may turn up some further suggestions for you to try?

I'd be interested in hearing if you get to the bottom of the issue. I'll close this ticket for now as it's not likely a plugin issue, but feel free to continue the conversation here.
