### ISSUE TITLE
Disconnect every connected device

### ISSUE THREAD

**Issue by Doomkyn** [don/cordova-plugin-ble-central#884]
Hello,
is there a method to disconnect every connected device?

Thanks

**Comment by peitschie** [comment]
Hi @Doomkyn 

As far as I am aware there is not.

Neither Android or iOS provide reliable interfaces to list all currently connected Bluetooth devices. Effectively, each Bluetooth connection is private to the application that requests the connection. Even closing a GATT handle on a currently connected BLE device won't necessarily disconnect if there are other applications and services running on the phone holding the connection open.
