### ISSUE TITLE
isConnected return true even after turning bluetooth on/off from Android phone

### ISSUE THREAD

**Issue by tigohenryschultz** [don/cordova-plugin-ble-central#894]
We are turning bluetooth on/off in the middle of a connection and receiving a write error. When we get a write error we check if the device isConnected, which is returning true but it should not be.

If the user disables bluetooth it should disconnect all sessions.

**Comment by peitschie** [comment]
I've been able to confirm this issue. Will dig into it in the next few days!

**Comment by peitschie** [comment]
I've pushed up a pre-release build if you're able to confirm that this fixes the issue for you: https://www.npmjs.com/package/cordova-plugin-ble-central/v/1.4.3-alpha.1

**Comment by peitschie** [comment]
@tigohenryschultz are you able to confirm whether the 1.4.3-alpha.1 release fixes this issue for you?

**Comment by tigohenryschultz** [comment]
I will try tomorrow, I was having trouble building the Android app today with it.

**Comment by tigohenryschultz** [comment]
@peitschie 

I get this error in AndroidStudio when trying to build/deploy to my phone:

```
I:\projects\tigosmart\android\capacitor-cordova-android-plugins\src\main\java\com\megster\cordova\ble\central\BLECentralPlugin.java:526: error: cannot find symbol
                    int connectedState = bluetoothManager.getConnectionState(peripheral.getDevice(), BluetoothProfile.GATT);
                                                                                                     ^
  symbol:   variable BluetoothProfile
  location: class BLECentralPlugin
```

**Comment by peitschie** [comment]
I've pushed 1.4.4-alpha.2, which should fix the compile issue. Apologies for that hiccup!
