### ISSUE TITLE
ble.write with non-arraybuffer type is silently ignored on iOS

### ISSUE THREAD

**Issue by tigohenryschultz** [don/cordova-plugin-ble-central#897]
After a user connects we register for notifications then try to write commands. This works perfectly on Android but we are not seeing any callsback for iOS.

The error scenario fires when you disconnect with 'Peripheral disconnected'

**Comment by tigohenryschultz** [comment]
Using the cordova/ionic

**Comment by peitschie** [comment]
@tigohenryschultz can you provide any code samples here of what you're doing?

I am extremely certain that notifications work just fine on iOS, so the question here is what you are doing or what your peripheral is doing that might be behaving differently.

Have you tried using an application like nrf Connect on your iPhone to see if that has any different behaviour?

**Comment by tigohenryschultz** [comment]
We were using this plugin for a long time: https://github.com/randdusing/cordova-plugin-bluetoothle but it is abandoned and has tons of little bugs crippling us. I've refactored our code base to use this plugin, which I have working amazingly well on Android but found a few quirks on iOS. I'll post code samples of our flow when I have time today.

**Comment by tigohenryschultz** [comment]
Our implementation is wrapped inside Vue/Vuex and Promises.

To start we always:

Request permissions when page loads, or when the user refreshes, if the user is already connected to a device it skips scanning
```
      this.requestPermissions()
          .then(() => {
            if (this.isConnectedTo.length === 0) {
              this.startScanLocal();
            }
          });
```

Our Permissions modules requests numerous permissions for iOS & Android:
The TigoBle2 module is this plugin, our randdusing implementation is TigoBle1.
The variable 'hasAllPermissions' is what tracks if any permissions are missing for the user.

```
requestPermissions: ({dispatch, commit}) => {
    log.debug('TigoPermissions:getPermissions');

    if (typeof window.cordova.plugins === "undefined"
      || typeof window.cordova.plugins.permissions === "undefined") {
      return;
    }

    let permissions = window.cordova.plugins.permissions;

    let REQUIRED_PERMISSIONS = [
      permissions.ACCESS_COARSE_LOCATION,
      permissions.ACCESS_FINE_LOCATION,
      permissions.CHANGE_WIFI_STATE,
      permissions.ACCESS_WIFI_STATE,
      permissions.ACCESS_NETWORK_STATE,
      permissions.INTERNET
    ];

    return new Promise((resolve, reject) => {
      permissions.requestPermissions(REQUIRED_PERMISSIONS,
        success => {
          log.debug('TigoPermissions:getPermissions:success:', success);

          Promise.all([
            dispatch('getLocationPermissions'),
            dispatch('ccaComm/TigoBle2/isBleEnabled', {}, {root: true}),
            dispatch('ccaComm/TigoBle2/isLocationEnabled', {}, {root: true}),
          ])
            .then((success) => {
              commit('setHasAllPermissions', true);
              resolve(success);
            })
            .catch((error) => {
              commit('setHasAllPermissions', false);
              reject(error);
            });
        },
        error => {
          log.debug('TigoPermissions:getPermissions:error:', error);
          commit('setHasAllPermissions', false);
          reject(error);
        }
      )
    });
  },
```

For the other iOS ble.isEnabled issue this is what we had to do, we had to force it to resolve true for iOS:

```
  isBleEnabled: ({commit, dispatch}) => {
    log.debug('TigoBle2:isBleEnabled');

    return new Promise((resolve, reject) => {

      //@TODO remove this hack when bug is fixed
      if (window.Capacitor.isIOS === true) {
        commit('setIsBleEnabled', true);
        resolve(true);
        return;
      }

      window.ble.isEnabled(
        () => {
          commit('setIsBleEnabled', true);
          resolve(true);
        },
        () => {
          commit('setIsBleEnabled', false);

          dispatch('enableBle')
            .then(resolve)
            .catch(reject);
        }
      );
    });
  },
```

If the user has all permissions the scanning starts/is allowed:

```
  startScanBle: ({commit}) => {
    log.debug('TigoBle2:startScanBle');

    return new Promise((resolve) => {
      commit('ccaComm/setUnitsFound', [], {root: true});

      window.ble.startScan([],
        (device) => {
          console.log('TigoBle2:startScanBle:success:', device);
          // We will resolve when the scan has started
          // but the function will still be called updating devices
          commit('ccaComm/setIsScanning', true, {root: true});
          commit('ccaComm/addUnitsFound', device, {root: true});
          resolve(device);
        },
        () => {
          commit('ccaComm/setIsScanning', false, {root: true});
        }
      );
    });
  },
```

This will build a unitsFound array that our interface will allow the user to connect to devices. Once a user clicks a device we will connect to the device like so:

 ```
connectToDeviceBle: ({commit, dispatch}, device) => {
    log.debug('TigoBle2:connectToDeviceBle');

    return new Promise((resolve, reject) => {
      commit('ccaComm/setIsConnectingTo', device, {root: true});

      window.ble.connect(device.id,
        (success) => {
          log.debug('TigoBle2:connectToDeviceBle:success:', success);
          commit('ccaComm/setAutoReconnect', false, {root: true});
          commit('ccaComm/addIsConnectedTo', device, {root: true});
          commit('ccaComm/setIsConnectingTo', null, {root: true});
          dispatch('registerNotification', device)
            .then(resolve)
            .catch(reject);
        },
        (error) => {
          console.error('TigoBle2:connectToDeviceBle:error:', error);

          if (error.errorMessage === 'Bluetooth Disabled' || error.errorMessage === 'Peripheral Disconnected') {
            commit('ccaComm/removeIsConnectedTo', device, {root: true});
            commit('ccaComm/setLostConnection',
              {
                device: device,
                hasLostConnection: true,
              },
              {root: true}
            );
          }

          commit('ccaComm/setIsConnectingTo', null, {root: true});
          reject(error);
        }
      );
    });
  },
```

One the success we trigger a 'registerNotification' call which will 

  ```
registerNotification: ({dispatch}, device) => {
    log.debug('TigoBle2:registerNotification');

    return new Promise((resolve) => {
      window.ble.startNotification(device.id,
        TIGO_SERVICES.SERVICE_ID,
        TIGO_SERVICES.RN_CHAR_ID,
        (success) => {
          console.log('TigoBle2:registerNotification:success:', success);
          dispatch('ccaComm/subscribeResult', {device: device, payload: success}, {root: true});
        },
        (error) => {
          console.error('TigoBle2:registerNotification:error:', error);
        }
      );

      resolve(true);
    });
  },
```

This is where our console log for success never fires for iOS, but the log 'TigoBle2:registerNotification' does fire. We can see when  breakpointing this as well. Android implementation is fine.

We have registerNotification resolve true always so our app can proceed with the connection process. Once the user is connected we connect to our device to get device info, which never returns.

![273949921_679598103452884_5358813386635992207_n](https://user-images.githubusercontent.com/75696293/155197805-724c58a7-ff70-439b-9b15-0c62bfe0dd7b.jpg)
![273895931_370224591276919_8010445571756475268_n](https://user-images.githubusercontent.com/75696293/155197808-5551c933-a6cb-4256-b592-a4319e7e0cf5.jpg)


Disconnecting from the device triggers the startNotification error scenario

**Comment by peitschie** [comment]
Right!

I see what you're describing. This is actually an API difference between this plugin and the randdusing's plugin.

This plugin doesn't have any "notify has subscribed" reply, so the only time that success callback will be invoked is when the peripheral actually sends a notification.

This is a shortcoming with this plugin's API, however I can't modify it without breaking backwards compatibility in unexpected ways.

I'm very open to suggestions however on how to implement such a hook in a way that doesn't impact the existing API though.

(more discussion on #635)

**Comment by tigohenryschultz** [comment]
I don't expect a successfully subscribed message, as you can see in my code that promise returns right away, regardless of success.

But after sending it a command I expect the success, which does not fire.

**Comment by tigohenryschultz** [comment]
@peitschie I created this sample project that should show the problem on iOS.

https://github.com/tigohenryschultz/don-ionic--vue-ble-sample

Let me know if you have any questions/troubles testing this sample: 

Android works fine but iOS gets stuck writing the commands and don't resolve success/error

**Comment by peitschie** [comment]
@tigohenryschultz what are the commands I need to run this on my phone?

I haven't dabbled much in ionic directly, so presume it's some variant of `iconic start`?

**Comment by tigohenryschultz** [comment]
For iOS you will need to run 

1. npm i
2. npx cap sync ios
3. ionic cap run ios -l --external

From xcode you may have to setup the signing/certificate stuff, but you should be able to run to the phone.

**Comment by peitschie** [comment]
Ah. Found it... this is another API difference between the randdusing plugin and this one 🙂

The `write` command expects an `ArrayBuffer`, not a base64-encoded string. If you write a string (rather than the correct type), it looks like it just silently fails!

If I make this tweak to your app, I now get the write response back (which was missing):
![image](https://user-images.githubusercontent.com/1052079/155433373-1b4e6646-2bee-4eb7-9103-a2e992d431c2.png)

What's interesting is that this works on Android... I wonder if the Android cordova wrappers automatically detect and decode the base64 string 🤔

**Comment by peitschie** [comment]
@tigohenryschultz I've pushed cordova-plugin-ble-central@1.4.4-alpha.3 with two tweaks.

1. If the type is a base64 string, automatically decode to the proper `NSData` type
2. If the type is not an NSData and cannot be coerced, an error is now raised to indicate the type is incorrect

Between these two, your issue here should hopefully be fixed 🛩️

**Comment by tigohenryschultz** [comment]
@peitschie  your awesome man! I'll test first thing tomorrow morning

**Comment by tigohenryschultz** [comment]
This build is working great on iOS and Android for me, thanks! @peitschie

**Comment by peitschie** [comment]
@tigohenryschultz fantastic. I'll cut a release next week... I'm just finishing up a bit more testing on the changes here.
