### ISSUE TITLE
adding support for bonding in iOS

### ISSUE THREAD

**Issue by Antorai78** [don/cordova-plugin-ble-central#908]
Is it possible to pair a bluetooth device using the bonding procedure on iOS as it happens on Android by implementing the BluetoothDevice.createBond method?

**Comment by peitschie** [comment]
Hi @Antorai78 

There's no equivalent in iOS to the createBond method. The Apple [Accessory Design Guidelines](https://developer.apple.com/accessories/Accessory-Design-Guidelines.pdf) outline how bonding is performed automatically in the background however (see section 40.10).

The short version is that simply interacting with an encrypted characteristic will trigger iOS to create a bond between the peripheral and phone (incidentally, this is pretty close to the same behaviour on Android as well, if `createBond` is not invoked manually).

**Comment by peitschie** [comment]
Closing this out, as without native support there's nothing reasonable the plugin can provide here. Feel free to continue discussion here however 🙂
