### ISSUE TITLE
How to check if LocationEnabled on IOS

### ISSUE THREAD

**Issue by playrobotics-alex** [don/cordova-plugin-ble-central#911]
Hi!
I am using isLocationEnabled() and it works perfectly on Android but seems not to work on IOS.
If I understand correctly isLocationEnabled is not supported on IOS...
What can I do instead?

Thanks :-)

**Comment by peitschie** [comment]
Hi @playrobotics-alex 

It's not necessary on iOS... I'd just skip the check all together! You can use [device.platform](https://cordova.apache.org/docs/en/11.x/reference/cordova-plugin-device/index.html#deviceplatform) from the `cordova-plugin-device` to sniff which platform is in use.

**Comment by playrobotics-alex** [comment]
Got it! Thanks 👍
