### ISSUE TITLE
callback when device connect or disconnect

### ISSUE THREAD

**Issue by mehmetkaynak** [don/cordova-plugin-ble-central#915]
Is it possible callback in background when user connect any bluetooth device or disconnect device?

**Comment by peitschie** [comment]
Hi @mehmetkaynak 

On iOS this is definitely possible, see: https://github.com/don/cordova-plugin-ble-central#background-scanning-and-notifications-on-ios

In these cases however,  you will only be notified when a device you have specifically connected to successfully goes online, or disconnects.

There's no way to subscribe to **any** device just connecting or disconnecting.
