### ISSUE TITLE
Parameters on scan API

### ISSUE THREAD

**Issue by pascualguerrerocolmenero** [don/cordova-plugin-ble-central#918]
Hi, the documentation shows that there are 4 parameters to be passed to the scan method, but when I use the plugin with ionic it only lets 2 parameters to be applied which are the services and seconds.

**Comment by peitschie** [comment]
Hi @pascualguerrerocolmenero 

The ionic wrapper is maintained separately.

The wrapper itself effectively turns these into observables I believe, hence why you don't need 4 parameters, but rather just two.

**Comment by pascualguerrerocolmenero** [comment]
Thanks for the response!
