### ISSUE TITLE
Address iOS deprecations and issues

### ISSUE THREAD

**Issue by nunoarruda** [don/cordova-plugin-ble-central#919]
There's a bunch of issues and deprecated stuff in the plugin:
<img width="748" alt="Screenshot 2022-06-15 at 15 05 22" src="https://user-images.githubusercontent.com/1189149/173847440-12b96531-2f27-4f67-9bf7-ef6833d295d3.png">

Maybe this should be addressed in order for the plugin to be "future proof"?

I'm not a native developer so I'm unable to create a PR for those.

**Comment by sam-higgs** [comment]
Any updates on this?

**Comment by peitschie** [comment]
Hi @sam-higgs 

I am definitely open to a pull request tackling this 🙂
