### ISSUE TITLE
scanning not work on android 

### ISSUE THREAD

**Issue by KinG-InFeT** [don/cordova-plugin-ble-central#92]
the scanning not work in android device.
i use this code for testing
https://gist.github.com/KinG-InFeT/e16a42659cc47a70397c

fix?

**Comment by don** [comment]
Your [example code](https://gist.github.com/KinG-InFeT/e16a42659cc47a70397c) works with Cordova 5.3.1 running on my Nexus 5 with Android 5.1.1.

![screenshot_2015-09-11-13-09-52](https://cloud.githubusercontent.com/assets/3133/9821335/a2e87a4c-5887-11e5-9dde-f82243534df7.png)


If you're not near any BLE devices, your example won't find anything, but it won't give you an error either. Use [nRF Master Control Panel](https://play.google.com/store/apps/details?id=no.nordicsemi.android.mcp&hl=en) on your phone to see if there are any Bluetooth LE peripherals near you.
