### ISSUE TITLE
readRSSI value showing only once after connect . Need updated RSSI value each time .

### ISSUE THREAD

**Issue by prasadrokade09** [don/cordova-plugin-ble-central#920]
async getRSSI(peripheral) {
    BleManager.retrieveServices(peripheral.id).then((peripheralData) => {
      console.log('Retrieved peripheral services', peripheralData);
      BleManager.readRSSI(peripheral.id).then((rssi) => {
        console.log('Retrieved actual RSSI value', rssi);
      });
    });
  }
I am using this method to get RSSI value . Currently the code  is executing only once when I connected to BLE device. Is that any solution for that or any other method is present in library which gives me updated RSSI value? Please help!!!

**Comment by peitschie** [comment]
I think you might have the wrong plugin @prasadrokade09 ... that looks like something from [react-native-ble-manager](https://github.com/innoveit/react-native-ble-manager)
