### ISSUE TITLE
Legacy advertisement device not discovered when targeting Android 12 

### ISSUE THREAD

**Issue by sam-higgs** [don/cordova-plugin-ble-central#943]
The following device is very rarely returned when targeting Android 12 (v1.5.2), previously it was always found when using v1.4.1, any ideas? are certain devices "ignored"?

A basic bluetooth scanner app finds it all the time, granted with limited information:

![Screenshot_20221109_165916_nRF Connect](https://user-images.githubusercontent.com/70139611/200894996-a0bdfab9-f2a7-42af-b8a2-eac5553e36af.jpg)

**Comment by peitschie** [comment]
Interesting to know @sam-higgs ! Thanks for investigating this.

I've very recently created a `slim` variant of this package which removes the AndroidManifest.xml permissions completely, so an integrating application can specify whatever custom combinations are required. If you need to have the `neverForLocation` flag removed, I'd suggest this is the best way to achieve that goal.

To use this variant of the plugin instead, you can install the `cordova-plugin-ble-central@slim` package, and add a `config-file` element to `config.xml` with the exact Android permissions you want for your app. For example, the default set excluding the `neverForLocation` flag is:

```
<config-file target="AndroidManifest.xml" parent="/manifest">
    <uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION" android:maxSdkVersion="28" />
    <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" android:maxSdkVersion="30" />
    <uses-permission android:name="android.permission.BLUETOOTH" android:maxSdkVersion="30" />
    <uses-permission android:name="android.permission.BLUETOOTH_ADMIN" android:maxSdkVersion="30" />
    <uses-permission android:name="android.permission.BLUETOOTH_SCAN" />
    <uses-permission android:name="android.permission.BLUETOOTH_CONNECT" />
</config-file>
```

**Comment by peitschie** [comment]
I'll close this issue, as it seems like you've managed to figure out what causes the inconsistency. If you have any issues with the `slim` approach above (or have better ideas here!), feel free to continue the discussion here 🙂

**Comment by sam-higgs** [comment]
@peitschie Yeah this is the approach we went for, seems to work - thanks for the quick response :)

**Comment by hongwei98** [comment]
@peitschie i removed android:usesPermissionFlags, the scan not working anymore

**Comment by peitschie** [comment]
@hongwei98 was it working prior to removing those flags?

**Comment by hongwei98** [comment]
> 

yes, not removing the flags is working but it was not able to scan the legacy advertisement

**Comment by peitschie** [comment]
If you remove the flag, I suspect you'll need to add a runtime request for `android.permission.ACCESS_FINE_LOCATION` instead. 

This can be done by using something like the cordova-diagnostic-plugin `requestRuntimePermissions` ([docs](https://github.com/dpa99c/cordova-diagnostic-plugin#requestruntimepermissions)) prior to starting the scan.
