### ISSUE TITLE
Connect 2 tablets via BLE Central

### ISSUE THREAD

**Issue by markarupert** [don/cordova-plugin-ble-central#948]
I have been using this plugin for years with great success to connect to peripherals.

Can I use this to connect 2 tablets and pas data back and forth? If so I am having trouble finding the calls I would use to accept the connection (act as the peripheral).

What am I missing?

**Comment by peitschie** [comment]
Hi @markarupert ,

You're not missing anything 😅  . This plugin won't help for the peripheral side of things.

You can try https://github.com/don/cordova-plugin-ble-peripheral which might work for your needs.

I'll close this out, but feel free to continue the discussion here!
