### ISSUE TITLE
iOS9 and xCode7 compiling issue

### ISSUE THREAD

**Issue by jonalling** [don/cordova-plugin-ble-central#96]
Cordova and Ionic have all been updated to latest releases, but I am getting this issue when trying to build the project in xCode. It specifically only seems to fail on the cordovaBLE plugin. If I remove the plugin, it builds with no errors.

** BUILD FAILED **

The following build commands failed:
CompileC build/cordovaDev.build/Debug-iphonesimulator/cordovaDev.build/Objects-normal/i386/BLECentralPlugin.o cordovaDev/Plugins/com.megster.cordova.ble/BLECentralPlugin/BLECentralPlugin.m normal i386 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)
Error code 65 for command: xcodebuild with args:

**Comment by don** [comment]
Try version 1.0.0 of the plugin from npm. https://www.npmjs.com/package/cordova-plugin-ble-central

Note that you should use the new plugin id cordova-plugin-ble-central instead of com.megster.cordova.ble.

**Comment by jonalling** [comment]
Yes, I added the plugin back in after removing it using the new id and it builds with no errors and works properly now.  Thanks.
