### ISSUE TITLE
Which method in Android handles the responses from characteristic?

### ISSUE THREAD

**Issue by RomainGoncalves** [don/cordova-plugin-ble-central#98]
Hello,

I found that in iOS the method handling responses sent TO characteristics from the devices was ```didUpdateValueForCharacteristic```
. Now which is the method handling that in Android's side? I've looked at the code and I'm not entirely sure.

Thanks for any help.

**Comment by don** [comment]
Try [BluetoothGattCallback](https://developer.android.com/reference/android/bluetooth/BluetoothGattCallback.html).
