### ISSUE TITLE
ble.setPin not supported on iOS

### ISSUE THREAD

**Issue by ZdenCo** [don/cordova-plugin-ble-central#991]
I have programatically generated pin that I need to assign to the bonding dialog, on Android this works as expected but on iOS it does not. 
I connect to the device, send writeWithoutResponse which will trigger pin dialog on iOS. I tried to call the set pin before the write and after but nothing seems to work.

**Comment by peitschie** [comment]
@ZdenCo iOS doesn't have a `setPin` implementation at all, so that behaviour is expected, though not helpful for your usecase.

I don't actually know how to achieve PIN entry with iOS... I don't suppose you do know how?
